var fs = require('fs');
var path = require('path');
var lines = [];

function addCode(code, desc, cat, ex1, ex2, inc, cu, doc) {
  ex1 = ex1 || []; ex2 = ex2 || []; inc = inc || []; cu = cu || []; doc = doc || [];
  var s = '  codes["' + code + '"] = { code: "' + code + '", description: "' + desc.replace(/"/g, '\\"') + '", category: "' + cat + '", excludes1: [' + ex1.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '], excludes2: [' + ex2.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '], includes: [' + inc.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '], commonUse: [' + cu.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '], documentation: [' + doc.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '] };';
  lines.push(s);
}

function addSimple(code, desc, cat, cu) {
  addCode(code, desc, cat, [], [], [], cu || [], []);
}

var allCodes = [];

// ========== CHAPTER II: NEOPLASMS ==========
// Lip C00
allCodes.push(["C00.0","Malignant neoplasm of upper lip, vermilion border","C00",["Cancer of upper lip"]]);
allCodes.push(["C00.1","Malignant neoplasm of lower lip, vermilion border","C00",["Cancer of lower lip"]]);
allCodes.push(["C00.3","Malignant neoplasm of upper lip, inner aspect","C00",["Inner lip cancer"]]);
allCodes.push(["C00.4","Malignant neoplasm of lower lip, inner aspect","C00",["Inner lip cancer"]]);
allCodes.push(["C00.5","Malignant neoplasm of lip, unspecified, external","C00",["Lip cancer NOS"]]);
allCodes.push(["C00.6","Malignant neoplasm of commissure of lip","C00",["Lip commissure cancer"]]);
allCodes.push(["C00.9","Malignant neoplasm of lip, unspecified","C00",["Lip cancer NOS"]]);
// Tongue C01-C02
allCodes.push(["C01.9","Malignant neoplasm of base of tongue","C01",["Base of tongue cancer"]]);
allCodes.push(["C02.0","Malignant neoplasm of dorsal surface of tongue","C02",["Dorsal tongue cancer"]]);
allCodes.push(["C02.1","Malignant neoplasm of border of tongue","C02",["Lateral tongue cancer"]]);
allCodes.push(["C02.2","Malignant neoplasm of ventral surface of tongue","C02",["Floor of mouth cancer"]]);
allCodes.push(["C02.3","Malignant neoplasm of anterior two-thirds of tongue, part unspecified","C02",["Tongue cancer NOS"]]);
allCodes.push(["C02.4","Malignant neoplasm of lingual tonsil","C02",["Lingual tonsil cancer"]]);
allCodes.push(["C02.9","Malignant neoplasm of tongue, unspecified","C02",["Tongue cancer NOS"]]);
// Gum C03
allCodes.push(["C03.0","Malignant neoplasm of upper gum","C03",["Upper gum cancer"]]);
allCodes.push(["C03.1","Malignant neoplasm of lower gum","C03",["Lower gum cancer"]]);
allCodes.push(["C03.9","Malignant neoplasm of gum, unspecified","C03",["Gum cancer NOS"]]);
// Floor of mouth C04
allCodes.push(["C04.0","Malignant neoplasm of anterior floor of mouth","C04",["Floor of mouth cancer"]]);
allCodes.push(["C04.1","Malignant neoplasm of lateral floor of mouth","C04",["Floor of mouth cancer"]]);
allCodes.push(["C04.9","Malignant neoplasm of floor of mouth, unspecified","C04",["Floor of mouth cancer NOS"]]);
// Palate C05
allCodes.push(["C05.0","Malignant neoplasm of hard palate","C05",["Hard palate cancer"]]);
allCodes.push(["C05.1","Malignant neoplasm of soft palate","C05",["Soft palate cancer"]]);
allCodes.push(["C05.2","Malignant neoplasm of uvula","C05",["Uvula cancer"]]);
allCodes.push(["C05.9","Malignant neoplasm of palate, unspecified","C05",["Palate cancer NOS"]]);
// Mouth C06
allCodes.push(["C06.0","Malignant neoplasm of cheek mucosa","C06",["Cheek mucosa cancer"]]);
allCodes.push(["C06.1","Malignant neoplasm of vestibule of mouth","C06",["Vestibule cancer"]]);
allCodes.push(["C06.2","Malignant neoplasm of retromolar area","C06",["Retromolar cancer"]]);
allCodes.push(["C06.8","Malignant neoplasm of other specified parts of mouth","C06",["Mouth cancer"]]);
allCodes.push(["C06.9","Malignant neoplasm of mouth, unspecified","C06",["Mouth cancer NOS"]]);
// Salivary glands C07-C08
allCodes.push(["C07.9","Malignant neoplasm of parotid gland","C07",["Parotid gland cancer","Salivary gland tumor"]]);
allCodes.push(["C08.0","Malignant neoplasm of submandibular gland","C08",["Submandibular gland cancer"]]);
allCodes.push(["C08.1","Malignant neoplasm of sublingual gland","C08",["Sublingual gland cancer"]]);
allCodes.push(["C08.9","Malignant neoplasm of major salivary gland, unspecified","C08",["Salivary gland cancer NOS"]]);
// Tonsil C09
allCodes.push(["C09.0","Malignant neoplasm of tonsillar fossa","C09",["Tonsillar fossa cancer"]]);
allCodes.push(["C09.1","Malignant neoplasm of tonsillar pillar","C09",["Tonsillar pillar cancer"]]);
allCodes.push(["C09.9","Malignant neoplasm of tonsil, unspecified","C09",["Tonsil cancer NOS"]]);
// Oropharynx C10
allCodes.push(["C10.0","Malignant neoplasm of vallecula","C10",["Vallecula cancer"]]);
allCodes.push(["C10.1","Malignant neoplasm of anterior surface of epiglottis","C10",["Epiglottis cancer"]]);
allCodes.push(["C10.2","Malignant neoplasm of lateral wall of oropharynx","C10",["Oropharynx cancer"]]);
allCodes.push(["C10.3","Malignant neoplasm of posterior wall of oropharynx","C10",["Oropharynx cancer"]]);
allCodes.push(["C10.4","Malignant neoplasm of tonsillar region","C10",["Tonsillar region cancer"]]);
allCodes.push(["C10.9","Malignant neoplasm of oropharynx, unspecified","C10",["Oropharynx cancer NOS"]]);
// Nasopharynx C11
allCodes.push(["C11.0","Malignant neoplasm of nasopharynx","C11",["Nasopharyngeal cancer"]]);
allCodes.push(["C11.1","Malignant neoplasm of roof of nasopharynx","C11",["Nasopharyngeal cancer"]]);
allCodes.push(["C11.2","Malignant neoplasm of posterior wall of nasopharynx","C11",["Nasopharyngeal cancer"]]);
allCodes.push(["C11.3","Malignant neoplasm of lateral wall of nasopharynx","C11",["Nasopharyngeal cancer"]]);
allCodes.push(["C11.9","Malignant neoplasm of nasopharynx, unspecified","C11",["Nasopharyngeal cancer NOS"]]);
// Hypopharynx C13
allCodes.push(["C13.0","Malignant neoplasm of postcricoid region","C13",["Postcricoid cancer"]]);
allCodes.push(["C13.1","Malignant neoplasm of hypopharyngeal aspect of aryepiglottic fold","C13",["Hypopharynx cancer"]]);
allCodes.push(["C13.2","Malignant neoplasm of posterior wall of hypopharynx","C13",["Hypopharynx cancer"]]);
allCodes.push(["C13.9","Malignant neoplasm of hypopharynx, unspecified","C13",["Hypopharynx cancer NOS"]]);
// Pharynx C14
allCodes.push(["C14.0","Malignant neoplasm of pharynx, unspecified","C14",["Pharyngeal cancer NOS"]]);
allCodes.push(["C14.2","Malignant neoplasm of Waldeyer ring","C14",["Waldeyer ring cancer"]]);
allCodes.push(["C14.8","Malignant neoplasm of other sites of lip, oral cavity and pharynx","C14",["Oral cavity cancer"]]);
// Esophagus C15
allCodes.push(["C15.3","Malignant neoplasm of upper third of esophagus","C15",["Esophageal cancer - upper"]]);
allCodes.push(["C15.4","Malignant neoplasm of middle third of esophagus","C15",["Esophageal cancer - middle"]]);
allCodes.push(["C15.5","Malignant neoplasm of lower third of esophagus","C15",["Esophageal cancer - lower"]]);
allCodes.push(["C15.9","Malignant neoplasm of esophagus, unspecified","C15",["Esophageal cancer NOS"]]);
// Stomach C16
allCodes.push(["C16.0","Malignant neoplasm of cardia","C16",["Gastric cardia cancer"]]);
allCodes.push(["C16.1","Malignant neoplasm of fundus of stomach","C16",["Gastric fundus cancer"]]);
allCodes.push(["C16.2","Malignant neoplasm of body of stomach","C16",["Gastric body cancer"]]);
allCodes.push(["C16.3","Malignant neoplasm of pyloric antrum","C16",["Gastric antrum cancer"]]);
allCodes.push(["C16.4","Malignant neoplasm of pylorus","C16",["Gastric pylorus cancer"]]);
allCodes.push(["C16.9","Malignant neoplasm of stomach, unspecified","C16",["Stomach cancer NOS","Gastric cancer"]]);
// Small intestine C17
allCodes.push(["C17.0","Malignant neoplasm of duodenum","C17",["Duodenal cancer"]]);
allCodes.push(["C17.1","Malignant neoplasm of jejunum","C17",["Jejunal cancer"]]);
allCodes.push(["C17.2","Malignant neoplasm of ileum","C17",["Ileal cancer"]]);
allCodes.push(["C17.9","Malignant neoplasm of small intestine, unspecified","C17",["Small bowel cancer NOS"]]);
// Colon C18-C20
allCodes.push(["C18.0","Malignant neoplasm of cecum","C18",["Cecal cancer"]]);
allCodes.push(["C18.1","Malignant neoplasm of appendix","C18",["Appendiceal cancer"]]);
allCodes.push(["C18.2","Malignant neoplasm of ascending colon","C18",["Ascending colon cancer"]]);
allCodes.push(["C18.3","Malignant neoplasm of hepatic flexure","C18",["Hepatic flexure cancer"]]);
allCodes.push(["C18.4","Malignant neoplasm of transverse colon","C18",["Transverse colon cancer"]]);
allCodes.push(["C18.5","Malignant neoplasm of splenic flexure","C18",["Splenic flexure cancer"]]);
allCodes.push(["C18.6","Malignant neoplasm of descending colon","C18",["Descending colon cancer"]]);
allCodes.push(["C18.7","Malignant neoplasm of sigmoid colon","C18",["Sigmoid colon cancer"]]);
allCodes.push(["C18.9","Malignant neoplasm of colon, unspecified","C18",["Colon cancer NOS","Colorectal cancer"]]);
allCodes.push(["C19","Malignant neoplasm of rectosigmoid junction","C18",["Rectosigmoid cancer"]]);
allCodes.push(["C20","Malignant neoplasm of rectum","C18",["Rectal cancer"]]);
// Anus C21
allCodes.push(["C21.0","Malignant neoplasm of anus, unspecified","C18",["Anal cancer NOS"]]);
allCodes.push(["C21.1","Malignant neoplasm of anal canal","C18",["Anal canal cancer"]]);
allCodes.push(["C21.2","Malignant neoplasm of cloacogenic zone","C18",["Cloacogenic cancer"]]);
allCodes.push(["C21.8","Malignant neoplasm of overlapping sites of rectum, anus and anal canal","C18",["Rectal/anal cancer"]]);
// Liver C22-C24
allCodes.push(["C22.0","Malignant neoplasm of liver","C22",["Hepatocellular carcinoma","Liver cancer","HCC"]]);
allCodes.push(["C22.1","Malignant neoplasm of intrahepatic bile duct","C22",["Cholangiocarcinoma"]]);
allCodes.push(["C22.2","Hepatoblastoma","C22",["Pediatric liver tumor"]]);
allCodes.push(["C22.9","Malignant neoplasm of liver, unspecified","C22",["Liver cancer NOS"]]);
allCodes.push(["C23","Malignant neoplasm of gallbladder","C22",["Gallbladder cancer"]]);
allCodes.push(["C24.0","Malignant neoplasm of extrahepatic bile duct","C22",["Bile duct cancer"]]);
allCodes.push(["C24.1","Malignant neoplasm of ampulla of Vater","C22",["Ampullary cancer"]]);
allCodes.push(["C24.9","Malignant neoplasm of biliary tract, unspecified","C22",["Biliary cancer NOS"]]);
// Pancreas C25
allCodes.push(["C25.0","Malignant neoplasm of head of pancreas","C25",["Pancreatic head cancer"]]);
allCodes.push(["C25.1","Malignant neoplasm of body of pancreas","C25",["Pancreatic body cancer"]]);
allCodes.push(["C25.2","Malignant neoplasm of tail of pancreas","C25",["Pancreatic tail cancer"]]);
allCodes.push(["C25.3","Malignant neoplasm of pancreatic duct","C25",["Pancreatic duct cancer"]]);
allCodes.push(["C25.4","Malignant neoplasm of endocrine pancreas","C25",["Pancreatic islet cell tumor"]]);
allCodes.push(["C25.9","Malignant neoplasm of pancreas, unspecified","C25",["Pancreatic cancer NOS"]]);
// Other digestive C26
allCodes.push(["C26.9","Malignant neoplasm of ill-defined sites within the digestive system","C25",["Digestive cancer NOS"]]);
// Nasal/Ear C30-C31
allCodes.push(["C30.0","Malignant neoplasm of nasal cavity","C30",["Nasal cavity cancer"]]);
allCodes.push(["C30.1","Malignant neoplasm of middle ear","C30",["Middle ear cancer"]]);
allCodes.push(["C31.0","Malignant neoplasm of maxillary sinus","C31",["Maxillary sinus cancer"]]);
allCodes.push(["C31.1","Malignant neoplasm of ethmoidal sinus","C31",["Ethmoid sinus cancer"]]);
allCodes.push(["C31.9","Malignant neoplasm of sinus, unspecified","C31",["Sinus cancer NOS"]]);
// Larynx C32
allCodes.push(["C32.0","Malignant neoplasm of glottis","C32",["Glottic cancer","Laryngeal cancer"]]);
allCodes.push(["C32.1","Malignant neoplasm of supraglottis","C32",["Supraglottic cancer"]]);
allCodes.push(["C32.9","Malignant neoplasm of larynx, unspecified","C32",["Laryngeal cancer NOS"]]);
// Trachea/Bronchus/Lung C33-C34
allCodes.push(["C33","Malignant neoplasm of trachea","C32",["Tracheal cancer"]]);
allCodes.push(["C34.0","Malignant neoplasm of main bronchus","C34",["Bronchial cancer"]]);
allCodes.push(["C34.1","Malignant neoplasm of upper lobe, bronchus or lung","C34",["Upper lobe lung cancer"]]);
allCodes.push(["C34.2","Malignant neoplasm of middle lobe, bronchus or lung","C34",["Middle lobe lung cancer"]]);
allCodes.push(["C34.3","Malignant neoplasm of lower lobe, bronchus or lung","C34",["Lower lobe lung cancer"]]);
allCodes.push(["C34.8","Malignant neoplasm of overlapping sites of bronchus and lung","C34",["Lung cancer"]]);
allCodes.push(["C34.9","Malignant neoplasm of bronchus or lung, unspecified","C34",["Lung cancer NOS","NSCLC","SCLC"]]);
// Thymus/Heart/Mediastinum/Pleura C37-C39
allCodes.push(["C37","Malignant neoplasm of thymus","C34",["Thymic cancer"]]);
allCodes.push(["C38.0","Malignant neoplasm of heart","C34",["Cardiac tumor"]]);
allCodes.push(["C38.1","Malignant neoplasm of anterior mediastinum","C34",["Anterior mediastinal tumor"]]);
allCodes.push(["C38.2","Malignant neoplasm of posterior mediastinum","C34",["Posterior mediastinal tumor"]]);
allCodes.push(["C38.3","Malignant neoplasm of mediastinum, unspecified","C34",["Mediastinal cancer NOS"]]);
allCodes.push(["C38.4","Malignant neoplasm of pleura","C34",["Mesothelioma","Pleural cancer"]]);
allCodes.push(["C38.8","Malignant neoplasm of overlapping sites of heart, mediastinum and pleura","C34",["Cardiothoracic cancer"]]);
// Bone C40-C41
allCodes.push(["C40.0","Malignant neoplasm of scapula and long bones of upper limb","C40",["Upper limb bone cancer"]]);
allCodes.push(["C40.1","Malignant neoplasm of short bones of upper limb","C40",["Hand bone cancer"]]);
allCodes.push(["C40.2","Malignant neoplasm of long bones of lower limb","C40",["Lower limb bone cancer"]]);
allCodes.push(["C40.3","Malignant neoplasm of short bones of lower limb","C40",["Foot bone cancer"]]);
allCodes.push(["C40.9","Malignant neoplasm of bone and articular cartilage of limb, unspecified","C40",["Extremity bone cancer"]]);
allCodes.push(["C41.0","Malignant neoplasm of bones of skull and face","C41",["Skull bone cancer"]]);
allCodes.push(["C41.1","Malignant neoplasm of mandible","C41",["Jaw cancer"]]);
allCodes.push(["C41.2","Malignant neoplasm of vertebral column","C41",["Spinal bone cancer"]]);
allCodes.push(["C41.3","Malignant neoplasm of ribs, sternum and clavicle","C41",["Chest wall bone cancer"]]);
allCodes.push(["C41.4","Malignant neoplasm of pelvic bones, sacrum and coccyx","C41",["Pelvic bone cancer"]]);
allCodes.push(["C41.9","Malignant neoplasm of bone and articular cartilage, unspecified","C41",["Bone cancer NOS"]]);
// Melanoma C43
allCodes.push(["C43.0","Malignant melanoma of lip","C43",["Lip melanoma"]]);
allCodes.push(["C43.1","Malignant melanoma of eyelid","C43",["Eyelid melanoma"]]);
allCodes.push(["C43.2","Malignant melanoma of ear","C43",["Ear melanoma"]]);
allCodes.push(["C43.3","Malignant melanoma of other parts of face","C43",["Facial melanoma"]]);
allCodes.push(["C43.4","Malignant melanoma of scalp and neck","C43",["Scalp melanoma"]]);
allCodes.push(["C43.5","Malignant melanoma of trunk","C43",["Trunk melanoma"]]);
allCodes.push(["C43.6","Malignant melanoma of upper limb, including shoulder","C43",["Upper limb melanoma"]]);
allCodes.push(["C43.7","Malignant melanoma of lower limb, including hip","C43",["Lower limb melanoma"]]);
allCodes.push(["C43.9","Malignant melanoma of skin, unspecified","C43",["Melanoma NOS"]]);
// Skin C44
allCodes.push(["C44.0","Other and unspecified malignant neoplasm of skin of lip","C44",["Lip skin cancer"]]);
allCodes.push(["C44.1","Other and unspecified malignant neoplasm of eyelid","C44",["Eyelid skin cancer"]]);
allCodes.push(["C44.2","Other and unspecified malignant neoplasm of ear","C44",["Ear skin cancer"]]);
allCodes.push(["C44.3","Other and unspecified malignant neoplasm of skin of face","C44",["Facial skin cancer"]]);
allCodes.push(["C44.4","Other and unspecified malignant neoplasm of scalp and neck","C44",["Scalp skin cancer"]]);
allCodes.push(["C44.5","Other and unspecified malignant neoplasm of skin of trunk","C44",["Trunk skin cancer"]]);
allCodes.push(["C44.6","Other and unspecified malignant neoplasm of skin of upper limb","C44",["Upper limb skin cancer"]]);
allCodes.push(["C44.7","Other and unspecified malignant neoplasm of skin of lower limb","C44",["Lower limb skin cancer"]]);
allCodes.push(["C44.9","Other and unspecified malignant neoplasm of skin, unspecified","C44",["Skin cancer NOS","BCC","SCC"]]);
// Mesothelioma C45
allCodes.push(["C45.0","Mesothelioma of pleura","C44",["Pleural mesothelioma"]]);
allCodes.push(["C45.1","Mesothelioma of peritoneum","C44",["Peritoneal mesothelioma"]]);
allCodes.push(["C45.9","Mesothelioma, unspecified","C44",["Mesothelioma NOS"]]);
// Kaposi C46
allCodes.push(["C46.0","Kaposi sarcoma of skin","C44",["Kaposi sarcoma - skin"]]);
allCodes.push(["C46.1","Kaposi sarcoma of soft tissue","C44",["Kaposi sarcoma - soft tissue"]]);
allCodes.push(["C46.3","Kaposi sarcoma of lymph nodes","C44",["Kaposi sarcoma - lymph nodes"]]);
allCodes.push(["C46.9","Kaposi sarcoma, unspecified","C44",["Kaposi sarcoma NOS"]]);
// Nerves C47
allCodes.push(["C47.0","Malignant neoplasm of peripheral nerves of head, face and neck","C47",["Head nerve tumor"]]);
allCodes.push(["C47.1","Malignant neoplasm of peripheral nerves of upper limb","C47",["Upper limb nerve tumor"]]);
allCodes.push(["C47.2","Malignant neoplasm of peripheral nerves of lower limb","C47",["Lower limb nerve tumor"]]);
allCodes.push(["C47.9","Malignant neoplasm of peripheral nerves, unspecified","C47",["Nerve cancer NOS"]]);
// Retroperitoneum/Peritoneum C48
allCodes.push(["C48.0","Malignant neoplasm of retroperitoneum","C47",["Retroperitoneal cancer"]]);
allCodes.push(["C48.1","Malignant neoplasm of specified parts of peritoneum","C47",["Peritoneal cancer"]]);
allCodes.push(["C48.2","Malignant neoplasm of peritoneum, unspecified","C47",["Peritoneal cancer NOS"]]);
// Connective/soft tissue C49
allCodes.push(["C49.0","Malignant neoplasm of connective tissue of head, face and neck","C49",["Head soft tissue sarcoma"]]);
allCodes.push(["C49.1","Malignant neoplasm of connective tissue of upper limb","C49",["Upper limb soft tissue sarcoma"]]);
allCodes.push(["C49.2","Malignant neoplasm of connective tissue of lower limb","C49",["Lower limb soft tissue sarcoma"]]);
allCodes.push(["C49.3","Malignant neoplasm of connective tissue of thorax","C49",["Thoracic soft tissue sarcoma"]]);
allCodes.push(["C49.4","Malignant neoplasm of connective tissue of abdomen","C49",["Abdominal soft tissue sarcoma"]]);
allCodes.push(["C49.5","Malignant neoplasm of connective tissue of pelvis","C49",["Pelvic soft tissue sarcoma"]]);
allCodes.push(["C49.9","Malignant neoplasm of connective tissue, unspecified","C49",["Soft tissue sarcoma NOS"]]);
// Breast C50
allCodes.push(["C50.0","Malignant neoplasm of nipple and areola of female breast","C50",["Nipple cancer"]]);
allCodes.push(["C50.1","Malignant neoplasm of central portion of female breast","C50",["Central breast cancer"]]);
allCodes.push(["C50.2","Malignant neoplasm of upper-inner quadrant of female breast","C50",["Upper inner quadrant breast cancer"]]);
allCodes.push(["C50.3","Malignant neoplasm of lower-inner quadrant of female breast","C50",["Lower inner quadrant breast cancer"]]);
allCodes.push(["C50.4","Malignant neoplasm of upper-outer quadrant of female breast","C50",["Upper outer quadrant breast cancer"]]);
allCodes.push(["C50.5","Malignant neoplasm of lower-outer quadrant of female breast","C50",["Lower outer quadrant breast cancer"]]);
allCodes.push(["C50.6","Malignant neoplasm of axillary tail of female breast","C50",["Axillary tail breast cancer"]]);
allCodes.push(["C50.8","Malignant neoplasm of overlapping sites of female breast","C50",["Breast cancer"]]);
allCodes.push(["C50.9","Malignant neoplasm of breast, unspecified","C50",["Breast cancer NOS","Invasive breast cancer"]]);
// Female genital C51-C58
allCodes.push(["C51.0","Malignant neoplasm of labium majus","C51",["Labial cancer"]]);
allCodes.push(["C51.1","Malignant neoplasm of labium minus","C51",["Labial cancer"]]);
allCodes.push(["C51.9","Malignant neoplasm of vulva, unspecified","C51",["Vulvar cancer NOS"]]);
allCodes.push(["C52.9","Malignant neoplasm of vagina, unspecified","C52",["Vaginal cancer"]]);
allCodes.push(["C53.0","Malignant neoplasm of endocervix","C53",["Endocervical cancer"]]);
allCodes.push(["C53.1","Malignant neoplasm of exocervix","C53",["Exocervical cancer"]]);
allCodes.push(["C53.9","Malignant neoplasm of cervix uteri, unspecified","C53",["Cervical cancer NOS"]]);
allCodes.push(["C54.1","Malignant neoplasm of endometrium","C54",["Endometrial cancer","Uterine cancer"]]);
allCodes.push(["C54.9","Malignant neoplasm of corpus uteri, unspecified","C54",["Uterine corpus cancer NOS"]]);
allCodes.push(["C55","Malignant neoplasm of uterus, unspecified","C54",["Uterine cancer NOS"]]);
allCodes.push(["C56.9","Malignant neoplasm of ovary, unspecified","C56",["Ovarian cancer NOS"]]);
allCodes.push(["C57.0","Malignant neoplasm of fallopian tube","C56",["Fallopian tube cancer"]]);
allCodes.push(["C57.9","Malignant neoplasm of female genital tract, unspecified","C56",["Female genital cancer NOS"]]);
allCodes.push(["C58","Malignant neoplasm of placenta","C56",["Choriocarcinoma"]]);
// Male genital C60-C63
allCodes.push(["C60.0","Malignant neoplasm of prepuce","C60",["Penile cancer - prepuce"]]);
allCodes.push(["C60.1","Malignant neoplasm of glans penis","C60",["Penile cancer - glans"]]);
allCodes.push(["C60.2","Malignant neoplasm of body of penis","C60",["Penile cancer - body"]]);
allCodes.push(["C60.9","Malignant neoplasm of penis, unspecified","C60",["Penile cancer NOS"]]);
allCodes.push(["C61","Malignant neoplasm of prostate","C61",["Prostate cancer","Prostatic adenocarcinoma"]]);
allCodes.push(["C62.0","Malignant neoplasm of undescended testis","C62",["Cryptorchidism-related testicular cancer"]]);
allCodes.push(["C62.1","Malignant neoplasm of other and unspecified testis","C62",["Testicular cancer"]]);
allCodes.push(["C62.9","Malignant neoplasm of testis, unspecified","C62",["Testicular cancer NOS"]]);
allCodes.push(["C63.9","Malignant neoplasm of male genital organs, unspecified","C62",["Male genital cancer NOS"]]);
// Urinary C64-C68
allCodes.push(["C64.1","Malignant neoplasm of right kidney, except renal pelvis","C64",["Right kidney cancer"]]);
allCodes.push(["C64.2","Malignant neoplasm of left kidney, except renal pelvis","C64",["Left kidney cancer"]]);
allCodes.push(["C64.9","Malignant neoplasm of kidney, except renal pelvis, unspecified","C64",["Renal cell carcinoma","Kidney cancer NOS","RCC"]]);
allCodes.push(["C65.9","Malignant neoplasm of renal pelvis, unspecified","C65",["Renal pelvis cancer NOS"]]);
allCodes.push(["C66.9","Malignant neoplasm of ureter, unspecified","C66",["Ureter cancer NOS"]]);
allCodes.push(["C67.0","Malignant neoplasm of trigone of bladder","C67",["Bladder trigone cancer"]]);
allCodes.push(["C67.1","Malignant neoplasm of dome of bladder","C67",["Bladder dome cancer"]]);
allCodes.push(["C67.2","Malignant neoplasm of lateral wall of bladder","C67",["Bladder lateral wall cancer"]]);
allCodes.push(["C67.3","Malignant neoplasm of anterior wall of bladder","C67",["Bladder anterior wall cancer"]]);
allCodes.push(["C67.4","Malignant neoplasm of bladder neck","C67",["Bladder neck cancer"]]);
allCodes.push(["C67.5","Malignant neoplasm of ureteric orifice","C67",["Ureteric orifice cancer"]]);
allCodes.push(["C67.6","Malignant neoplasm of urachus","C67",["Urachal cancer"]]);
allCodes.push(["C67.7","Malignant neoplasm of posterior wall of bladder","C67",["Bladder posterior wall cancer"]]);
allCodes.push(["C67.8","Malignant neoplasm of overlapping sites of bladder","C67",["Bladder cancer"]]);
allCodes.push(["C67.9","Malignant neoplasm of bladder, unspecified","C67",["Bladder cancer NOS"]]);
allCodes.push(["C68.0","Malignant neoplasm of urethra","C68",["Urethral cancer"]]);
allCodes.push(["C68.1","Malignant neoplasm of paraurethral glands","C68",["Paraurethral gland cancer"]]);
allCodes.push(["C68.9","Malignant neoplasm of urinary organs, unspecified","C68",["Urinary cancer NOS"]]);
// Eye C69
allCodes.push(["C69.0","Malignant neoplasm of conjunctiva","C69",["Conjunctival cancer"]]);
allCodes.push(["C69.1","Malignant neoplasm of cornea","C69",["Corneal cancer"]]);
allCodes.push(["C69.2","Malignant neoplasm of retina","C69",["Retinal cancer","Retinoblastoma"]]);
allCodes.push(["C69.3","Malignant neoplasm of choroid","C69",["Choroidal cancer"]]);
allCodes.push(["C69.4","Malignant neoplasm of ciliary body","C69",["Ciliary body cancer"]]);
allCodes.push(["C69.5","Malignant neoplasm of lacrimal gland and duct","C69",["Lacrimal gland cancer"]]);
allCodes.push(["C69.6","Malignant neoplasm of orbit","C69",["Orbital cancer"]]);
allCodes.push(["C69.9","Malignant neoplasm of eye, unspecified","C69",["Eye cancer NOS"]]);
// Brain C71
allCodes.push(["C71.0","Malignant neoplasm of cerebrum, except lobes and ventricles","C71",["Cerebral cancer"]]);
allCodes.push(["C71.1","Malignant neoplasm of frontal lobe","C71",["Frontal lobe brain cancer"]]);
allCodes.push(["C71.2","Malignant neoplasm of temporal lobe","C71",["Temporal lobe brain cancer"]]);
allCodes.push(["C71.3","Malignant neoplasm of parietal lobe","C71",["Parietal lobe brain cancer"]]);
allCodes.push(["C71.4","Malignant neoplasm of occipital lobe","C71",["Occipital lobe brain cancer"]]);
allCodes.push(["C71.5","Malignant neoplasm of brain ventricle","C71",["Brain ventricle cancer"]]);
allCodes.push(["C71.6","Malignant neoplasm of cerebellum","C71",["Cerebellar cancer"]]);
allCodes.push(["C71.7","Malignant neoplasm of brain stem","C71",["Brain stem cancer"]]);
allCodes.push(["C71.8","Malignant neoplasm of overlapping sites of brain","C71",["Brain cancer"]]);
allCodes.push(["C71.9","Malignant neoplasm of brain, unspecified","C71",["Brain cancer NOS","Glioblastoma"]]);
// Thyroid C73
allCodes.push(["C73","Malignant neoplasm of thyroid gland","C73",["Thyroid cancer"]]);
// Other endocrine C74-C75
allCodes.push(["C74.0","Malignant neoplasm of cortex of adrenal gland","C74",["Adrenal cortical cancer"]]);
allCodes.push(["C74.1","Malignant neoplasm of medulla of adrenal gland","C74",["Pheochromocytoma"]]);
allCodes.push(["C74.9","Malignant neoplasm of adrenal gland, unspecified","C74",["Adrenal cancer NOS"]]);
allCodes.push(["C75.0","Malignant neoplasm of parathyroid gland","C75",["Parathyroid cancer"]]);
allCodes.push(["C75.1","Malignant neoplasm of pituitary gland","C75",["Pituitary cancer"]]);
allCodes.push(["C75.2","Malignant neoplasm of pineal gland","C75",["Pineal tumor"]]);
allCodes.push(["C75.3","Malignant neoplasm of carotid body","C75",["Carotid body tumor"]]);
allCodes.push(["C75.4","Malignant neoplasm of aortic body and other paraganglia","C75",["Paraganglion tumor"]]);
allCodes.push(["C75.5","Malignant neoplasm of unspecified endocrine gland","C75",["Endocrine cancer NOS"]]);
// Ill-defined C76
allCodes.push(["C76.0","Malignant neoplasm of head, face and neck","C76",["Head/face cancer NOS"]]);
allCodes.push(["C76.1","Malignant neoplasm of thorax","C76",["Thoracic cancer NOS"]]);
allCodes.push(["C76.2","Malignant neoplasm of abdomen","C76",["Abdominal cancer NOS"]]);
allCodes.push(["C76.3","Malignant neoplasm of pelvis","C76",["Pelvic cancer NOS"]]);
allCodes.push(["C76.4","Malignant neoplasm of upper limb","C76",["Upper limb cancer NOS"]]);
allCodes.push(["C76.5","Malignant neoplasm of lower limb","C76",["Lower limb cancer NOS"]]);
allCodes.push(["C76.8","Malignant neoplasm of overlapping sites of other and ill-defined sites","C76",["Ill-defined cancer"]]);
allCodes.push(["C76.9","Malignant neoplasm of ill-defined site, unspecified","C76",["Cancer NOS"]]);
// Secondary/ill-defined C77-C80
allCodes.push(["C77.0","Secondary and unspecified malignant neoplasm of lymph nodes of head, face and neck","C77",["Cervical lymph node metastasis"]]);
allCodes.push(["C77.1","Secondary and unspecified malignant neoplasm of intrathoracic lymph nodes","C77",["Mediastinal lymph node metastasis"]]);
allCodes.push(["C77.2","Secondary and unspecified malignant neoplasm of intra-abdominal lymph nodes","C77",["Abdominal lymph node metastasis"]]);
allCodes.push(["C77.3","Secondary and unspecified malignant neoplasm of axillary and upper limb lymph nodes","C77",["Axillary lymph node metastasis"]]);
allCodes.push(["C77.4","Secondary and unspecified malignant neoplasm of inguinal and lower limb lymph nodes","C77",["Inguinal lymph node metastasis"]]);
allCodes.push(["C77.5","Secondary and unspecified malignant neoplasm of intrapelvic lymph nodes","C77",["Pelvic lymph node metastasis"]]);
allCodes.push(["C77.8","Secondary and unspecified malignant neoplasm of multiple lymph nodes","C77",["Lymph node metastasis"]]);
allCodes.push(["C77.9","Secondary and unspecified malignant neoplasm of lymph node, unspecified","C77",["Lymph node metastasis NOS"]]);
allCodes.push(["C78.0","Secondary malignant neoplasm of lung","C78",["Pulmonary metastasis"]]);
allCodes.push(["C78.1","Secondary malignant neoplasm of mediastinum","C78",["Mediastinal metastasis"]]);
allCodes.push(["C78.2","Secondary malignant neoplasm of pleura","C78",["Pleural metastasis"]]);
allCodes.push(["C78.3","Secondary malignant neoplasm of other respiratory organs","C78",["Respiratory metastasis"]]);
allCodes.push(["C78.4","Secondary malignant neoplasm of small intestine","C78",["Small bowel metastasis"]]);
allCodes.push(["C78.5","Secondary malignant neoplasm of large intestine and rectum","C78",["Colorectal metastasis"]]);
allCodes.push(["C78.6","Secondary malignant neoplasm of retroperitoneum and peritoneum","C78",["Peritoneal metastasis"]]);
allCodes.push(["C78.7","Secondary malignant neoplasm of liver","C78",["Hepatic metastasis","Liver metastasis"]]);
allCodes.push(["C78.8","Secondary malignant neoplasm of other digestive organs","C78",["Digestive metastasis"]]);
allCodes.push(["C79.0","Secondary malignant neoplasm of kidney","C79",["Renal metastasis"]]);
allCodes.push(["C79.1","Secondary malignant neoplasm of bladder and other urinary organs","C79",["Urinary metastasis"]]);
allCodes.push(["C79.2","Secondary malignant neoplasm of skin","C79",["Cutaneous metastasis"]]);
allCodes.push(["C79.3","Secondary malignant neoplasm of brain and spinal cord","C79",["Brain metastasis"]]);
allCodes.push(["C79.4","Secondary malignant neoplasm of other parts of nervous system","C79",["CNS metastasis"]]);
allCodes.push(["C79.5","Secondary malignant neoplasm of bone and bone marrow","C79",["Bone metastasis"]]);
allCodes.push(["C79.6","Secondary malignant neoplasm of ovary","C79",["Ovarian metastasis"]]);
allCodes.push(["C79.7","Secondary malignant neoplasm of adrenal gland","C79",["Adrenal metastasis"]]);
allCodes.push(["C79.8","Secondary malignant neoplasm of other specified sites","C79",["Metastatic cancer NOS"]]);
allCodes.push(["C79.9","Secondary malignant neoplasm, unspecified site","C79",["Metastatic cancer NOS"]]);
allCodes.push(["C80.1","Malignant (primary) neoplasm, unspecified","C79",["Cancer of unknown primary","CUP"]]);
allCodes.push(["C80.2","Malignant neoplasm of uncertain behavior","C79",["Cancer of uncertain behavior"]]);
// Lymphoma/Leukemia C81-C96
allCodes.push(["C81.0","Nodular lymphocyte predominant Hodgkin lymphoma","C81",["NLPHL"]]);
allCodes.push(["C81.1","Hodgkin lymphoma, lymphocyte-rich","C81",["Lymphocyte-rich HL"]]);
allCodes.push(["C81.2","Hodgkin lymphoma, mixed cellularity","C81",["Mixed cellularity HL"]]);
allCodes.push(["C81.3","Hodgkin lymphoma, lymphocyte depletion","C81",["Lymphocyte-depleted HL"]]);
allCodes.push(["C81.4","Hodgkin lymphoma, nodular sclerosis","C81",["Nodular sclerosis HL"]]);
allCodes.push(["C81.9","Hodgkin lymphoma, unspecified","C81",["Hodgkin lymphoma NOS"]]);
allCodes.push(["C82.0","Follicular lymphoma, grade 1","C82",["Low-grade follicular lymphoma"]]);
allCodes.push(["C82.1","Follicular lymphoma, grade 2","C82",["Follicular lymphoma grade 2"]]);
allCodes.push(["C82.2","Follicular lymphoma, grade 3a","C82",["Follicular lymphoma grade 3a"]]);
allCodes.push(["C82.6","Follicular lymphoma, grade 3b","C82",["Follicular lymphoma grade 3b"]]);
allCodes.push(["C82.9","Follicular lymphoma, unspecified","C82",["Follicular lymphoma NOS"]]);
allCodes.push(["C83.0","Small lymphocytic lymphoma","C83",["SLL"]]);
allCodes.push(["C83.1","Mantle cell lymphoma","C83",["MCL"]]);
allCodes.push(["C83.2","Marginal zone lymphoma, MALT type","C83",["MALT lymphoma"]]);
allCodes.push(["C83.3","Diffuse large B-cell lymphoma","C83",["DLBCL"]]);
allCodes.push(["C83.4","Immunoblastic lymphoma","C83",["Immunoblastic lymphoma"]]);
allCodes.push(["C83.5","Lymphoblastic (diffuse) lymphoma","C83",["Lymphoblastic lymphoma"]]);
allCodes.push(["C83.7","Burkitt lymphoma","C83",["Burkitt lymphoma"]]);
allCodes.push(["C83.8","Other non-follicular lymphoma","C83",["Non-follicular lymphoma"]]);
allCodes.push(["C83.9","Non-follicular lymphoma, unspecified","C83",["NHL NOS"]]);
allCodes.push(["C84.0","Mycosis fungoides","C84",["Mycosis fungoides","Cutaneous T-cell lymphoma"]]);
allCodes.push(["C84.1","Sezary disease","C84",["Sezary syndrome"]]);
allCodes.push(["C84.4","Peripheral T-cell lymphoma, not elsewhere classified","C84",["PTCL"]]);
allCodes.push(["C84.6","Anaplastic large cell lymphoma","C84",["ALCL"]]);
allCodes.push(["C84.7","Anaplastic large cell lymphoma, ALK-positive","C84",["ALK-positive ALCL"]]);
allCodes.push(["C84.9","Mature T/NK-cell lymphoma, unspecified","C84",["T/NK-cell lymphoma NOS"]]);
allCodes.push(["C85.0","Lymphosarcoma","C85",["Lymphosarcoma"]]);
allCodes.push(["C85.1","B-cell lymphoma, unspecified","C85",["B-cell lymphoma NOS"]]);
allCodes.push(["C85.2","Mediastinal (thymic) large B-cell lymphoma","C85",["Mediastinal B-cell lymphoma"]]);
allCodes.push(["C85.9","Non-Hodgkin lymphoma, unspecified","C85",["NHL NOS"]]);
allCodes.push(["C88.0","Waldenstrom macroglobulinemia","C88",["WM","IgM lymphoplasmacytic lymphoma"]]);
allCodes.push(["C88.2","Heavy chain disease","C88",["Heavy chain disease"]]);
allCodes.push(["C88.4","Extranodal marginal zone lymphoma of MALT type","C84",["MALT lymphoma"]]);
allCodes.push(["C88.9","Malignant immunoproliferative disease, unspecified","C88",["Immunoproliferative disease NOS"]]);
allCodes.push(["C90.0","Multiple myeloma","C90",["Myeloma","MM"]]);
allCodes.push(["C90.1","Plasma cell leukemia","C90",["Plasma cell leukemia"]]);
allCodes.push(["C90.2","Extramedullary plasmacytoma","C90",["Plasmacytoma"]]);
allCodes.push(["C91.0","Acute lymphoblastic leukemia [ALL]","C91",["ALL"]]);
allCodes.push(["C91.1","Chronic lymphocytic leukemia [CLL]","C91",["CLL"]]);
allCodes.push(["C91.2","Prolymphocytic leukemia, B-cell type","C91",["B-PLL"]]);
allCodes.push(["C91.3","Prolymphocytic leukemia, T-cell type","C91",["T-PLL"]]);
allCodes.push(["C91.4","Hairy cell leukemia","C91",["HCL"]]);
allCodes.push(["C91.5","Adult T-cell lymphoma/leukemia (HTLV-1 associated)","C91",["ATLL"]]);
allCodes.push(["C91.6","Childhood lymphoblastic leukemia","C91",["Pediatric ALL"]]);
allCodes.push(["C91.8","Other lymphoid leukemia","C91",["Other lymphoid leukemia"]]);
allCodes.push(["C91.9","Lymphoid leukemia, unspecified","C91",["Leukemia NOS"]]);
allCodes.push(["C92.0","Acute myeloblastic leukemia [AML]","C92",["AML"]]);
allCodes.push(["C92.1","Chronic myelogenous leukemia [CML]","C92",["CML"]]);
allCodes.push(["C92.2","Acute promyelocytic leukemia","C92",["APL"]]);
allCodes.push(["C92.3","Myeloid sarcoma","C92",["Chloroma"]]);
allCodes.push(["C92.4","Acute promyelocytic leukemia, t(15;17)(q22;q21)","C92",["APL with PML-RARA"]]);
allCodes.push(["C92.5","Acute myelomonocytic leukemia","C92",["AMML"]]);
allCodes.push(["C92.6","Acute myeloid leukemia with t(6;9)(p23;q34)","C92",["AML with DEK-NUP214"]]);
allCodes.push(["C92.8","Other acute myeloid leukemia","C92",["Other AML"]]);
allCodes.push(["C92.9","Myeloid leukemia, unspecified","C92",["Myeloid leukemia NOS"]]);
allCodes.push(["C93.0","Chronic monomyelocytic leukemia","C93",["CMML"]]);
allCodes.push(["C93.1","Acute monocytic leukemia","C93",["AMoL"]]);
allCodes.push(["C93.9","Monocytic leukemia, unspecified","C93",["Monocytic leukemia NOS"]]);
allCodes.push(["C94.0","Acute erythroid leukemia","C94",["Erythroleukemia"]]);
allCodes.push(["C94.2","Acute megakaryoblastic leukemia","C94",["AMKL"]]);
allCodes.push(["C94.4","Acute panmyelosis with myelofibrosis","C94",["APMF"]]);
allCodes.push(["C94.7","Other specified leukemias","C94",["Other leukemias"]]);
allCodes.push(["C95.0","Acute leukemia of unspecified cell type","C95",["Acute leukemia NOS"]]);
allCodes.push(["C95.1","Chronic leukemia of unspecified cell type","C95",["Chronic leukemia NOS"]]);
allCodes.push(["C95.2","Subacute leukemia of unspecified cell type","C95",["Subacute leukemia NOS"]]);
allCodes.push(["C95.9","Leukemia, unspecified","C95",["Leukemia NOS"]]);
// Myelodysplastic C96
allCodes.push(["C96.0","Multifocal and multisystemic (disseminated) Langerhans-cell histiocytosis","C96",["LCH"]]);
allCodes.push(["C96.1","Malignant histiocytosis","C96",["Histiocytic sarcoma"]]);
allCodes.push(["C96.2","Mast cell sarcoma","C96",["Mast cell sarcoma"]]);
allCodes.push(["C96.4","True histiocytic lymphoma","C96",["Histiocytic lymphoma"]]);
allCodes.push(["C96.9","Malignant neoplasm of lymphoid, hematopoietic and related tissue, unspecified","C96",["Hematologic cancer NOS"]]);
// In situ D00-D09
allCodes.push(["D00.0","Carcinoma in situ of lip, oral cavity and pharynx","D00",["Oral cavity CIS"]]);
allCodes.push(["D00.1","Carcinoma in situ of esophagus","D00",["Esophageal CIS"]]);
allCodes.push(["D00.2","Carcinoma in situ of stomach","D00",["Gastric CIS"]]);
allCodes.push(["D01.0","Carcinoma in situ of colon","D01",["Colon CIS"]]);
allCodes.push(["D01.1","Carcinoma in situ of rectosigmoid junction and rectum","D01",["Rectal CIS"]]);
allCodes.push(["D01.2","Carcinoma in situ of anal canal","D01",["Anal CIS"]]);
allCodes.push(["D01.3","Carcinoma in situ of anus, unspecified","D01",["Anal CIS NOS"]]);
allCodes.push(["D01.4","Carcinoma in situ of other and unspecified parts of intestine","D01",["Intestinal CIS"]]);
allCodes.push(["D01.5","Carcinoma in situ of liver, gallbladder and bile ducts","D01",["Hepatobiliary CIS"]]);
allCodes.push(["D01.7","Carcinoma in situ of other specified digestive organs","D01",["Digestive CIS"]]);
allCodes.push(["D01.9","Carcinoma in situ of digestive organ, unspecified","D01",["Digestive CIS NOS"]]);
allCodes.push(["D02.0","Carcinoma in situ of larynx","D02",["Laryngeal CIS"]]);
allCodes.push(["D02.1","Carcinoma in situ of trachea","D02",["Tracheal CIS"]]);
allCodes.push(["D02.2","Carcinoma in situ of bronchus and lung","D02",["Pulmonary CIS"]]);
allCodes.push(["D02.3","Carcinoma in situ of other respiratory organs","D02",["Respiratory CIS"]]);
allCodes.push(["D02.4","Carcinoma in situ of respiratory organ, unspecified","D02",["Respiratory CIS NOS"]]);
allCodes.push(["D03.0","Melanoma in situ of lip","D03",["Lip melanoma in situ"]]);
allCodes.push(["D03.1","Melanoma in situ of eyelid","D03",["Eyelid melanoma in situ"]]);
allCodes.push(["D03.2","Melanoma in situ of ear","D03",["Ear melanoma in situ"]]);
allCodes.push(["D03.3","Melanoma in situ of face","D03",["Facial melanoma in situ"]]);
allCodes.push(["D03.4","Melanoma in situ of scalp and neck","D03",["Scalp melanoma in situ"]]);
allCodes.push(["D03.5","Melanoma in situ of trunk","D03",["Trunk melanoma in situ"]]);
allCodes.push(["D03.6","Melanoma in situ of upper limb","D03",["Upper limb melanoma in situ"]]);
allCodes.push(["D03.7","Melanoma in situ of lower limb","D03",["Lower limb melanoma in situ"]]);
allCodes.push(["D03.8","Melanoma in situ of other sites","D03",["Melanoma in situ"]]);
allCodes.push(["D03.9","Melanoma in situ, unspecified","D03",["Melanoma in situ NOS"]]);
allCodes.push(["D04.0","Carcinoma in situ of skin of lip","D04",["Lip skin CIS"]]);
allCodes.push(["D04.1","Carcinoma in situ of skin of eyelid","D04",["Eyelid CIS"]]);
allCodes.push(["D04.2","Carcinoma in situ of skin of ear","D04",["Ear CIS"]]);
allCodes.push(["D04.3","Carcinoma in situ of skin of other and unspecified parts of face","D04",["Facial CIS"]]);
allCodes.push(["D04.4","Carcinoma in situ of skin of scalp and neck","D04",["Scalp CIS"]]);
allCodes.push(["D04.5","Carcinoma in situ of skin of trunk","D04",["Trunk CIS"]]);
allCodes.push(["D04.6","Carcinoma in situ of skin of upper limb","D04",["Upper limb CIS"]]);
allCodes.push(["D04.7","Carcinoma in situ of skin of lower limb","D04",["Lower limb CIS"]]);
allCodes.push(["D04.9","Carcinoma in situ of skin, unspecified","D04",["Skin CIS NOS"]]);
allCodes.push(["D05.0","Carcinoma in situ of lobular carcinoma in situ of breast","D05",["LCIS"]]);
allCodes.push(["D05.1","Carcinoma in situ of other and unspecified ductal carcinoma in situ of breast","D05",["DCIS"]]);
allCodes.push(["D05.9","Carcinoma in situ of breast, unspecified","D05",["Breast CIS NOS"]]);
allCodes.push(["D06.0","Carcinoma in situ of endocervix","D06",["Endocervical CIS"]]);
allCodes.push(["D06.1","Carcinoma in situ of exocervix","D06",["Exocervical CIS"]]);
allCodes.push(["D06.7","Carcinoma in situ of other parts of cervix","D06",["Cervical CIS"]]);
allCodes.push(["D06.9","Carcinoma in situ of cervix, unspecified","D06",["Cervical CIS NOS"]]);
allCodes.push(["D07.0","Carcinoma in situ of endometrium","D07",["Endometrial CIS"]]);
allCodes.push(["D07.1","Carcinoma in situ of vulva","D07",["Vulvar CIS"]]);
allCodes.push(["D07.2","Carcinoma in situ of vagina","D07",["Vaginal CIS"]]);
allCodes.push(["D07.3","Carcinoma in situ of other and unspecified female genital organs","D07",["Female genital CIS"]]);
allCodes.push(["D07.4","Carcinoma in situ of penis","D07",["Penile CIS"]]);
allCodes.push(["D07.5","Carcinoma in situ of prostate","D07",["Prostatic CIS"]]);
allCodes.push(["D07.6","Carcinoma in situ of other and unspecified male genital organs","D07",["Male genital CIS"]]);
allCodes.push(["D09.0","Carcinoma in situ of bladder","D09",["Bladder CIS"]]);
allCodes.push(["D09.1","Carcinoma in situ of other and unspecified urinary organs","D09",["Urinary CIS"]]);
allCodes.push(["D09.2","Carcinoma in situ of eye","D09",["Ocular CIS"]]);
allCodes.push(["D09.3","Carcinoma in situ of thyroid and other endocrine glands","D09",["Endocrine CIS"]]);
allCodes.push(["D09.9","Carcinoma in situ, unspecified","D09",["CIS NOS"]]);
// Benign neoplasms D10-D36
allCodes.push(["D10.0","Benign neoplasm of lip","D10",["Lip tumor"]]);
allCodes.push(["D10.1","Benign neoplasm of tongue","D10",["Tongue tumor"]]);
allCodes.push(["D10.2","Benign neoplasm of floor of mouth","D10",["Floor of mouth tumor"]]);
allCodes.push(["D10.3","Benign neoplasm of other and unspecified parts of mouth","D10",["Oral cavity tumor"]]);
allCodes.push(["D10.4","Benign neoplasm of tonsil","D10",["Tonsillar tumor"]]);
allCodes.push(["D10.5","Benign neoplasm of oropharynx","D10",["Oropharyngeal tumor"]]);
allCodes.push(["D10.6","Benign neoplasm of nasopharynx","D10",["Nasopharyngeal tumor"]]);
allCodes.push(["D10.7","Benign neoplasm of hypopharynx","D10",["Hypopharyngeal tumor"]]);
allCodes.push(["D10.9","Benign neoplasm of pharynx, unspecified","D10",["Pharyngeal tumor NOS"]]);
allCodes.push(["D11.0","Benign neoplasm of parotid gland","D11",["Parotid tumor"]]);
allCodes.push(["D11.1","Benign neoplasm of submandibular gland","D11",["Submandibular tumor"]]);
allCodes.push(["D11.7","Benign neoplasm of other major salivary glands","D11",["Salivary gland tumor"]]);
allCodes.push(["D11.9","Benign neoplasm of major salivary gland, unspecified","D11",["Salivary gland tumor NOS"]]);
allCodes.push(["D12.0","Benign neoplasm of cecum","D12",["Cecal tumor"]]);
allCodes.push(["D12.1","Benign neoplasm of appendix","D12",["Appendiceal tumor"]]);
allCodes.push(["D12.2","Benign neoplasm of ascending colon","D12",["Ascending colon tumor"]]);
allCodes.push(["D12.3","Benign neoplasm of transverse colon","D12",["Transverse colon tumor"]]);
allCodes.push(["D12.4","Benign neoplasm of descending colon","D12",["Descending colon tumor"]]);
allCodes.push(["D12.5","Benign neoplasm of sigmoid colon","D12",["Sigmoid tumor"]]);
allCodes.push(["D12.6","Benign neoplasm of colon, unspecified","D12",["Colon polyp","Colon tumor NOS"]]);
allCodes.push(["D12.7","Benign neoplasm of rectosigmoid junction and rectum","D12",["Rectal polyp","Rectal tumor"]]);
allCodes.push(["D12.8","Benign neoplasm of anus and anal canal","D12",["Anal tumor"]]);
allCodes.push(["D12.9","Benign neoplasm of large intestine, part unspecified","D12",["Colorectal tumor"]]);
allCodes.push(["D13.0","Benign neoplasm of esophagus","D13",["Esophageal tumor"]]);
allCodes.push(["D13.1","Benign neoplasm of stomach","D13",["Gastric tumor"]]);
allCodes.push(["D13.2","Benign neoplasm of duodenum","D13",["Duodenal tumor"]]);
allCodes.push(["D13.3","Benign neoplasm of other and unspecified parts of small intestine","D13",["Small bowel tumor"]]);
allCodes.push(["D13.4","Benign neoplasm of liver","D13",["Hepatic tumor"]]);
allCodes.push(["D13.5","Benign neoplasm of extrahepatic bile ducts","D13",["Bile duct tumor"]]);
allCodes.push(["D13.6","Benign neoplasm of pancreas","D13",["Pancreatic tumor"]]);
allCodes.push(["D13.7","Benign neoplasm of endocrine pancreas","D13",["Islet cell tumor"]]);
allCodes.push(["D13.9","Benign neoplasm of ill-defined sites within the digestive system","D13",["Digestive tumor NOS"]]);
allCodes.push(["D14.0","Benign neoplasm of middle ear","D14",["Middle ear tumor"]]);
allCodes.push(["D14.1","Benign neoplasm of larynx","D14",["Laryngeal tumor"]]);
allCodes.push(["D14.2","Benign neoplasm of trachea","D14",["Tracheal tumor"]]);
allCodes.push(["D14.3","Benign neoplasm of bronchus and lung","D14",["Pulmonary tumor"]]);
allCodes.push(["D14.4","Benign neoplasm of respiratory organ, unspecified","D14",["Respiratory tumor NOS"]]);
allCodes.push(["D15.0","Benign neoplasm of thymus","D15",["Thymoma"]]);
allCodes.push(["D15.1","Benign neoplasm of heart","D15",["Cardiac tumor"]]);
allCodes.push(["D15.2","Benign neoplasm of mediastinum","D15",["Mediastinal tumor"]]);
allCodes.push(["D15.7","Benign neoplasm of other specified thoracic organs","D15",["Thoracic tumor"]]);
allCodes.push(["D15.9","Benign neoplasm of thoracic organ, unspecified","D15",["Thoracic tumor NOS"]]);
allCodes.push(["D16.0","Benign neoplasm of scapula and long bones of upper limb","D16",["Upper limb bone tumor"]]);
allCodes.push(["D16.1","Benign neoplasm of short bones of upper limb","D16",["Hand bone tumor"]]);
allCodes.push(["D16.2","Benign neoplasm of long bones of lower limb","D16",["Lower limb bone tumor"]]);
allCodes.push(["D16.3","Benign neoplasm of short bones of lower limb","D16",["Foot bone tumor"]]);
allCodes.push(["D16.4","Benign neoplasm of bones of skull and face","D16",["Skull tumor"]]);
allCodes.push(["D16.5","Benign neoplasm of mandible","D16",["Jaw tumor"]]);
allCodes.push(["D16.6","Benign neoplasm of vertebral column","D16",["Spinal tumor"]]);
allCodes.push(["D16.7","Benign neoplasm of ribs, sternum and clavicle","D16",["Chest wall tumor"]]);
allCodes.push(["D16.8","Benign neoplasm of pelvic bones, sacrum and coccyx","D16",["Pelvic bone tumor"]]);
allCodes.push(["D16.9","Benign neoplasm of bone and articular cartilage, unspecified","D16",["Bone tumor NOS"]]);
allCodes.push(["D17.0","Benign lipomatous neoplasm of skin and subcutaneous tissue of face","D17",["Facial lipoma"]]);
allCodes.push(["D17.1","Benign lipomatous neoplasm of skin and subcutaneous tissue of neck","D17",["Neck lipoma"]]);
allCodes.push(["D17.2","Benign lipomatous neoplasm of skin and subcutaneous tissue of trunk","D17",["Trunk lipoma"]]);
allCodes.push(["D17.3","Benign lipomatous neoplasm of skin and subcutaneous tissue of upper limb","D17",["Upper limb lipoma"]]);
allCodes.push(["D17.4","Benign lipomatous neoplasm of skin and subcutaneous tissue of lower limb","D17",["Lower limb lipoma"]]);
allCodes.push(["D17.5","Benign lipomatous neoplasm of skin and subcutaneous tissue of genitourinary organ","D17",["Genitourinary lipoma"]]);
allCodes.push(["D17.7","Benign lipomatous neoplasm of skin and subcutaneous tissue of other sites","D17",["Lipoma NOS"]]);
allCodes.push(["D17.9","Benign lipomatous neoplasm of skin and subcutaneous tissue, unspecified","D17",["Lipoma NOS"]]);
allCodes.push(["D18.0","Hemangioma, any site","D18",["Hemangioma"]]);
allCodes.push(["D18.1","Lymphangioma, any site","D18",["Lymphangioma"]]);
allCodes.push(["D19.0","Benign mesothelioma of pleura","D19",["Benign pleural mesothelioma"]]);
allCodes.push(["D19.1","Benign mesothelioma of peritoneum","D19",["Benign peritoneal mesothelioma"]]);
allCodes.push(["D19.7","Benign mesothelioma of other sites","D19",["Benign mesothelioma"]]);
allCodes.push(["D19.9","Benign mesothelioma, unspecified","D19",["Benign mesothelioma NOS"]]);
allCodes.push(["D20.0","Benign neoplasm of soft tissue of retroperitoneum","D20",["Retroperitoneal tumor"]]);
allCodes.push(["D20.1","Benign neoplasm of soft tissue of mediastinum","D20",["Mediastinal soft tissue tumor"]]);
allCodes.push(["D21.0","Benign neoplasm of connective and other soft tissue of head, face and neck","D21",["Head soft tissue tumor"]]);
allCodes.push(["D21.1","Benign neoplasm of connective and other soft tissue of upper limb","D21",["Upper limb soft tissue tumor"]]);
allCodes.push(["D21.2","Benign neoplasm of connective and other soft tissue of lower limb","D21",["Lower limb soft tissue tumor"]]);
allCodes.push(["D21.3","Benign neoplasm of connective and other soft tissue of thorax","D21",["Thoracic soft tissue tumor"]]);
allCodes.push(["D21.4","Benign neoplasm of connective and other soft tissue of abdomen","D21",["Abdominal soft tissue tumor"]]);
allCodes.push(["D21.5","Benign neoplasm of connective and other soft tissue of pelvis","D21",["Pelvic soft tissue tumor"]]);
allCodes.push(["D21.6","Benign neoplasm of connective and other soft tissue of trunk, unspecified","D21",["Trunk soft tissue tumor"]]);
allCodes.push(["D21.9","Benign neoplasm of connective and other soft tissue, unspecified","D21",["Soft tissue tumor NOS"]]);
allCodes.push(["D22.0","Melanocytic nevi of lip","D22",["Lip nevus"]]);
allCodes.push(["D22.1","Melanocytic nevi of eyelid","D22",["Eyelid nevus"]]);
allCodes.push(["D22.2","Melanocytic nevi of ear","D22",["Ear nevus"]]);
allCodes.push(["D22.3","Melanocytic nevi of other and unspecified parts of face","D22",["Facial nevus"]]);
allCodes.push(["D22.4","Melanocytic nevi of scalp and neck","D22",["Scalp nevus"]]);
allCodes.push(["D22.5","Melanocytic nevi of trunk","D22",["Trunk nevus"]]);
allCodes.push(["D22.6","Melanocytic nevi of upper limb","D22",["Upper limb nevus"]]);
allCodes.push(["D22.7","Melanocytic nevi of lower limb","D22",["Lower limb nevus"]]);
allCodes.push(["D22.9","Melanocytic nevi, unspecified","D22",["Nevus NOS","Mole"]]);
allCodes.push(["D23.0","Benign neoplasm of skin of lip","D23",["Lip skin tumor"]]);
allCodes.push(["D23.1","Benign neoplasm of skin of eyelid","D23",["Eyelid skin tumor"]]);
allCodes.push(["D23.2","Benign neoplasm of skin of ear","D23",["Ear skin tumor"]]);
allCodes.push(["D23.3","Benign neoplasm of skin of other and unspecified parts of face","D23",["Facial skin tumor"]]);
allCodes.push(["D23.4","Benign neoplasm of skin of scalp and neck","D23",["Scalp skin tumor"]]);
allCodes.push(["D23.5","Benign neoplasm of skin of trunk","D23",["Trunk skin tumor"]]);
allCodes.push(["D23.6","Benign neoplasm of skin of upper limb","D23",["Upper limb skin tumor"]]);
allCodes.push(["D23.7","Benign neoplasm of skin of lower limb","D23",["Lower limb skin tumor"]]);
allCodes.push(["D23.9","Benign neoplasm of skin, unspecified","D23",["Skin tumor NOS"]]);
allCodes.push(["D24","Benign neoplasm of breast","D24",["Breast fibroadenoma","Breast lump"]]);
allCodes.push(["D25.0","Submucous leiomyoma of uterus","D25",["Submucous fibroid"]]);
allCodes.push(["D25.1","Intramural leiomyoma of uterus","D25",["Intramural fibroid"]]);
allCodes.push(["D25.2","Subserosal leiomyoma of uterus","D25",["Subserosal fibroid"]]);
allCodes.push(["D25.9","Leiomyoma of uterus, unspecified","D25",["Uterine fibroid"]]);
allCodes.push(["D26.0","Benign neoplasm of cervix uteri","D26",["Cervical polyp"]]);
allCodes.push(["D26.1","Benign neoplasm of corpus uteri","D26",["Uterine corpus tumor"]]);
allCodes.push(["D26.7","Benign neoplasm of other parts of uterus","D26",["Uterine tumor"]]);
allCodes.push(["D26.9","Benign neoplasm of uterus, unspecified","D26",["Uterine tumor NOS"]]);
allCodes.push(["D27","Benign neoplasm of ovary","D27",["Ovarian cyst","Ovarian tumor"]]);
allCodes.push(["D28.0","Benign neoplasm of vulva","D28",["Vulvar tumor"]]);
allCodes.push(["D28.1","Benign neoplasm of vagina","D28",["Vaginal tumor"]]);
allCodes.push(["D28.2","Benign neoplasm of fallopian tube","D28",["Fallopian tube tumor"]]);
allCodes.push(["D28.7","Benign neoplasm of other specified female genital organs","D28",["Female genital tumor"]]);
allCodes.push(["D28.9","Benign neoplasm of female genital organ, unspecified","D28",["Female genital tumor NOS"]]);
allCodes.push(["D29.0","Benign neoplasm of prostate","D29",["Prostatic BPH"]]);
allCodes.push(["D29.1","Benign neoplasm of testis","D29",["Testicular tumor"]]);
allCodes.push(["D29.2","Benign neoplasm of epididymis","D29",["Epididymal cyst"]]);
allCodes.push(["D29.3","Benign neoplasm of spermatic cord","D29",["Spermatic cord tumor"]]);
allCodes.push(["D29.4","Benign neoplasm of penis","D29",["Penile tumor"]]);
allCodes.push(["D29.9","Benign neoplasm of male genital organ, unspecified","D29",["Male genital tumor NOS"]]);
allCodes.push(["D30.0","Benign neoplasm of kidney","D30",["Renal cyst","Kidney tumor"]]);
allCodes.push(["D30.1","Benign neoplasm of renal pelvis","D30",["Renal pelvis tumor"]]);
allCodes.push(["D30.2","Benign neoplasm of ureter","D30",["Ureteral tumor"]]);
allCodes.push(["D30.3","Benign neoplasm of bladder","D30",["Bladder tumor","Bladder polyp"]]);
allCodes.push(["D30.4","Benign neoplasm of urethra","D30",["Urethral tumor"]]);
allCodes.push(["D30.9","Benign neoplasm of urinary organ, unspecified","D30",["Urinary tumor NOS"]]);
allCodes.push(["D31.0","Benign neoplasm of conjunctiva","D31",["Conjunctival tumor"]]);
allCodes.push(["D31.1","Benign neoplasm of cornea","D31",["Corneal tumor"]]);
allCodes.push(["D31.2","Benign neoplasm of retina","D31",["Retinal tumor"]]);
allCodes.push(["D31.3","Benign neoplasm of choroid","D31",["Choroidal tumor"]]);
allCodes.push(["D31.4","Benign neoplasm of ciliary body","D31",["Ciliary body tumor"]]);
allCodes.push(["D31.5","Benign neoplasm of lacrimal gland and duct","D31",["Lacrimal gland tumor"]]);
allCodes.push(["D31.6","Benign neoplasm of orbit, unspecified","D31",["Orbital tumor"]]);
allCodes.push(["D31.9","Benign neoplasm of eye, unspecified","D31",["Eye tumor NOS"]]);
allCodes.push(["D32.0","Benign neoplasm of meninges of cerebral hemispheres","D32",["Meningioma"]]);
allCodes.push(["D32.1","Benign neoplasm of meninges of spinal cord","D32",["Spinal meningioma"]]);
allCodes.push(["D32.9","Benign neoplasm of meninges, unspecified","D32",["Meningioma NOS"]]);
allCodes.push(["D33.0","Benign neoplasm of brain, supratentorial","D33",["Supratentorial brain tumor"]]);
allCodes.push(["D33.1","Benign neoplasm of brain, infratentorial","D33",["Infratentorial brain tumor"]]);
allCodes.push(["D33.2","Benign neoplasm of brain, unspecified","D33",["Brain tumor NOS"]]);
allCodes.push(["D33.3","Benign neoplasm of cranial nerves","D33",["Cranial nerve tumor"]]);
allCodes.push(["D33.4","Benign neoplasm of brain, ventricles","D33",["Ventricular tumor"]]);
allCodes.push(["D33.7","Benign neoplasm of other parts of central nervous system","D33",["CNS tumor"]]);
allCodes.push(["D33.9","Benign neoplasm of central nervous system, unspecified","D33",["CNS tumor NOS"]]);
allCodes.push(["D34","Benign neoplasm of thyroid gland","D34",["Thyroid nodule","Thyroid adenoma"]]);
allCodes.push(["D35.0","Benign neoplasm of adrenal gland","D35",["Adrenal adenoma"]]);
allCodes.push(["D35.1","Benign neoplasm of parathyroid gland","D35",["Parathyroid adenoma"]]);
allCodes.push(["D35.2","Benign neoplasm of pituitary gland","D35",["Pituitary adenoma"]]);
allCodes.push(["D35.3","Benign neoplasm of craniopharyngeal duct","D35",["Craniopharyngioma"]]);
allCodes.push(["D35.4","Benign neoplasm of pineal gland","D35",["Pineal cyst"]]);
allCodes.push(["D35.5","Benign neoplasm of carotid body","D35",["Carotid body tumor"]]);
allCodes.push(["D35.6","Benign neoplasm of aortic body and other paraganglia","D35",["Paraganglioma"]]);
allCodes.push(["D35.7","Benign neoplasm of other specified endocrine glands","D35",["Endocrine tumor"]]);
allCodes.push(["D35.9","Benign neoplasm of endocrine gland, unspecified","D35",["Endocrine tumor NOS"]]);
allCodes.push(["D36.0","Benign neoplasm of lymph nodes","D36",["Lymph node tumor"]]);
allCodes.push(["D36.1","Benign neoplasm of peripheral nerves and autonomic nervous system","D36",["Nerve sheath tumor"]]);
allCodes.push(["D36.7","Benign neoplasm of other specified sites","D36",["Benign tumor"]]);
allCodes.push(["D36.9","Benign neoplasm of unspecified site","D36",["Benign tumor NOS"]]);
// Neoplasms of uncertain behavior D37-D48
allCodes.push(["D37.0","Neoplasm of uncertain behavior of lip, oral cavity and pharynx","D37",["Oral cavity uncertain tumor"]]);
allCodes.push(["D37.1","Neoplasm of uncertain behavior of stomach","D37",["Gastric uncertain tumor"]]);
allCodes.push(["D37.2","Neoplasm of uncertain behavior of small intestine","D37",["Small bowel uncertain tumor"]]);
allCodes.push(["D37.3","Neoplasm of uncertain behavior of appendix","D37",["Appendiceal uncertain tumor"]]);
allCodes.push(["D37.4","Neoplasm of uncertain behavior of colon","D37",["Colon uncertain tumor"]]);
allCodes.push(["D37.5","Neoplasm of uncertain behavior of rectum, rectosigmoid junction and anus","D37",["Rectal uncertain tumor"]]);
allCodes.push(["D37.6","Neoplasm of uncertain behavior of liver, gallbladder and bile ducts","D37",["Hepatobiliary uncertain tumor"]]);
allCodes.push(["D37.7","Neoplasm of uncertain behavior of other digestive organs","D37",["Digestive uncertain tumor"]]);
allCodes.push(["D37.8","Neoplasm of uncertain behavior of digestive organ, unspecified","D37",["Digestive uncertain tumor NOS"]]);
allCodes.push(["D37.9","Neoplasm of uncertain behavior of digestive organ, unspecified","D37",["Digestive uncertain tumor NOS"]]);
allCodes.push(["D38.0","Neoplasm of uncertain behavior of larynx","D38",["Laryngeal uncertain tumor"]]);
allCodes.push(["D38.1","Neoplasm of uncertain behavior of trachea, bronchus and lung","D38",["Pulmonary uncertain tumor"]]);
allCodes.push(["D38.2","Neoplasm of uncertain behavior of pleura","D38",["Pleural uncertain tumor"]]);
allCodes.push(["D38.3","Neoplasm of uncertain behavior of mediastinum","D38",["Mediastinal uncertain tumor"]]);
allCodes.push(["D38.4","Neoplasm of uncertain behavior of thymus","D38",["Thymic uncertain tumor"]]);
allCodes.push(["D38.5","Neoplasm of uncertain behavior of other respiratory organs","D38",["Respiratory uncertain tumor"]]);
allCodes.push(["D38.6","Neoplasm of uncertain behavior of respiratory organ, unspecified","D38",["Respiratory uncertain tumor NOS"]]);
allCodes.push(["D39.0","Neoplasm of uncertain behavior of uterus","D39",["Uterine uncertain tumor"]]);
allCodes.push(["D39.1","Neoplasm of uncertain behavior of ovary","D39",["Ovarian uncertain tumor"]]);
allCodes.push(["D39.2","Neoplasm of uncertain behavior of placenta","D39",["Placental uncertain tumor"]]);
allCodes.push(["D39.7","Neoplasm of uncertain behavior of other specified female genital organs","D39",["Female genital uncertain tumor"]]);
allCodes.push(["D39.9","Neoplasm of uncertain behavior of female genital organ, unspecified","D39",["Female genital uncertain tumor NOS"]]);
allCodes.push(["D40.0","Neoplasm of uncertain behavior of prostate","D40",["Prostatic uncertain tumor"]]);
allCodes.push(["D40.1","Neoplasm of uncertain behavior of testis","D40",["Testicular uncertain tumor"]]);
allCodes.push(["D40.7","Neoplasm of uncertain behavior of other specified male genital organs","D40",["Male genital uncertain tumor"]]);
allCodes.push(["D40.9","Neoplasm of uncertain behavior of male genital organ, unspecified","D40",["Male genital uncertain tumor NOS"]]);
allCodes.push(["D41.0","Neoplasm of uncertain behavior of kidney","D41",["Renal uncertain tumor"]]);
allCodes.push(["D41.1","Neoplasm of uncertain behavior of renal pelvis","D41",["Renal pelvis uncertain tumor"]]);
allCodes.push(["D41.2","Neoplasm of uncertain behavior of ureter","D41",["Ureteral uncertain tumor"]]);
allCodes.push(["D41.3","Neoplasm of uncertain behavior of bladder","D41",["Bladder uncertain tumor"]]);
allCodes.push(["D41.4","Neoplasm of uncertain behavior of urethra","D41",["Urethral uncertain tumor"]]);
allCodes.push(["D41.7","Neoplasm of uncertain behavior of other urinary organs","D41",["Urinary uncertain tumor"]]);
allCodes.push(["D41.9","Neoplasm of uncertain behavior of urinary organ, unspecified","D41",["Urinary uncertain tumor NOS"]]);
allCodes.push(["D42.0","Neoplasm of uncertain behavior of meninges of cerebral hemispheres","D42",["Meningeal uncertain tumor"]]);
allCodes.push(["D42.1","Neoplasm of uncertain behavior of meninges of spinal cord","D42",["Spinal meningeal uncertain tumor"]]);
allCodes.push(["D42.9","Neoplasm of uncertain behavior of meninges, unspecified","D42",["Meningeal uncertain tumor NOS"]]);
allCodes.push(["D43.0","Neoplasm of uncertain behavior of brain, supratentorial","D43",["Supratentorial uncertain brain tumor"]]);
allCodes.push(["D43.1","Neoplasm of uncertain behavior of brain, infratentorial","D43",["Infratentorial uncertain brain tumor"]]);
allCodes.push(["D43.2","Neoplasm of uncertain behavior of brain, unspecified","D43",["Brain uncertain tumor NOS"]]);
allCodes.push(["D43.3","Neoplasm of uncertain behavior of cranial nerves","D43",["Cranial nerve uncertain tumor"]]);
allCodes.push(["D43.4","Neoplasm of uncertain behavior of brain, ventricles","D43",["Ventricular uncertain tumor"]]);
allCodes.push(["D43.7","Neoplasm of uncertain behavior of other parts of central nervous system","D43",["CNS uncertain tumor"]]);
allCodes.push(["D43.9","Neoplasm of uncertain behavior of central nervous system, unspecified","D43",["CNS uncertain tumor NOS"]]);
allCodes.push(["D44.0","Neoplasm of uncertain behavior of thyroid gland","D44",["Thyroid uncertain tumor"]]);
allCodes.push(["D44.1","Neoplasm of uncertain behavior of adrenal gland","D44",["Adrenal uncertain tumor"]]);
allCodes.push(["D44.2","Neoplasm of uncertain behavior of pituitary gland","D44",["Pituitary uncertain tumor"]]);
allCodes.push(["D44.3","Neoplasm of uncertain behavior of pineal gland","D44",["Pineal uncertain tumor"]]);
allCodes.push(["D44.4","Neoplasm of uncertain behavior of endocrine pancreas","D44",["Pancreatic endocrine uncertain tumor"]]);
allCodes.push(["D44.7","Neoplasm of uncertain behavior of other specified endocrine glands","D44",["Endocrine uncertain tumor"]]);
allCodes.push(["D44.9","Neoplasm of uncertain behavior of endocrine gland, unspecified","D44",["Endocrine uncertain tumor NOS"]]);
allCodes.push(["D45","Polycythemia vera","D45",["PV","Polycythemia"]]);
allCodes.push(["D46.0","Refractory anemia without sideroblasts","D46",["RA"]]);
allCodes.push(["D46.1","Refractory anemia with sideroblasts","D46",["RARS"]]);
allCodes.push(["D46.2","Refractory anemia with excess blasts","D46",["RAEB"]]);
allCodes.push(["D46.3","Refractory anemia with excess blasts in transformation","D46",["RAEB-T"]]);
allCodes.push(["D46.4","Refractory cytopenia with multilineage dysplasia","D46",["RCMD"]]);
allCodes.push(["D46.5","Refractory cytopenia with multilineage dysplasia and ringed sideroblasts","D46",["RCMD-RS"]]);
allCodes.push(["D46.6","Myelodysplastic syndrome with isolated del(5q)","D46",["5q- syndrome"]]);
allCodes.push(["D46.7","Other myelodysplastic syndromes","D46",["MDS NOS"]]);
allCodes.push(["D46.9","Myelodysplastic syndrome, unspecified","D46",["MDS NOS"]]);
allCodes.push(["D47.0","Histiocytic and mast cell tumors of uncertain behavior","D47",["Mast cell tumor"]]);
allCodes.push(["D47.1","Chronic myeloproliferative disease","D47",["CMPD"]]);
allCodes.push(["D47.2","Monoclonal gammopathy of undetermined significance [MGUS]","D47",["MGUS"]]);
allCodes.push(["D47.3","Essential (hemorrhagic) thrombocythemia","D47",["Essential thrombocythemia","ET"]]);
allCodes.push(["D47.4","Osteomyelofibrosis","D47",["Myelofibrosis","MF"]]);
allCodes.push(["D47.5","Chronic myelomonocytic leukemia [CMML]","D47",["CMML"]]);
allCodes.push(["D47.8","Other specified neoplasms of uncertain behavior of lymphoid, hematopoietic and related tissue","D47",["Hematologic uncertain tumor"]]);
allCodes.push(["D47.9","Neoplasm of uncertain behavior of lymphoid, hematopoietic and related tissue, unspecified","D47",["Hematologic uncertain tumor NOS"]]);
allCodes.push(["D48.0","Neoplasm of uncertain behavior of bone and articular cartilage","D48",["Bone uncertain tumor"]]);
allCodes.push(["D48.1","Neoplasm of uncertain behavior of connective and other soft tissue","D48",["Soft tissue uncertain tumor"]]);
allCodes.push(["D48.2","Neoplasm of uncertain behavior of peripheral nerves and autonomic nervous system","D48",["Nerve uncertain tumor"]]);
allCodes.push(["D48.3","Neoplasm of uncertain behavior of retroperitoneum","D48",["Retroperitoneal uncertain tumor"]]);
allCodes.push(["D48.4","Neoplasm of uncertain behavior of peritoneum","D48",["Peritoneal uncertain tumor"]]);
allCodes.push(["D48.5","Neoplasm of uncertain behavior of skin","D48",["Skin uncertain tumor"]]);
allCodes.push(["D48.6","Neoplasm of uncertain behavior of breast","D48",["Breast uncertain tumor"]]);
allCodes.push(["D48.7","Neoplasm of uncertain behavior of other specified sites","D48",["Uncertain tumor"]]);
allCodes.push(["D48.9","Neoplasm of uncertain behavior, unspecified","D48",["Uncertain tumor NOS"]]);
// D49
allCodes.push(["D49.0","Neoplasm of unspecified behavior of digestive organs","D49",["Digestive neoplasm UNS"]]);
allCodes.push(["D49.1","Neoplasm of unspecified behavior of respiratory organs","D49",["Respiratory neoplasm UNS"]]);
allCodes.push(["D49.2","Neoplasm of unspecified behavior of bone, soft tissue, and skin","D49",["Bone/soft tissue neoplasm UNS"]]);
allCodes.push(["D49.3","Neoplasm of unspecified behavior of breast","D49",["Breast neoplasm UNS"]]);
allCodes.push(["D49.4","Neoplasm of unspecified behavior of genitourinary organs","D49",["Genitourinary neoplasm UNS"]]);
allCodes.push(["D49.5","Neoplasm of unspecified behavior of other endocrine glands","D49",["Endocrine neoplasm UNS"]]);
allCodes.push(["D49.6","Neoplasm of unspecified behavior of eye, brain and other parts of central nervous system","D49",["CNS neoplasm UNS"]]);
allCodes.push(["D49.7","Neoplasm of unspecified behavior of lymphoid, hematopoietic and related tissue","D49",["Hematologic neoplasm UNS"]]);
allCodes.push(["D49.8","Neoplasm of unspecified behavior of other specified sites","D49",["Neoplasm UNS"]]);
allCodes.push(["D49.9","Neoplasm of unspecified behavior, unspecified site","D49",["Neoplasm UNS NOS"]]);

console.log('Generated ' + allCodes.length + ' Chapter II entries');

// Now write out each code
var codeLines = [];
for (var i = 0; i < allCodes.length; i++) {
  var c = allCodes[i];
  var cu = c[3] || [];
  var s = '  codes["' + c[0] + '"] = { code: "' + c[0] + '", description: "' + c[1].replace(/"/g, '\\"') + '", category: "' + c[2] + '", excludes1: [], excludes2: [], includes: [], commonUse: [' + cu.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '], documentation: [] };';
  codeLines.push(s);
}

fs.writeFileSync(path.join(__dirname, 'part_ch2.txt'), codeLines.join('\n'), 'utf8');
console.log('Wrote part_ch2.txt');
