var fs = require('fs');
var path = require('path');
var lines = [];

var allCodes = [];

// ========== CHAPTER III: BLOOD (D50-D89) ==========
allCodes.push(["D50.0","Iron deficiency anemia secondary to blood loss (chronic)","D50",["Anemia of chronic blood loss"]]);
allCodes.push(["D50.1","Iron deficiency anemia secondary to inadequate iron intake","D50",["Dietary iron deficiency anemia"]]);
allCodes.push(["D50.8","Other iron deficiency anemias","D50",["Iron deficiency anemia"]]);
allCodes.push(["D50.9","Iron deficiency anemia, unspecified","D50",["Iron deficiency anemia NOS"]]);
allCodes.push(["D51.0","Vitamin B12 deficiency anemia due to intrinsic factor deficiency","D51",["Pernicious anemia"]]);
allCodes.push(["D51.1","Vitamin B12 deficiency anemia due to selective vitamin B12 malabsorption","D51",["B12 malabsorption"]]);
allCodes.push(["D51.2","Vitamin B12 deficiency anemia due to dietary vitamin B12 deficiency","D51",["Dietary B12 deficiency"]]);
allCodes.push(["D51.3","Other dietary vitamin B12 deficiency anemia","D51",["B12 deficiency anemia"]]);
allCodes.push(["D51.8","Other vitamin B12 deficiency anemias","D51",["B12 deficiency anemia"]]);
allCodes.push(["D51.9","Vitamin B12 deficiency anemia, unspecified","D51",["B12 deficiency anemia NOS"]]);
allCodes.push(["D52.0","Folate deficiency anemia due to inadequate folate intake","D52",["Dietary folate deficiency anemia"]]);
allCodes.push(["D52.1","Folate deficiency anemia due to malabsorption","D52",["Folate malabsorption"]]);
allCodes.push(["D52.8","Other folate deficiency anemias","D52",["Folate deficiency anemia"]]);
allCodes.push(["D52.9","Folate deficiency anemia, unspecified","D52",["Folate deficiency anemia NOS"]]);
allCodes.push(["D53.0","Anemia due to protein deficiency","D53",["Protein deficiency anemia"]]);
allCodes.push(["D53.1","Megaloblastic anemia, not elsewhere classified","D53",["Megaloblastic anemia NOS"]]);
allCodes.push(["D53.2","Anemia due to disorders of nucleotide metabolism","D53",["Nucleotide metabolism anemia"]]);
allCodes.push(["D53.8","Other specified nutritional anemias","D53",["Nutritional anemia"]]);
allCodes.push(["D53.9","Nutritional anemia, unspecified","D53",["Nutritional anemia NOS"]]);
allCodes.push(["D55.0","Anemia due to glucose-6-phosphate dehydrogenase deficiency","D55",["G6PD deficiency anemia"]]);
allCodes.push(["D55.1","Anemia due to other disorders of glutathione metabolism","D55",["Glutathione metabolism anemia"]]);
allCodes.push(["D55.2","Anemia due to disorders of glycolytic enzymes","D55",["Glycolytic enzyme anemia"]]);
allCodes.push(["D55.8","Other anemias due to enzyme disorders","D55",["Enzyme disorder anemia"]]);
allCodes.push(["D55.9","Anemia due to enzyme disorder, unspecified","D55",["Enzyme disorder anemia NOS"]]);
allCodes.push(["D56.0","Thalassemia minor","D56",["Beta thalassemia trait","Alpha thalassemia trait"]]);
allCodes.push(["D56.1","Beta thalassemia major","D56",["Cooley anemia","Thalassemia major"]]);
allCodes.push(["D56.2","Beta thalassemia intermedia","D56",["Thalassemia intermedia"]]);
allCodes.push(["D56.3","Sickle cell-hemoglobin C disease","D56",["HbSC disease"]]);
allCodes.push(["D56.4","Hereditary persistence of fetal hemoglobin","D56",["HPFH"]]);
allCodes.push(["D56.8","Other thalassemias","D56",["Other thalassemia"]]);
allCodes.push(["D56.9","Thalassemia, unspecified","D56",["Thalassemia NOS"]]);
allCodes.push(["D57.0","Sickle-cell anemia with crisis","D57",["Sickle cell crisis","Vaso-occlusive crisis"]]);
allCodes.push(["D57.1","Sickle-cell anemia without crisis","D57",["Sickle cell disease"]]);
allCodes.push(["D57.2","Sickle-cell/Hb-C disease","D57",["Sickle-HbC disease"]]);
allCodes.push(["D57.3","Sickle-cell trait","D57",["Sickle cell trait","HbAS"]]);
allCodes.push(["D57.8","Other sickle-cell disorders","D57",["Other sickle cell disorders"]]);
allCodes.push(["D58.0","Hereditary spherocytosis","D58",["Spherocytosis"]]);
allCodes.push(["D58.1","Hereditary elliptocytosis","D58",["Elliptocytosis"]]);
allCodes.push(["D58.2","Hemoglobin E disease","D58",["HbE disease"]]);
allCodes.push(["D58.8","Other hereditary hemolytic anemias","D58",["Hereditary hemolytic anemia"]]);
allCodes.push(["D58.9","Hereditary hemolytic anemia, unspecified","D58",["Hereditary hemolytic anemia NOS"]]);
allCodes.push(["D59.0","Drug-induced autoimmune hemolytic anemia","D59",["Drug-induced hemolytic anemia"]]);
allCodes.push(["D59.1","Other autoimmune hemolytic anemias","D59",["Autoimmune hemolytic anemia","AIHA"]]);
allCodes.push(["D59.2","Drug-induced non-autoimmune hemolytic anemia","D59",["Drug-induced hemolytic anemia"]]);
allCodes.push(["D59.3","Hemolytic-uremic syndrome","D59",["HUS"]]);
allCodes.push(["D59.4","Other non-autoimmune hemolytic anemias","D59",["Non-autoimmune hemolytic anemia"]]);
allCodes.push(["D59.5","Paroxysmal nocturnal hemoglobinuria [Marchiafava-Micheli]","D59",["PNH"]]);
allCodes.push(["D59.6","Hemolysis due to exogenous agents","D59",["Exogenous hemolysis"]]);
allCodes.push(["D59.8","Other acquired hemolytic anemias","D59",["Acquired hemolytic anemia"]]);
allCodes.push(["D59.9","Acquired hemolytic anemia, unspecified","D59",["Acquired hemolytic anemia NOS"]]);
allCodes.push(["D60.0","Acute aplastic anemia","D61",["Acute aplastic anemia"]]);
allCodes.push(["D60.1","Chronic aplastic anemia","D61",["Chronic aplastic anemia"]]);
allCodes.push(["D60.2","Aplastic anemia, unspecified","D61",["Aplastic anemia NOS"]]);
allCodes.push(["D60.8","Other aplastic anemias","D61",["Aplastic anemia"]]);
allCodes.push(["D60.9","Aplastic anemia, unspecified","D61",["Aplastic anemia NOS"]]);
allCodes.push(["D61.3","Idiopathic aplastic anemia","D61",["Idiopathic aplastic anemia"]]);
allCodes.push(["D61.8","Other specified aplastic anemias","D61",["Aplastic anemia"]]);
allCodes.push(["D61.9","Aplastic anemia, unspecified","D61",["Aplastic anemia NOS"]]);
allCodes.push(["D62","Acute posthemorrhagic anemia","D62",["Acute blood loss anemia","Posthemorrhagic anemia"]]);
allCodes.push(["D63.0","Anemia in neoplastic disease","D63",["Anemia of malignancy"]]);
allCodes.push(["D63.1","Anemia in chronic kidney disease","D63",["Anemia of CKD","Renal anemia"]]);
allCodes.push(["D63.2","Anemia of endocrine disorder","D63",["Endocrine anemia"]]);
allCodes.push(["D63.8","Anemia in other chronic diseases","D63",["Anemia of chronic disease","ACD"]]);
allCodes.push(["D63.9","Anemia in chronic disease, unspecified","D63",["Anemia of chronic disease NOS"]]);
allCodes.push(["D64.0","Hereditary sideroblastic anemia","D64",["Sideroblastic anemia"]]);
allCodes.push(["D64.1","Secondary sideroblastic anemia","D64",["Acquired sideroblastic anemia"]]);
allCodes.push(["D64.2","Sideroblastic anemia due to other drugs and toxins","D64",["Drug-induced sideroblastic anemia"]]);
allCodes.push(["D64.3","Other sideroblastic anemias","D64",["Sideroblastic anemia"]]);
allCodes.push(["D64.4","Dyserythropoietic anemia","D64",["Dyserythropoietic anemia"]]);
allCodes.push(["D64.8","Other specified anemias","D64",["Other anemias"]]);
allCodes.push(["D64.9","Anemia, unspecified","D64",["Anemia NOS"]]);
allCodes.push(["D65","Disseminated intravascular coagulation [defibrination syndrome]","D65",["DIC"]]);
allCodes.push(["D66","Hereditary factor VIII deficiency","D66",["Hemophilia A"]]);
allCodes.push(["D67","Hereditary factor IX deficiency","D67",["Hemophilia B","Christmas disease"]]);
allCodes.push(["D68.0","Von Willebrand disease","D68",["vWD"]]);
allCodes.push(["D68.1","Hereditary factor XI deficiency","D68",["Hemophilia C"]]);
allCodes.push(["D68.2","Hereditary deficiency of other clotting factors","D68",["Clotting factor deficiency"]]);
allCodes.push(["D68.3","Hemorrhagic disorder due to circulating anticoagulants","D68",["Acquired coagulopathy"]]);
allCodes.push(["D68.4","Acquired coagulation factor deficiency","D68",["Acquired coagulopathy"]]);
allCodes.push(["D68.5","Thrombophilia due to antiphospholipid antibodies","D68",["APL syndrome","Antiphospholipid syndrome"]]);
allCodes.push(["D68.6","Other thrombophilia","D68",["Thrombophilia"]]);
allCodes.push(["D68.8","Other specified coagulation defects","D68",["Coagulation defect"]]);
allCodes.push(["D68.9","Coagulation defect, unspecified","D68",["Coagulation defect NOS"]]);
allCodes.push(["D69.0","Allergic purpura","D69",["Henoch-Schonlein purpura","IgA vasculitis"]]);
allCodes.push(["D69.1","Qualitative platelet defects","D69",["Platelet function defect"]]);
allCodes.push(["D69.2","Other nonthrombocytopenic purpura","D69",["Purpura"]]);
allCodes.push(["D69.3","Idiopathic thrombocytopenic purpura","D69",["ITP","Immune thrombocytopenia"]]);
allCodes.push(["D69.4","Other primary thrombocytopenia","D69",["Thrombocytopenia"]]);
allCodes.push(["D69.5","Secondary thrombocytopenia","D69",["Secondary thrombocytopenia"]]);
allCodes.push(["D69.6","Thrombocytopenia, unspecified","D69",["Thrombocytopenia NOS"]]);
allCodes.push(["D69.8","Other specified hemorrhagic conditions","D69",["Hemorrhagic condition"]]);
allCodes.push(["D69.9","Hemorrhagic condition, unspecified","D69",["Hemorrhagic condition NOS"]]);
allCodes.push(["D70.0","Agranulocytosis","D70",["Agranulocytosis","Neutropenia"]]);
allCodes.push(["D70.1","Agranulocytosis due to infection","D70",["Infection-related neutropenia"]]);
allCodes.push(["D70.2","Cyclic neutropenia","D70",["Cyclic neutropenia"]]);
allCodes.push(["D70.3","Neutropenia due to chemotherapy","D70",["Chemotherapy-induced neutropenia"]]);
allCodes.push(["D70.4","Neutropenia due to drugs","D70",["Drug-induced neutropenia"]]);
allCodes.push(["D70.8","Other neutropenias","D70",["Neutropenia"]]);
allCodes.push(["D70.9","Neutropenia, unspecified","D70",["Neutropenia NOS"]]);
allCodes.push(["D71.0","Chronic granulomatous disease","D72",["CGD"]]);
allCodes.push(["D71.1","Leukocyte adhesion deficiency","D72",["LAD"]]);
allCodes.push(["D71.2","Other functional disorders of polymorphonuclear neutrophils","D72",["Neutrophil function defect"]]);
allCodes.push(["D71.3","Other specified disorders of white blood cells","D72",["White blood cell disorder"]]);
allCodes.push(["D71.9","Disorder of white blood cells, unspecified","D72",["White blood cell disorder NOS"]]);
allCodes.push(["D72.8","Other specified disorders of white blood cells","D72",["White blood cell disorder"]]);
allCodes.push(["D72.9","Disorder of white blood cells, unspecified","D72",["White blood cell disorder NOS"]]);
allCodes.push(["D73.0","Hypersplenism","D73",["Hypersplenism"]]);
allCodes.push(["D73.1","Hypersplenism, unspecified","D73",["Hypersplenism NOS"]]);
allCodes.push(["D73.2","Chronic congestive splenomegaly","D73",["Congestive splenomegaly"]]);
allCodes.push(["D73.3","Abscess of spleen","D73",["Splenic abscess"]]);
allCodes.push(["D73.4","Cyst of spleen","D73",["Splenic cyst"]]);
allCodes.push(["D73.5","Infarction of spleen","D73",["Splenic infarction"]]);
allCodes.push(["D73.8","Other diseases of spleen","D73",["Spleen disease"]]);
allCodes.push(["D73.9","Disease of spleen, unspecified","D73",["Spleen disease NOS"]]);
allCodes.push(["D75.0","Familial erythrocytosis","D75",["Familial polycythemia"]]);
allCodes.push(["D75.1","Secondary polycythemia","D75",["Secondary polycythemia"]]);
allCodes.push(["D75.2","Essential thrombocytosis","D75",["Essential thrombocytosis"]]);
allCodes.push(["D75.8","Other specified diseases of blood and blood-forming organs","D75",["Blood disorder"]]);
allCodes.push(["D75.9","Disease of blood and blood-forming organs, unspecified","D75",["Blood disorder NOS"]]);
allCodes.push(["D80.0","Hypogammaglobulinemia due to deficiency of secretory component","D80",["Secretory IgA deficiency"]]);
allCodes.push(["D80.1","Nonfamilial hypogammaglobulinemia","D80",["Common variable immunodeficiency","CVID"]]);
allCodes.push(["D80.2","Selective deficiency of immunoglobulin A [IgA]","D80",["IgA deficiency"]]);
allCodes.push(["D80.3","Selective deficiency of immunoglobulin G [IgG] subclasses","D80",["IgG subclass deficiency"]]);
allCodes.push(["D80.4","Selective deficiency of immunoglobulin M [IgM]","D80",["IgM deficiency"]]);
allCodes.push(["D80.5","Immunodeficiency with increased immunoglobulin M [IgM]","D80",["Hyper IgM syndrome"]]);
allCodes.push(["D80.6","Antibody deficiency with near-normal immunoglobulins or with hyperimmunoglobulinemia","D80",["Antibody deficiency"]]);
allCodes.push(["D80.7","Transient hypogammaglobulinemia of infancy","D80",["Transient hypogammaglobulinemia"]]);
allCodes.push(["D80.8","Other specified immunodeficiencies with predominant antibody defect","D80",["Antibody defect"]]);
allCodes.push(["D80.9","Immunodeficiency with predominant antibody defect, unspecified","D80",["Antibody defect NOS"]]);
allCodes.push(["D81.0","Severe combined immunodeficiency [SCID] with reticular dysgenesis","D81",["SCID - reticular dysgenesis"]]);
allCodes.push(["D81.1","Severe combined immunodeficiency [SCID] with adenosine deaminase deficiency","D81",["SCID - ADA deficiency"]]);
allCodes.push(["D81.2","Severe combined immunodeficiency [SCID] due to purine nucleoside phosphorylase deficiency","D81",["SCID - PNP deficiency"]]);
allCodes.push(["D81.3","Adenosine deaminase [ADA] deficiency","D81",["ADA deficiency"]]);
allCodes.push(["D81.4","Nezelof syndrome","D81",["Nezelof syndrome"]]);
allCodes.push(["D81.5","Purine nucleoside phosphorylase [PNP] deficiency","D81",["PNP deficiency"]]);
allCodes.push(["D81.6","Major histocompatibility complex class I deficiency","D81",["MHC class I deficiency"]]);
allCodes.push(["D81.7","Major histocompatibility complex class II deficiency","D81",["MHC class II deficiency"]]);
allCodes.push(["D81.8","Other combined immunodeficiencies","D81",["Combined immunodeficiency"]]);
allCodes.push(["D81.9","Combined immunodeficiency, unspecified","D81",["Combined immunodeficiency NOS"]]);
allCodes.push(["D82.0","Wiskott-Aldrich syndrome","D82",["WAS"]]);
allCodes.push(["D82.1","Di George syndrome","D82",["22q11.2 deletion syndrome","Velocardiofacial syndrome"]]);
allCodes.push(["D82.2","Ataxia-telangiectasia [Louis-Bar syndrome]","D82",["AT","Ataxia-telangiectasia"]]);
allCodes.push(["D82.3","Immunodeficiency due to defective extrinsic (Th1) pathway","D82",["Th1 pathway defect"]]);
allCodes.push(["D82.4","Hyper IgE syndrome","D82",["Job syndrome"]]);
allCodes.push(["D82.8","Immunodeficiency associated with other specified major defects","D82",["Immunodeficiency with major defect"]]);
allCodes.push(["D82.9","Immunodeficiency associated with major defect, unspecified","D82",["Immunodeficiency with major defect NOS"]]);
allCodes.push(["D83.0","Common variable immunodeficiency with predominant abnormalities of B-cell numbers and function","D83",["CVID with B-cell abnormality"]]);
allCodes.push(["D83.1","Common variable immunodeficiency with predominant immunoglobulin abnormalities","D83",["CVID with Ig abnormality"]]);
allCodes.push(["D83.2","Common variable immunodeficiency with autoantibodies to B or T cells","D83",["CVID with autoantibodies"]]);
allCodes.push(["D83.8","Other common variable immunodeficiencies","D83",["CVID"]]);
allCodes.push(["D83.9","Common variable immunodeficiency, unspecified","D83",["CVID NOS"]]);
allCodes.push(["D84.0","Immunodeficiency due to lymphocyte adhesion molecule defect","D84",["Lymphocyte adhesion defect"]]);
allCodes.push(["D84.1","Defects in the complement system","D84",["Complement deficiency"]]);
allCodes.push(["D84.2","Other specified immunodeficiencies","D84",["Other immunodeficiency"]]);
allCodes.push(["D84.8","Other specified immunodeficiencies","D84",["Other immunodeficiency"]]);
allCodes.push(["D84.9","Immunodeficiency, unspecified","D84",["Immunodeficiency NOS"]]);
allCodes.push(["D86.0","Sarcoidosis of lung","D86",["Pulmonary sarcoidosis","Sarcoidosis"]]);
allCodes.push(["D86.1","Sarcoidosis of lymph nodes","D86",["Lymph node sarcoidosis"]]);
allCodes.push(["D86.2","Sarcoidosis of lung with sarcoidosis of lymph nodes","D86",["Pulmonary and lymph node sarcoidosis"]]);
allCodes.push(["D86.3","Sarcoidosis of spleen","D86",["Splenic sarcoidosis"]]);
allCodes.push(["D86.8","Sarcoidosis of other sites","D86",["Sarcoidosis - other site"]]);
allCodes.push(["D86.9","Sarcoidosis, unspecified","D86",["Sarcoidosis NOS"]]);
allCodes.push(["D89.0","Polyclonal hypergammaglobulinemia","D89",["Polyclonal hypergammaglobulinemia"]]);
allCodes.push(["D89.1","Monoclonal gammopathy of undetermined significance (MGUS)","D89",["MGUS"]]);
allCodes.push(["D89.2","Monoclonal gammopathy, unspecified","D89",["Monoclonal gammopathy NOS"]]);
allCodes.push(["D89.3","Polyclonal hypergammaglobulinemia, unspecified","D89",["Polyclonal hypergammaglobulinemia NOS"]]);
allCodes.push(["D89.4","Autoimmune lymphoproliferative syndrome [ALPS]","D89",["ALPS"]]);
allCodes.push(["D89.5","Other specified hypergammaglobulinemia","D89",["Hypergammaglobulinemia"]]);
allCodes.push(["D89.6","Combined immunodeficiency, unspecified","D89",["Combined immunodeficiency NOS"]]);
allCodes.push(["D89.8","Other specified disorders involving the immune mechanism","D89",["Immune disorder"]]);
allCodes.push(["D89.9","Disorder involving the immune mechanism, unspecified","D89",["Immune disorder NOS"]]);

// ========== CHAPTER IV: ENDOCRINE/METABOLIC (E00-E89) ==========
allCodes.push(["E00.0","Congenital iodine-deficiency syndrome with myxedematous cretinism","E00",["Cretinism with hypothyroidism"]]);
allCodes.push(["E00.1","Congenital iodine-deficiency syndrome with neurological features","E00",["Cretinism - neurological"]]);
allCodes.push(["E00.2","Congenital iodine-deficiency syndrome with mixed features","E00",["Cretinism - mixed"]]);
allCodes.push(["E00.9","Congenital iodine-deficiency syndrome, unspecified","E00",["Congenital iodine deficiency NOS"]]);
allCodes.push(["E01.0","Iodine-deficiency-related diffuse goiter (endemic goiter)","E01",["Endemic goiter"]]);
allCodes.push(["E01.1","Iodine-deficiency-related multinodular goiter (endemic goiter)","E01",["Endemic multinodular goiter"]]);
allCodes.push(["E01.2","Iodine-deficiency-related goiter, unspecified","E01",["Iodine-deficiency goiter NOS"]]);
allCodes.push(["E01.8","Iodine-deficiency-related hypothyroidism and allied conditions","E01",["Iodine-deficiency hypothyroidism"]]);
allCodes.push(["E02","Subclinical iodine-deficiency hypothyroidism","E02",["Subclinical hypothyroidism from iodine deficiency"]]);
allCodes.push(["E03.0","Congenital hypothyroidism with diffuse goiter","E03",["Congenital hypothyroidism with goiter"]]);
allCodes.push(["E03.1","Congenital hypothyroidism without goiter","E03",["Congenital hypothyroidism NOS"]]);
allCodes.push(["E03.2","Hypothyroidism due to medicaments and other exogenous substances","E03",["Drug-induced hypothyroidism"]]);
allCodes.push(["E03.3","Postinfectious hypothyroidism","E03",["Post thyroiditis hypothyroidism"]]);
allCodes.push(["E03.4","Atrophy of thyroid (acquired)","E03",["Thyroid atrophy"]]);
allCodes.push(["E03.5","Other hypothyroidism","E03",["Hypothyroidism"]]);
allCodes.push(["E03.8","Other specified hypothyroidism","E03",["Other hypothyroidism"]]);
allCodes.push(["E03.9","Hypothyroidism, unspecified","E03",["Hypothyroidism NOS","Underactive thyroid"]]);
allCodes.push(["E04.0","Nontoxic diffuse goiter","E04",["Simple goiter","Diffuse goiter"]]);
allCodes.push(["E04.1","Nontoxic single thyroid nodule","E04",["Thyroid nodule"]]);
allCodes.push(["E04.2","Nontoxic multinodular goiter","E04",["Multinodular goiter","MNG"]]);
allCodes.push(["E04.3","Transient nontoxic goiter","E04",["Transient goiter"]]);
allCodes.push(["E04.8","Other specified nontoxic goiter","E04",["Nontoxic goiter"]]);
allCodes.push(["E04.9","Nontoxic goiter, unspecified","E04",["Goiter NOS"]]);
allCodes.push(["E05.0","Thyrotoxicosis with diffuse goiter","E05",["Graves disease","Diffuse toxic goiter"]]);
allCodes.push(["E05.1","Thyrotoxicosis with toxic single thyroid nodule","E05",["Toxic thyroid nodule","Toxic adenoma"]]);
allCodes.push(["E05.2","Thyrotoxicosis with toxic multinodular goiter","E05",["Toxic multinodular goiter","Plummer disease"]]);
allCodes.push(["E05.3","Thyrotoxicosis from ectopic thyroid tissue","E05",["Ectopic hyperthyroidism"]]);
allCodes.push(["E05.4","Thyrotoxicosis factitia","E05",["Thyrotoxicosis factitia"]]);
allCodes.push(["E05.5","Thyroid crisis or storm","E05",["Thyroid storm"]]);
allCodes.push(["E05.8","Other thyrotoxicosis","E05",["Hyperthyroidism"]]);
allCodes.push(["E05.9","Thyrotoxicosis, unspecified","E05",["Hyperthyroidism NOS"]]);
allCodes.push(["E06.0","Acute thyroiditis","E06",["Acute thyroiditis","Subacute thyroiditis"]]);
allCodes.push(["E06.1","Subacute thyroiditis","E06",["De Quervain thyroiditis"]]);
allCodes.push(["E06.2","Chronic thyroiditis with transient thyrotoxicosis","E06",["Hashitoxicosis"]]);
allCodes.push(["E06.3","Autoimmune thyroiditis","E06",["Hashimoto thyroiditis"]]);
allCodes.push(["E06.4","Drug-induced thyroiditis","E06",["Drug-induced thyroiditis"]]);
allCodes.push(["E06.5","Other chronic thyroiditis","E06",["Chronic thyroiditis"]]);
allCodes.push(["E06.9","Thyroiditis, unspecified","E06",["Thyroiditis NOS"]]);
allCodes.push(["E07.0","Hyperthyroidism of thyroid follicular cell origin","E07",["Hyperthyroidism"]]);
allCodes.push(["E07.1","Hashitoxicosis","E07",["Hashitoxicosis"]]);
allCodes.push(["E07.8","Other disorders of thyroid","E07",["Thyroid disorder"]]);
allCodes.push(["E07.9","Disorder of thyroid, unspecified","E07",["Thyroid disorder NOS"]]);
allCodes.push(["E10.0","Type 1 diabetes mellitus with hyperosmolarity","E10",["DKA with hyperosmolarity"]]);
allCodes.push(["E10.1","Type 1 diabetes mellitus with ketoacidosis","E10",["DKA","Diabetic ketoacidosis"]]);
allCodes.push(["E10.2","Type 1 diabetes mellitus with kidney complications","E10",["T1DM with nephropathy"]]);
allCodes.push(["E10.3","Type 1 diabetes mellitus with ophthalmic complications","E10",["T1DM with retinopathy"]]);
allCodes.push(["E10.4","Type 1 diabetes mellitus with neurological complications","E10",["T1DM with neuropathy"]]);
allCodes.push(["E10.5","Type 1 diabetes mellitus with peripheral circulatory complications","E10",["T1DM with PVD"]]);
allCodes.push(["E10.6","Type 1 diabetes mellitus with other specified complications","E10",["T1DM with other complication"]]);
allCodes.push(["E10.7","Type 1 diabetes mellitus with multiple complications","E10",["T1DM with multiple complications"]]);
allCodes.push(["E10.8","Type 1 diabetes mellitus with unspecified complications","E10",["T1DM with unspecified complication"]]);
allCodes.push(["E10.9","Type 1 diabetes mellitus without complications","E10",["Type 1 diabetes","T1DM"]]);
allCodes.push(["E11.0","Type 2 diabetes mellitus with hyperosmolarity","E11",["T2DM with hyperosmolarity"]]);
allCodes.push(["E11.1","Type 2 diabetes mellitus with ketoacidosis","E11",["T2DM with ketoacidosis"]]);
allCodes.push(["E11.2","Type 2 diabetes mellitus with kidney complications","E11",["T2DM with nephropathy","Diabetic nephropathy"]]);
allCodes.push(["E11.3","Type 2 diabetes mellitus with ophthalmic complications","E11",["T2DM with retinopathy","Diabetic retinopathy"]]);
allCodes.push(["E11.4","Type 2 diabetes mellitus with neurological complications","E11",["T2DM with neuropathy","Diabetic neuropathy"]]);
allCodes.push(["E11.5","Type 2 diabetes mellitus with peripheral circulatory complications","E11",["T2DM with PVD","Diabetic PVD"]]);
allCodes.push(["E11.6","Type 2 diabetes mellitus with other specified complications","E11",["T2DM with other complication"]]);
allCodes.push(["E11.7","Type 2 diabetes mellitus with multiple complications","E11",["T2DM with multiple complications"]]);
allCodes.push(["E11.8","Type 2 diabetes mellitus with unspecified complications","E11",["T2DM with unspecified complication"]]);
allCodes.push(["E11.9","Type 2 diabetes mellitus without complications","E11",["Type 2 diabetes","T2DM","Diabetes mellitus"]]);
allCodes.push(["E13.0","Other specified diabetes mellitus with hyperosmolarity","E13",["Other diabetes with hyperosmolarity"]]);
allCodes.push(["E13.1","Other specified diabetes mellitus with ketoacidosis","E13",["Other diabetes with ketoacidosis"]]);
allCodes.push(["E13.2","Other specified diabetes mellitus with kidney complications","E13",["Other diabetes with nephropathy"]]);
allCodes.push(["E13.3","Other specified diabetes mellitus with ophthalmic complications","E13",["Other diabetes with retinopathy"]]);
allCodes.push(["E13.4","Other specified diabetes mellitus with neurological complications","E13",["Other diabetes with neuropathy"]]);
allCodes.push(["E13.9","Other specified diabetes mellitus without complications","E13",["Other specified diabetes NOS"]]);
allCodes.push(["E15","Nonspecific hypoglycemia","E15",["Hypoglycemia NOS"]]);
allCodes.push(["E16.0","Drug-induced hypoglycemia without coma","E16",["Drug-induced hypoglycemia"]]);
allCodes.push(["E16.1","Other hypoglycemia","E16",["Hypoglycemia"]]);
allCodes.push(["E16.2","Hypoglycemia, unspecified","E16",["Hypoglycemia NOS"]]);
allCodes.push(["E16.3","Increased secretion of glucagon","E16",["Glucagon excess"]]);
allCodes.push(["E16.4","Increased secretion of gastrin","E16",["Zollinger-Ellison syndrome"]]);
allCodes.push(["E16.8","Other specified disorders of pancreatic internal secretion","E16",["Pancreatic endocrine disorder"]]);
allCodes.push(["E16.9","Disorder of pancreatic internal secretion, unspecified","E16",["Pancreatic endocrine disorder NOS"]]);
allCodes.push(["E20.0","Idiopathic hypoparathyroidism","E20",["Hypoparathyroidism NOS"]]);
allCodes.push(["E20.1","Pseudohypoparathyroidism","E20",["Pseudohypoparathyroidism"]]);
allCodes.push(["E20.8","Other hypoparathyroidism","E20",["Hypoparathyroidism"]]);
allCodes.push(["E20.9","Hypoparathyroidism, unspecified","E20",["Hypoparathyroidism NOS"]]);
allCodes.push(["E21.0","Primary hyperparathyroidism","E21",["Hyperparathyroidism"]]);
allCodes.push(["E21.1","Secondary hyperparathyroidism, not elsewhere classified","E21",["Secondary hyperparathyroidism"]]);
allCodes.push(["E21.2","Other hyperparathyroidism","E21",["Hyperparathyroidism"]]);
allCodes.push(["E21.3","Hyperparathyroidism, unspecified","E21",["Hyperparathyroidism NOS"]]);
allCodes.push(["E21.4","Other specified disorders of parathyroid gland","E21",["Parathyroid disorder"]]);
allCodes.push(["E21.5","Disorder of parathyroid gland, unspecified","E21",["Parathyroid disorder NOS"]]);
allCodes.push(["E22.0","Acromegaly and pituitary gigantism","E22",["Acromegaly","Gigantism"]]);
allCodes.push(["E22.1","Hyperprolactinemia","E22",["Prolactinoma"]]);
allCodes.push(["E22.2","Syndrome of inappropriate secretion of antidiuretic hormone","E22",["SIADH"]]);
allCodes.push(["E22.8","Other hyperfunction of pituitary gland","E22",["Pituitary hyperfunction"]]);
allCodes.push(["E22.9","Hyperfunction of pituitary gland, unspecified","E22",["Pituitary hyperfunction NOS"]]);
allCodes.push(["E23.0","Hypopituitarism","E23",["Pituitary insufficiency","Hypopituitarism"]]);
allCodes.push(["E23.1","Drug-induced hypopituitarism","E23",["Drug-induced hypopituitarism"]]);
allCodes.push(["E23.2","Diabetes insipidus","E23",["Diabetes insipidus","DI"]]);
allCodes.push(["E23.3","Cranio-pharyngioma","E23",["Craniopharyngioma"]]);
allCodes.push(["E23.6","Other disorders of pituitary gland","E23",["Pituitary disorder"]]);
allCodes.push(["E23.7","Disorder of pituitary gland, unspecified","E23",["Pituitary disorder NOS"]]);
allCodes.push(["E24.0","Pituitary-dependent Cushing disease","E24",["Cushing disease"]]);
allCodes.push(["E24.1","Ectopic ACTH syndrome","E24",["Ectopic Cushing syndrome"]]);
allCodes.push(["E24.2","Drug-induced Cushing syndrome","E24",["Iatrogenic Cushing syndrome"]]);
allCodes.push(["E24.3","Ectopic ACTH syndrome","E24",["Ectopic ACTH"]]);
allCodes.push(["E24.4","Cushing syndrome, unspecified","E24",["Cushing syndrome NOS"]]);
allCodes.push(["E24.8","Other Cushing syndromes","E24",["Cushing syndrome"]]);
allCodes.push(["E24.9","Cushing syndrome, unspecified","E24",["Cushing syndrome NOS"]]);
allCodes.push(["E25.0","Adrenogenital disorders associated with enzyme deficiency","E25",["Congenital adrenal hyperplasia","CAH"]]);
allCodes.push(["E25.8","Other adrenogenital disorders","E25",["Adrenogenital disorder"]]);
allCodes.push(["E25.9","Adrenogenital disorder, unspecified","E25",["Adrenogenital disorder NOS"]]);
allCodes.push(["E26.0","Primary hyperaldosteronism","E27",["Conn syndrome"]]);
allCodes.push(["E26.1","Secondary hyperaldosteronism","E27",["Secondary hyperaldosteronism"]]);
allCodes.push(["E26.9","Hyperaldosteronism, unspecified","E27",["Hyperaldosteronism NOS"]]);
allCodes.push(["E27.0","Adrenal crisis","E27",["Addisonian crisis","Adrenal crisis"]]);
allCodes.push(["E27.1","Primary adrenocortical insufficiency","E27",["Addison disease"]]);
allCodes.push(["E27.2","Addisonian crisis","E27",["Addisonian crisis"]]);
allCodes.push(["E27.3","Adrenocortical insufficiency, unspecified","E27",["Adrenal insufficiency NOS"]]);
allCodes.push(["E27.4","Other and unspecified adrenocortical insufficiency","E27",["Adrenal insufficiency"]]);
allCodes.push(["E27.5","Adrenal medulla chromaffin neoplasm","E27",["Pheochromocytoma"]]);
allCodes.push(["E27.8","Other specified disorders of adrenal gland","E27",["Adrenal disorder"]]);
allCodes.push(["E27.9","Disorder of adrenal gland, unspecified","E27",["Adrenal disorder NOS"]]);
allCodes.push(["E28.0","Ovarian hyperfunction","E28",["Ovarian hyperfunction"]]);
allCodes.push(["E28.1","Polycystic ovarian syndrome","E28",["PCOS","PCOD"]]);
allCodes.push(["E28.2","Premature ovarian failure","E28",["POF","Premature menopause"]]);
allCodes.push(["E28.3","Primary ovarian insufficiency","E28",["Primary ovarian insufficiency"]]);
allCodes.push(["E28.8","Other ovarian dysfunction","E28",["Ovarian dysfunction"]]);
allCodes.push(["E28.9","Ovarian dysfunction, unspecified","E28",["Ovarian dysfunction NOS"]]);
allCodes.push(["E29.0","Testicular hyperfunction","E29",["Testicular hyperfunction"]]);
allCodes.push(["E29.1","Testicular hypofunction","E29",["Hypogonadism","Low testosterone"]]);
allCodes.push(["E29.8","Other testicular dysfunction","E29",["Testicular dysfunction"]]);
allCodes.push(["E29.9","Testicular dysfunction, unspecified","E29",["Testicular dysfunction NOS"]]);
allCodes.push(["E31.0","Autoimmune polyglandular dysfunction","E31",["APS type I","APS type II"]]);
allCodes.push(["E31.1","Polyglandular hyperfunction","E31",["Polyglandular hyperfunction"]]);
allCodes.push(["E31.2","Polyglandular dysfunction, unspecified","E31",["Polyglandular dysfunction NOS"]]);
allCodes.push(["E31.8","Other specified polyglandular dysfunction","E31",["Polyglandular dysfunction"]]);
allCodes.push(["E31.9","Polyglandular dysfunction, unspecified","E31",["Polyglandular dysfunction NOS"]]);
// Malnutrition
allCodes.push(["E40","Kwashiorkor","E40",["Protein malnutrition"]]);
allCodes.push(["E41","Nutritional marasmus","E41",["Marasmus"]]);
allCodes.push(["E43","Unspecified severe protein-energy malnutrition","E43",["Severe malnutrition"]]);
allCodes.push(["E44.0","Moderate protein-energy malnutrition","E44",["Moderate malnutrition"]]);
allCodes.push(["E44.1","Mild protein-energy malnutrition","E44",["Mild malnutrition"]]);
allCodes.push(["E46","Unspecified protein-energy malnutrition","E46",["Malnutrition NOS"]]);
// Vitamin deficiencies
allCodes.push(["E50.0","Vitamin A deficiency with conjunctival xerosis","E50",["Vitamin A deficiency - ocular"]]);
allCodes.push(["E50.1","Vitamin A deficiency with Bitot spot and corneal xerosis","E50",["Bitot spot"]]);
allCodes.push(["E50.2","Vitamin A deficiency with corneal ulceration and xerosis","E50",["Vitamin A corneal ulcer"]]);
allCodes.push(["E50.3","Vitamin A deficiency with keratomalacia","E50",["Keratomalacia"]]);
allCodes.push(["E50.4","Vitamin A deficiency with xerophthalmia","E50",["Xerophthalmia"]]);
allCodes.push(["E50.5","Vitamin A deficiency with night blindness","E50",["Night blindness"]]);
allCodes.push(["E50.6","Vitamin A deficiency with xerosis of conjunctiva","E50",["Conjunctival xerosis"]]);
allCodes.push(["E50.7","Other ocular manifestations of vitamin A deficiency","E50",["Vitamin A deficiency - eye"]]);
allCodes.push(["E50.8","Other manifestations of vitamin A deficiency","E50",["Vitamin A deficiency"]]);
allCodes.push(["E50.9","Vitamin A deficiency, unspecified","E50",["Vitamin A deficiency NOS"]]);
allCodes.push(["E51.1","Beriberi","E51",["Beriberi","Thiamine deficiency"]]);
allCodes.push(["E51.2","Wernicke encephalopathy","E51",["Wernicke-Korsakoff syndrome"]]);
allCodes.push(["E51.8","Other manifestations of thiamine deficiency","E51",["Thiamine deficiency"]]);
allCodes.push(["E51.9","Thiamine deficiency, unspecified","E51",["Thiamine deficiency NOS"]]);
allCodes.push(["E52","Niacin deficiency [pellagra]","E52",["Pellagra"]]);
allCodes.push(["E53.0","Deficiency of vitamin B12","E53",["Vitamin B12 deficiency"]]);
allCodes.push(["E53.1","Deficiency of pyridoxine","E53",["Vitamin B6 deficiency"]]);
allCodes.push(["E53.8","Deficiency of other B group vitamins","E53",["B vitamin deficiency"]]);
allCodes.push(["E53.9","Vitamin B deficiency, unspecified","E53",["B vitamin deficiency NOS"]]);
allCodes.push(["E54","Ascorbic acid deficiency","E54",["Scurvy","Vitamin C deficiency"]]);
allCodes.push(["E55.0","Rickets, active","E55",["Rickets"]]);
allCodes.push(["E55.9","Vitamin D deficiency, unspecified","E55",["Vitamin D deficiency NOS","Low vitamin D"]]);
allCodes.push(["E56.0","Deficiency of vitamin E","E56",["Vitamin E deficiency"]]);
allCodes.push(["E56.1","Deficiency of vitamin K","E56",["Vitamin K deficiency"]]);
allCodes.push(["E56.8","Deficiency of other vitamins","E56",["Vitamin deficiency"]]);
allCodes.push(["E56.9","Vitamin deficiency, unspecified","E56",["Vitamin deficiency NOS"]]);
allCodes.push(["E61.0","Deficiency of copper","E61",["Copper deficiency"]]);
allCodes.push(["E61.1","Deficiency of iron","E61",["Iron deficiency"]]);
allCodes.push(["E61.2","Deficiency of magnesium","E61",["Magnesium deficiency"]]);
allCodes.push(["E61.3","Deficiency of manganese","E61",["Manganese deficiency"]]);
allCodes.push(["E61.4","Deficiency of chromium","E61",["Chromium deficiency"]]);
allCodes.push(["E61.5","Deficiency of molybdenum","E61",["Molybdenum deficiency"]]);
allCodes.push(["E61.6","Deficiency of zinc","E61",["Zinc deficiency"]]);
allCodes.push(["E61.7","Deficiency of multiple nutrient elements","E61",["Multiple nutrient deficiency"]]);
allCodes.push(["E61.8","Deficiency of other nutrient elements","E61",["Nutrient element deficiency"]]);
allCodes.push(["E61.9","Deficiency of nutrient element, unspecified","E61",["Nutrient element deficiency NOS"]]);
allCodes.push(["E63.0","Deficiency of essential fatty acids [EFA]","E63",["EFA deficiency"]]);
allCodes.push(["E63.1","Imbalance of constituents of food intake","E61",["Dietary imbalance"]]);
allCodes.push(["E63.8","Other specified nutritional deficiencies","E61",["Nutritional deficiency"]]);
allCodes.push(["E63.9","Nutritional deficiency, unspecified","E61",["Nutritional deficiency NOS"]]);
allCodes.push(["E65","Localized adiposity","E65",["Localized fat deposit"]]);
allCodes.push(["E66.0","Morbid (severe) obesity due to excess calories","E66",["Morbid obesity","Severe obesity"]]);
allCodes.push(["E66.1","Drug-induced obesity","E66",["Drug-induced obesity"]]);
allCodes.push(["E66.2","Morbid (severe) obesity with alveolar hypoventilation","E66",["Pickwickian syndrome","Obesity hypoventilation"]]);
allCodes.push(["E66.8","Other obesity","E66",["Obesity"]]);
allCodes.push(["E66.9","Obesity, unspecified","E66",["Obesity NOS","Overweight"]]);
allCodes.push(["E67.0","Hypervitaminosis A","E67",["Hypervitaminosis A"]]);
allCodes.push(["E67.1","Hypercarotinemia","E67",["Hypercarotinemia"]]);
allCodes.push(["E67.2","Hypervitaminosis D","E67",["Hypervitaminosis D"]]);
allCodes.push(["E67.3","Hypervitaminosis E","E67",["Hypervitaminosis E"]]);
allCodes.push(["E67.8","Other hyperalimentation","E67",["Other hyperalimentation"]]);
allCodes.push(["E67.9","Hyperalimentation, unspecified","E67",["Hyperalimentation NOS"]]);
allCodes.push(["E70.0","Classical phenylketonuria","E70",["PKU"]]);
allCodes.push(["E70.1","Other hyperphenylalaninemias","E70",["Non-PKU hyperphenylalaninemia"]]);
allCodes.push(["E70.2","Disorders of tyrosine metabolism","E70",["Tyrosinemia","Tyrosinosis"]]);
allCodes.push(["E70.3","Albinism","E70",["Albinism"]]);
allCodes.push(["E70.8","Other disorders of aromatic amino-acid metabolism","E70",["Aromatic amino acid disorder"]]);
allCodes.push(["E70.9","Disorder of aromatic amino-acid metabolism, unspecified","E70",["Aromatic amino acid disorder NOS"]]);
allCodes.push(["E71.0","Maple syrup urine disease","E71",["MSUD","Branched-chain ketoaciduria"]]);
allCodes.push(["E71.1","Disorders of branched-chain amino-acid metabolism","E71",["BCAA metabolism disorder"]]);
allCodes.push(["E71.2","Disorders of branched-chain amino-acid metabolism, unspecified","E71",["BCAA disorder NOS"]]);
allCodes.push(["E71.3","Disorders of fatty-acid metabolism","E71",["Fatty acid oxidation disorder"]]);
allCodes.push(["E71.4","Disorders of propionate metabolism","E71",["Propionic acidemia"]]);
allCodes.push(["E71.5","Disorders of other branched-chain amino-acid metabolism","E71",["Other BCAA disorder"]]);
allCodes.push(["E71.8","Other disorders of branched-chain amino-acid metabolism and fatty-acid metabolism","E71",["Other metabolic disorder"]]);
allCodes.push(["E71.9","Disorder of branched-chain amino-acid metabolism and fatty-acid metabolism, unspecified","E71",["BCAA/fatty acid disorder NOS"]]);
allCodes.push(["E72.0","Disorders of amino-acid transport","E72",["Amino acid transport disorder"]]);
allCodes.push(["E72.1","Disorders of amino-acid metabolism","E72",["Amino acid metabolism disorder"]]);
allCodes.push(["E72.2","Disorders of urea cycle metabolism","E72",["Urea cycle disorder","UCD"]]);
allCodes.push(["E72.3","Disorders of glycine metabolism","E72",["Glycine metabolism disorder"]]);
allCodes.push(["E72.8","Other disorders of amino-acid metabolism","E72",["Amino acid disorder"]]);
allCodes.push(["E72.9","Disorder of amino-acid metabolism, unspecified","E72",["Amino acid disorder NOS"]]);
allCodes.push(["E73.0","Congenital lactase deficiency","E73",["Congenital lactase deficiency"]]);
allCodes.push(["E73.1","Acquired lactase deficiency","E73",["Lactose intolerance","Lactase deficiency"]]);
allCodes.push(["E73.8","Other disorders of lactose metabolism","E73",["Lactose metabolism disorder"]]);
allCodes.push(["E73.9","Lactose intolerance, unspecified","E73",["Lactose intolerance NOS"]]);
allCodes.push(["E74.0","Glycogen storage disease","E74",["GSD","Von Gierke disease"]]);
allCodes.push(["E74.1","Disorders of fructose metabolism","E74",["Fructose intolerance","Hereditary fructose intolerance"]]);
allCodes.push(["E74.2","Disorders of galactose metabolism","E74",["Galactosemia"]]);
allCodes.push(["E74.3","Other disorders of carbohydrate metabolism","E74",["Carbohydrate metabolism disorder"]]);
allCodes.push(["E74.4","Disorders of pyruvate metabolism and gluconeogenesis","E74",["Pyruvate metabolism disorder"]]);
allCodes.push(["E74.8","Other specified disorders of carbohydrate metabolism","E74",["Carbohydrate metabolism disorder"]]);
allCodes.push(["E74.9","Disorder of carbohydrate metabolism, unspecified","E74",["Carbohydrate metabolism disorder NOS"]]);
allCodes.push(["E75.0","Sphingolipidosis","E75",["Sphingolipidosis","Gaucher disease"]]);
allCodes.push(["E75.1","Other lipid storage disorders","E75",["Lipid storage disease"]]);
allCodes.push(["E75.2","Disorders of sphingolipid metabolism","E75",["Sphingolipid metabolism disorder"]]);
allCodes.push(["E75.3","Other disorders of lipoid metabolism","E75",["Lipoid metabolism disorder"]]);
allCodes.push(["E75.4","Niemann-Pick disease","E75",["Niemann-Pick"]]);
allCodes.push(["E75.5","Other lipid storage disorders","E75",["Lipid storage disease"]]);
allCodes.push(["E75.6","Lipid storage disorder, unspecified","E75",["Lipid storage disease NOS"]]);
allCodes.push(["E76.0","Mucopolysaccharidosis, type I [Hurler syndrome or Scheie syndrome]","E76",["MPS I","Hurler syndrome","Scheie syndrome"]]);
allCodes.push(["E76.1","Mucopolysaccharidosis, type II [Hunter syndrome]","E76",["MPS II","Hunter syndrome"]]);
allCodes.push(["E76.2","Mucopolysaccharidosis, type III [Sanfilippo syndrome]","E76",["MPS III","Sanfilippo syndrome"]]);
allCodes.push(["E76.3","Mucopolysaccharidosis, type IV [Morquio syndrome]","E76",["MPS IV","Morquio syndrome"]]);
allCodes.push(["E76.8","Other mucopolysaccharidoses","E76",["Other MPS"]]);
allCodes.push(["E76.9","Mucopolysaccharidosis, unspecified","E76",["MPS NOS"]]);
allCodes.push(["E78.0","Pure hypercholesterolemia","E78",["Hypercholesterolemia","High cholesterol"]]);
allCodes.push(["E78.1","Pure hyperglyceridemia","E78",["Hypertriglyceridemia","High triglycerides"]]);
allCodes.push(["E78.2","Mixed hyperlipidemia","E78",["Mixed hyperlipidemia","Dyslipidemia"]]);
allCodes.push(["E78.3","Hyperlipoproteinemia","E78",["Hyperlipoproteinemia"]]);
allCodes.push(["E78.4","Other hyperlipidemia","E78",["Hyperlipidemia NOS"]]);
allCodes.push(["E78.5","Hyperlipidemia, unspecified","E78",["High lipids NOS"]]);
allCodes.push(["E78.6","Lipoprotein deficiency","E78",["Lipoprotein deficiency"]]);
allCodes.push(["E78.8","Other disorders of lipoprotein metabolism and other lipidemias","E78",["Lipid metabolism disorder"]]);
allCodes.push(["E78.9","Disorder of lipoprotein metabolism and other lipidemias, unspecified","E78",["Lipid disorder NOS"]]);
allCodes.push(["E79.0","Primary hyperuricemia, unspecified","E79",["Gout","Hyperuricemia"]]);
allCodes.push(["E79.1","Lesch-Nyhan syndrome","E79",["Lesch-Nyhan"]]);
allCodes.push(["E79.8","Other disorders of purine and pyrimidine metabolism","E79",["Purine metabolism disorder"]]);
allCodes.push(["E79.9","Disorder of purine and pyrimidine metabolism, unspecified","E79",["Purine metabolism disorder NOS"]]);
allCodes.push(["E80.0","Hereditary porphyria","E80",["Porphyria"]]);
allCodes.push(["E80.1","Porphyria cutanea tarda","E80",["PCT"]]);
allCodes.push(["E80.2","Other porphyria","E80",["Other porphyria"]]);
allCodes.push(["E80.3","Disorders of bilirubin metabolism","E80",["Gilbert syndrome","Crigler-Najjar","Dubin-Johnson"]]);
allCodes.push(["E80.4","Gilbert syndrome","E80",["Gilbert syndrome"]]);
allCodes.push(["E80.5","Crigler-Najjar syndrome","E80",["Crigler-Najjar"]]);
allCodes.push(["E80.6","Other disorders of bilirubin metabolism","E80",["Bilirubin disorder"]]);
allCodes.push(["E80.7","Disorders of porphyrin and bilirubin metabolism, unspecified","E80",["Heme metabolism disorder NOS"]]);
allCodes.push(["E83.0","Disorders of copper metabolism","E83",["Wilson disease","Menkes disease"]]);
allCodes.push(["E83.1","Disorders of iron metabolism","E83",["Hemochromatosis","Iron overload"]]);
allCodes.push(["E83.2","Disorders of zinc metabolism","E83",["Zinc metabolism disorder"]]);
allCodes.push(["E83.3","Disorders of phosphorus metabolism","E83",["Phosphorus metabolism disorder"]]);
allCodes.push(["E83.4","Disorders of magnesium metabolism","E83",["Magnesium metabolism disorder"]]);
allCodes.push(["E83.5","Disorders of calcium metabolism","E83",["Calcium metabolism disorder","Hypocalcemia","Hypercalcemia"]]);
allCodes.push(["E83.8","Other disorders of mineral metabolism","E83",["Mineral metabolism disorder"]]);
allCodes.push(["E83.9","Disorder of mineral metabolism, unspecified","E83",["Mineral metabolism disorder NOS"]]);
allCodes.push(["E84.0","Cystic fibrosis with pulmonary manifestations","E84",["CF with pulmonary involvement"]]);
allCodes.push(["E84.1","Cystic fibrosis with intestinal manifestations","E84",["CF with intestinal involvement"]]);
allCodes.push(["E84.8","Cystic fibrosis with other manifestations","E84",["CF with other manifestation"]]);
allCodes.push(["E84.9","Cystic fibrosis, unspecified","E84",["CF NOS","Cystic fibrosis"]]);
allCodes.push(["E85.0","Non-neuropathic hereditary amyloidosis","E85",["Hereditary amyloidosis"]]);
allCodes.push(["E85.1","Neuropathic hereditary amyloidosis","E85",["FAP","Familial amyloid polyneuropathy"]]);
allCodes.push(["E85.2","Senile systemic amyloidosis","E85",["Senile amyloidosis"]]);
allCodes.push(["E85.3","Secondary systemic amyloidosis","E85",["AA amyloidosis"]]);
allCodes.push(["E85.4","Localized amyloidosis","E85",["Localized amyloidosis"]]);
allCodes.push(["E85.8","Other amyloidosis","E85",["Other amyloidosis"]]);
allCodes.push(["E85.9","Amyloidosis, unspecified","E85",["Amyloidosis NOS"]]);
allCodes.push(["E86.0","Dehydration","E86",["Dehydration"]]);
allCodes.push(["E86.1","Volume depletion","E86",["Volume depletion","Hypovolemia"]]);
allCodes.push(["E86.9","Volume depletion, unspecified","E86",["Volume depletion NOS"]]);
allCodes.push(["E87.0","Hyperosmolality and hypernatremia","E87",["Hypernatremia"]]);
allCodes.push(["E87.1","Hypo-osmolality and hyponatremia","E87",["Hyponatremia","Low sodium"]]);
allCodes.push(["E87.2","Metabolic acidosis","E87",["Metabolic acidosis"]]);
allCodes.push(["E87.3","Alkalosis","E87",["Metabolic alkalosis","Respiratory alkalosis"]]);
allCodes.push(["E87.4","Mixed disorder of acid-base balance","E87",["Mixed acid-base disorder"]]);
allCodes.push(["E87.5","Hyperkalemia","E87",["High potassium"]]);
allCodes.push(["E87.6","Hypokalemia","E87",["Low potassium"]]);
allCodes.push(["E87.7","Fluid overload","E87",["Fluid overload","Volume overload"]]);
allCodes.push(["E87.8","Other disorders of fluid, electrolyte and acid-base balance","E87",["Electrolyte disorder"]]);
allCodes.push(["E88.0","Obesity due to excess calories","E88",["Obesity"]]);
allCodes.push(["E88.1","Lipodystrophy, not elsewhere classified","E88",["Lipodystrophy"]]);
allCodes.push(["E88.2","Lipomatosis, not elsewhere classified","E88",["Lipomatosis"]]);
allCodes.push(["E88.3","Lymphedema, not elsewhere classified","E88",["Lymphedema"]]);
allCodes.push(["E88.8","Other metabolic disorders","E88",["Metabolic disorder"]]);
allCodes.push(["E88.9","Metabolic disorder, unspecified","E88",["Metabolic disorder NOS"]]);
allCodes.push(["E89.0","Postprocedural hypothyroidism","E89",["Post-thyroidectomy hypothyroidism"]]);
allCodes.push(["E89.1","Postprocedural hypoinsulinemia","E89",["Post-pancreatectomy diabetes"]]);
allCodes.push(["E89.2","Postprocedural hypoparathyroidism","E89",["Post-surgical hypoparathyroidism"]]);
allCodes.push(["E89.3","Postprocedural hypopituitarism","E89",["Post-surgical hypopituitarism"]]);
allCodes.push(["E89.4","Postprocedural ovarian failure","E89",["Post-surgical ovarian failure"]]);
allCodes.push(["E89.5","Postprocedural adrenal (cortical) insufficiency","E89",["Post-adrenalectomy adrenal insufficiency"]]);
allCodes.push(["E89.6","Postprocedural hyperparathyroidism","E89",["Post-surgical hyperparathyroidism"]]);
allCodes.push(["E89.8","Other postprocedural endocrine and metabolic disorders","E89",["Post-surgical endocrine disorder"]]);
allCodes.push(["E89.9","Postprocedural endocrine and metabolic disorder, unspecified","E89",["Post-surgical endocrine disorder NOS"]]);

// Write all these codes
var codeLines = [];
for (var i = 0; i < allCodes.length; i++) {
  var c = allCodes[i];
  var cu = c[3] || [];
  var s = '  codes["' + c[0] + '"] = { code: "' + c[0] + '", description: "' + c[1].replace(/"/g, '\\"') + '", category: "' + c[2] + '", excludes1: [], excludes2: [], includes: [], commonUse: [' + cu.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '], documentation: [] };';
  codeLines.push(s);
}

fs.writeFileSync(path.join(__dirname, 'part_ch3_4.txt'), codeLines.join('\n'), 'utf8');
console.log('Wrote ' + allCodes.length + ' Chapter III+IV entries');
