var fs = require('fs');
var path = require('path');
var allCodes = [];

// CHAPTER V: MENTAL/BEHAVIORAL (F01-F99)
var ch5 = [
["F01.0","Vascular dementia of mild severity","F01",["Mild vascular dementia"]],
["F01.1","Vascular dementia of moderate severity","F01",["Moderate vascular dementia"]],
["F01.2","Vascular dementia of severe severity","F01",["Severe vascular dementia"]],
["F01.9","Vascular dementia, unspecified","F01",["Vascular dementia NOS"]],
["F02.0","Dementia in Alzheimer disease with early onset","F02",["Early-onset Alzheimer dementia"]],
["F02.1","Dementia in Alzheimer disease with late onset","F02",["Late-onset Alzheimer dementia"]],
["F02.8","Dementia in other diseases classified elsewhere","F02",["Dementia NOS"]],
["F03","Unspecified dementia","F03",["Dementia NOS","Senile dementia"]],
["F04","Organic amnesic syndrome, not induced by alcohol","F04",["Korsakoff syndrome"]],
["F05.0","Delirium with hyperactivity","F05",["Hyperactive delirium"]],
["F05.1","Delirium with hypoactivity","F05",["Hypoactive delirium"]],
["F05.9","Delirium, unspecified","F05",["Delirium NOS"]],
["F06.0","Psychotic disorder with delusions due to physiological condition","F06",["Delusional disorder NOS"]],
["F06.1","Psychotic disorder with hallucinations due to physiological condition","F06",["Hallucinatory disorder NOS"]],
["F06.3","Mood disorders due to known physiological condition","F06",["Organic mood disorder"]],
["F06.4","Anxiety disorder due to known physiological condition","F06",["Organic anxiety disorder"]],
["F06.7","Mild neurocognitive disorder due to known physiological condition","F06",["Mild neurocognitive disorder"]],
["F06.9","Unspecified mental disorder due to known physiological condition","F06",["Organic mental disorder NOS"]],
["F09","Unspecified organic mental disorder","F09",["Organic brain syndrome NOS"]],
["F10.10","Alcohol abuse, uncomplicated","F10",["Alcohol abuse"]],
["F10.20","Alcohol dependence, uncomplicated","F10",["Alcoholism","Alcohol dependence"]],
["F10.21","Alcohol dependence, in remission","F10",["Alcohol dependence in remission"]],
["F10.92","Alcohol use, unspecified with intoxication","F10",["Alcohol intoxication"]],
["F10.93","Alcohol use, unspecified with withdrawal","F10",["Alcohol withdrawal"]],
["F11.10","Opioid abuse, uncomplicated","F11",["Opioid abuse"]],
["F11.20","Opioid dependence, uncomplicated","F11",["Opioid dependence","Heroin dependence"]],
["F11.23","Opioid dependence with withdrawal","F11",["Opioid withdrawal"]],
["F12.10","Cannabis abuse, uncomplicated","F12",["Marijuana abuse"]],
["F12.20","Cannabis dependence, uncomplicated","F12",["Cannabis dependence","Marijuana dependence"]],
["F13.20","Sedative-hypnotic dependence, uncomplicated","F13",["Benzodiazepine dependence"]],
["F13.23","Sedative-hypnotic dependence with withdrawal","F13",["Benzodiazepine withdrawal"]],
["F14.10","Cocaine abuse, uncomplicated","F14",["Cocaine abuse"]],
["F14.20","Cocaine dependence, uncomplicated","F14",["Cocaine dependence"]],
["F15.10","Other stimulant abuse, uncomplicated","F15",["Amphetamine abuse"]],
["F15.20","Other stimulant dependence, uncomplicated","F15",["Amphetamine dependence","Methamphetamine dependence"]],
["F17.210","Nicotine dependence, cigarettes, uncomplicated","F17",["Smoking","Tobacco dependence","Cigarette dependence"]],
["F18.10","Inhalant abuse, uncomplicated","F18",["Inhalant abuse"]],
["F19.20","Other psychoactive substance dependence","F19",["Substance dependence NOS"]],
["F20.0","Paranoid schizophrenia","F20",["Paranoid schizophrenia"]],
["F20.1","Hebephrenic schizophrenia","F20",["Disorganized schizophrenia"]],
["F20.2","Catatonic schizophrenia","F20",["Catatonic schizophrenia"]],
["F20.3","Undifferentiated schizophrenia","F20",["Undifferentiated schizophrenia"]],
["F20.9","Schizophrenia, unspecified","F20",["Schizophrenia NOS"]],
["F21","Schizotypal disorder","F21",["Schizotypal personality"]],
["F22","Delusional disorders","F22",["Delusional disorder"]],
["F23","Brief psychotic disorder","F23",["Brief reactive psychosis"]],
["F25.0","Schizoaffective disorder, manic type","F25",["Schizoaffective - manic"]],
["F25.1","Schizoaffective disorder, depressive type","F25",["Schizoaffective - depressive"]],
["F25.9","Schizoaffective disorder, unspecified","F25",["Schizoaffective disorder NOS"]],
["F29","Unspecified psychosis","F29",["Psychosis NOS"]],
["F30.0","Hypomanic episode","F30",["Hypomania"]],
["F30.1","Manic episode","F30",["Mania"]],
["F31.0","Bipolar I, current episode hypomanic","F31",["Bipolar I - hypomanic"]],
["F31.1","Bipolar I, current episode manic","F31",["Bipolar I - manic"]],
["F31.2","Bipolar I, current episode manic severe with psychotic features","F31",["Bipolar I - manic with psychosis"]],
["F31.3","Bipolar I, current episode depressed","F31",["Bipolar depression"]],
["F31.81","Bipolar II disorder","F31",["Bipolar II"]],
["F31.9","Bipolar disorder, unspecified","F31",["Bipolar disorder NOS"]],
["F32.0","Major depressive disorder, single episode, mild","F32",["Depression - mild"]],
["F32.1","Major depressive disorder, single episode, moderate","F32",["Depression - moderate"]],
["F32.2","Major depressive disorder, single episode, severe","F32",["Depression - severe"]],
["F32.9","Major depressive disorder, single episode, unspecified","F32",["Depression NOS"]],
["F33.0","Major depressive disorder, recurrent, mild","F33",["Recurrent depression - mild"]],
["F33.1","Major depressive disorder, recurrent, moderate","F33",["Recurrent depression - moderate"]],
["F33.2","Major depressive disorder, recurrent, severe","F33",["Recurrent depression - severe"]],
["F33.9","Major depressive disorder, recurrent, unspecified","F33",["Recurrent depression NOS"]],
["F34.0","Cyclothymic disorder","F34",["Cyclothymia"]],
["F34.1","Dysthymic disorder","F34",["Dysthymia"]],
["F39","Unspecified mood disorder","F39",["Mood disorder NOS"]],
["F40.0","Agoraphobia","F40",["Agoraphobia"]],
["F40.1","Social phobia","F40",["Social anxiety disorder","Social phobia"]],
["F40.2","Specific phobias","F40",["Specific phobia"]],
["F41.0","Panic disorder without agoraphobia","F41",["Panic disorder","Panic attacks"]],
["F41.1","Generalized anxiety disorder","F41",["GAD","Anxiety disorder"]],
["F41.9","Anxiety disorder, unspecified","F41",["Anxiety NOS"]],
["F42.0","Obsessional thoughts or ruminations","F42",["OCD - obsessions"]],
["F42.1","Compulsive acts","F42",["OCD - compulsions"]],
["F42.2","Mixed obsessional thoughts and acts","F42",["OCD"]],
["F42.9","Obsessive-compulsive disorder, unspecified","F42",["OCD NOS"]],
["F43.1","Post-traumatic stress disorder","F43",["PTSD"]],
["F43.20","Adjustment disorder, unspecified","F43",["Adjustment disorder NOS"]],
["F43.21","Adjustment disorder with depressed mood","F43",["Adjustment disorder - depressed"]],
["F43.22","Adjustment disorder with anxiety","F43",["Adjustment disorder - anxious"]],
["F43.23","Adjustment disorder with mixed anxiety and depressed mood","F43",["Adjustment disorder - mixed"]],
["F44.0","Dissociative amnesia","F44",["Dissociative amnesia"]],
["F44.1","Dissociative fugue","F44",["Fugue state"]],
["F44.4","Dissociative motor disorder","F44",["Conversion disorder - motor"]],
["F44.5","Dissociative convulsions","F44",["Psychogenic seizures"]],
["F44.6","Dissociative anesthesia and sensory loss","F44",["Conversion - sensory"]],
["F44.9","Dissociative [conversion] disorder, unspecified","F44",["Conversion disorder NOS"]],
["F45.0","Somatization disorder","F45",["Somatization disorder"]],
["F45.2","Hypochondriasis","F45",["Health anxiety","Hypochondriasis"]],
["F45.21","Body dysmorphic disorder","F45",["BDD","Body dysmorphia"]],
["F45.3","Somatoform pain disorder","F45",["Psychogenic pain"]],
["F45.9","Somatoform disorder, unspecified","F45",["Somatoform disorder NOS"]],
["F48.0","Neurasthenia","F48",["Neurasthenia","Chronic fatigue syndrome"]],
["F48.1","Depersonalization-derealization disorder","F48",["Depersonalization"]],
["F50.0","Anorexia nervosa","F50",["Anorexia"]],
["F50.1","Bulimia nervosa","F50",["Bulimia"]],
["F50.9","Eating disorder, unspecified","F50",["Eating disorder NOS"]],
["F51.0","Nonorganic insomnia","F51",["Insomnia"]],
["F51.1","Nonorganic hypersomnia","F51",["Hypersomnia"]],
["F60.0","Paranoid personality disorder","F60",["Paranoid personality"]],
["F60.1","Schizoid personality disorder","F60",["Schizoid personality"]],
["F60.2","Antisocial personality disorder","F60",["ASPD","Antisocial personality","Sociopathy"]],
["F60.3","Borderline personality disorder","F60",["BPD","Borderline personality"]],
["F60.5","Avoidant personality disorder","F60",["Avoidant personality"]],
["F60.6","Dependent personality disorder","F60",["Dependent personality"]],
["F60.7","Narcissistic personality disorder","F60",["NPD","Narcissistic personality"]],
["F60.9","Personality disorder, unspecified","F60",["Personality disorder NOS"]],
["F63.0","Pathological gambling","F63",["Gambling disorder","Compulsive gambling"]],
["F63.1","Pyromania","F63",["Pyromania"]],
["F63.2","Kleptomania","F63",["Kleptomania"]],
["F64.0","Transsexualism","F64",["Gender dysphoria"]],
["F80.0","Phonological disorder","F80",["Speech sound disorder"]],
["F80.1","Expressive language disorder","F80",["Expressive language delay"]],
["F80.2","Mixed receptive-expressive language disorder","F80",["Mixed language disorder"]],
["F81.0","Specific reading disorder","F81",["Dyslexia","Reading disorder"]],
["F81.2","Specific disorder of arithmetical skills","F81",["Dyscalculia","Math disorder"]],
["F82","Specific developmental disorder of motor function","F82",["Developmental coordination disorder","Dyspraxia"]],
["F84.0","Childhood autism","F84",["Autism","Autism spectrum disorder","ASD"]],
["F84.1","Asperger syndrome","F84",["Asperger syndrome"]],
["F84.9","Pervasive developmental disorder, unspecified","F84",["PDD NOS","Autism NOS"]],
["F90.0","ADHD, predominantly inattentive type","F90",["ADHD - inattentive","ADD"]],
["F90.1","ADHD, predominantly hyperactive type","F90",["ADHD - hyperactive"]],
["F90.2","ADHD, combined type","F90",["ADHD - combined"]],
["F90.9","ADHD, unspecified type","F90",["ADHD NOS"]],
["F95.0","Transient tic disorder","F95",["Transient tic disorder"]],
["F95.1","Chronic motor or vocal tic disorder","F95",["Chronic tic disorder"]],
["F95.2","Tourette syndrome","F95",["Tourette syndrome"]],
["F98.0","Enuresis","F98",["Bedwetting","Nocturnal enuresis"]],
["F98.1","Encopresis","F98",["Fecal soiling"]],
["F98.5","Stuttering","F98",["Stuttering"]]
];

// CHAPTER VI: NERVOUS SYSTEM (G00-G99)
var ch6 = [
["G00.0","Haemophilus influenzae meningitis","G00",["H. influenzae meningitis"]],
["G00.1","Pneumococcal meningitis","G00",["Strep pneumoniae meningitis"]],
["G00.2","Streptococcal meningitis","G00",["Group B strep meningitis"]],
["G00.9","Bacterial meningitis, unspecified","G00",["Bacterial meningitis NOS"]],
["G03.0","Meningitis due to other bacteria","G03",["Meningitis NOS"]],
["G03.1","Cryptococcal meningitis","G03",["Fungal meningitis"]],
["G03.8","Meningitis due to other organisms","G03",["Meningitis NOS"]],
["G03.9","Meningitis, unspecified","G03",["Meningitis NOS"]],
["G04.0","Acute disseminated encephalitis","G04",["ADEM"]],
["G04.1","Acute transverse myelitis","G04",["Transverse myelitis"]],
["G04.2","Bacterial meningoencephalitis","G04",["Bacterial meningoencephalitis"]],
["G04.8","Other viral meningoencephalitis","G04",["Encephalitis NOS"]],
["G04.9","Encephalitis, myelitis and encephalomyelitis, unspecified","G04",["Encephalitis NOS"]],
["G10","Huntington disease","G10",["Huntington chorea","Huntington disease"]],
["G11.0","Congenital cerebellar ataxia","G11",["Congenital cerebellar ataxia"]],
["G11.1","Friedreich ataxia","G11",["Friedreich ataxia"]],
["G11.2","Early-onset cerebellar ataxia","G11",["Early-onset ataxia"]],
["G11.3","Cerebellar ataxia with DNA repair defects","G11",["Ataxia telangiectasia"]],
["G11.4","Hereditary spastic paraplegia","G11",["HSP","Spastic paraplegia"]],
["G11.8","Other hereditary ataxias","G11",["Hereditary ataxia NOS"]],
["G11.9","Hereditary ataxia, unspecified","G11",["Hereditary ataxia NOS"]],
["G20","Parkinson disease","G20",["Parkinsonism","PD","Paralysis agitans"]],
["G21.0","Malignant neuroleptic syndrome","G21",["NMS"]],
["G21.1","Drug-induced secondary parkinsonism","G21",["Drug-induced parkinsonism"]],
["G21.2","Postencephalitic parkinsonism","G21",["Postencephalitic parkinsonism"]],
["G21.3","Idiopathic Parkinson disease with dyskinesia","G21",["PD with dyskinesia"]],
["G21.8","Other secondary parkinsonism","G21",["Secondary parkinsonism NOS"]],
["G21.9","Secondary parkinsonism, unspecified","G21",["Secondary parkinsonism NOS"]],
["G25.0","Essential tremor","G25",["ET","Benign essential tremor"]],
["G25.1","Drug-induced tremor","G25",["Drug-induced tremor"]],
["G25.2","Other specified forms of tremor","G25",["Tremor NOS"]],
["G25.3","Myoclonus","G25",["Myoclonus"]],
["G25.4","Drug-induced dystonia","G25",["Drug-induced dystonia"]],
["G25.5","Other chorea","G25",["Chorea NOS"]],
["G25.8","Other specified extrapyramidal and movement disorders","G25",["Movement disorder NOS"]],
["G25.9","Extrapyramidal and movement disorder, unspecified","G25",["Movement disorder NOS"]],
["G30.0","Alzheimer disease with early onset","G30",["Early-onset Alzheimer disease"]],
["G30.1","Alzheimer disease with late onset","G30",["Late-onset Alzheimer disease"]],
["G30.9","Alzheimer disease, unspecified","G30",["Alzheimer disease NOS"]],
["G31.0","Localized cerebral atrophy","G31",["Cerebral atrophy"]],
["G31.1","Senile degeneration of brain","G31",["Senile brain degeneration"]],
["G31.2","Degeneration of nervous system due to alcohol","G31",["Wernicke-Korsakoff syndrome"]],
["G31.8","Other degenerative diseases of nervous system","G31",["Neurodegeneration NOS"]],
["G31.9","Degenerative disease of nervous system, unspecified","G31",["Neurodegeneration NOS"]],
["G35","Multiple sclerosis","G35",["MS","Demyelinating disease"]],
["G40.0","Localization-related (focal) (partial) idiopathic epilepsy","G40",["Idiopathic epilepsy"]],
["G40.1","Localization-related (focal) (partial) symptomatic epilepsy","G40",["Symptomatic epilepsy"]],
["G40.2","Localization-related (focal) (partial) symptomatic epilepsy, complex","G40",["Temporal lobe epilepsy"]],
["G40.3","Generalized idiopathic epilepsy","G40",["Juvenile myoclonic epilepsy"]],
["G40.4","Other generalized epilepsy","G40",["Generalized epilepsy NOS"]],
["G40.5","Special epileptic syndromes","G40",["Epilepsy syndrome NOS"]],
["G40.9","Epilepsy, unspecified","G40",["Epilepsy NOS","Seizure disorder"]],
["G41.0","Grand mal status epilepticus","G41",["Generalized tonic-clonic status epilepticus"]],
["G41.1","Complex partial status epilepticus","G41",["Focal status epilepticus"]],
["G41.2","Simple partial status epilepticus","G41",["Simple partial status"]],
["G41.8","Other status epilepticus","G41",["Status epilepticus NOS"]],
["G41.9","Status epilepticus, unspecified","G41",["Status epilepticus NOS"]],
["G43.0","Migraine without aura","G43",["Common migraine","Migraine without aura"]],
["G43.1","Migraine with aura","G43",["Classic migraine","Migraine with aura"]],
["G43.2","Status migrainosus","G43",["Status migrainosus"]],
["G43.7","Chronic migraine without aura","G43",["Chronic migraine"]],
["G43.8","Other migraine","G43",["Migraine NOS"]],
["G43.9","Migraine, unspecified","G43",["Migraine NOS"]],
["G44.0","Cluster headache syndrome","G44",["Cluster headache"]],
["G44.1","Vascular headache, not elsewhere classified","G44",["Vascular headache"]],
["G44.2","Tension-type headache","G44",["Tension headache","TTH"]],
["G44.3","Chronic post-traumatic headache","G44",["Post-traumatic headache"]],
["G44.4","Drug-induced headache, not elsewhere classified","G44",["Medication-overuse headache"]],
["G44.8","Other specified headache syndromes","G44",["Headache NOS"]],
["G45.0","Vertebro-basilar artery syndrome","G45",["VBI","Vertebrobasilar insufficiency"]],
["G45.1","Carotid artery syndrome (hemispheric)","G45",["Carotid artery syndrome"]],
["G45.2","Multiple and bilateral precerebral artery syndromes","G45",["Multi-territory TIA"]],
["G45.8","Other transient cerebral ischaemic attacks","G45",["TIA NOS"]],
["G45.9","Transient cerebral ischaemic attack, unspecified","G45",["TIA NOS"]],
["G47.0","Insomnia","G47",["Insomnia"]],
["G47.1","Hypersomnia","G47",["Hypersomnia","Excessive daytime sleepiness"]],
["G47.2","Circadian rhythm sleep disorder","G47",["Sleep-wake disorder"]],
["G47.3","Sleep apnea","G47",["Sleep apnea","OSA","Obstructive sleep apnea"]],
["G47.4","Narcolepsy and cataplexy","G47",["Narcolepsy"]],
["G47.8","Other sleep disorders","G47",["Sleep disorder NOS"]],
["G47.9","Sleep disorder, unspecified","G47",["Sleep disorder NOS"]],
["G50.0","Trigeminal neuralgia","G50",["Trigeminal neuralgia","Tic douloureux"]],
["G50.1","Atypical facial pain","G50",["Atypical facial pain"]],
["G50.8","Other disorders of trigeminal nerve","G50",["Trigeminal nerve disorder"]],
["G50.9","Disorder of trigeminal nerve, unspecified","G50",["Trigeminal nerve disorder NOS"]],
["G51.0","Bell palsy","G51",["Bell palsy","Idiopathic facial paralysis"]],
["G51.1","Geniculate ganglionitis","G51",["Ramsay Hunt syndrome"]],
["G51.2","Melkersson syndrome","G51",["Melkersson-Rosenthal syndrome"]],
["G51.8","Other disorders of facial nerve","G51",["Facial nerve disorder"]],
["G51.9","Facial nerve disorder, unspecified","G51",["Facial nerve disorder NOS"]],
["G54.0","Brachial plexus disorders","G54",["Brachial plexopathy","Thoracic outlet syndrome"]],
["G54.1","Lumbosacral root lesions","G54",["Radiculopathy","Nerve root lesion"]],
["G54.2","Cervical root lesions","G54",["Cervical radiculopathy"]],
["G54.4","Lumbosacral root lesions","G54",["Lumbar radiculopathy"]],
["G54.5","Neuralgic amyotrophy","G54",["Parsonage-Turner syndrome"]],
["G54.8","Other nerve root and plexus disorders","G54",["Nerve root disorder NOS"]],
["G54.9","Nerve root and plexus disorder, unspecified","G54",["Nerve root disorder NOS"]],
["G55","Nerve root and plexus compressions in diseases classified elsewhere","G55",["Radiculopathy NOS"]],
["G56.0","Carpal tunnel syndrome","G56",["CTS","Carpal tunnel syndrome"]],
["G56.1","Median nerve lesion","G56",["Median neuropathy"]],
["G56.2","Ulnar nerve lesion at elbow","G56",["Ulnar neuropathy at elbow"]],
["G56.3","Ulnar nerve lesion at wrist","G56",["Ulnar neuropathy at wrist"]],
["G56.4","Radial nerve lesion","G56",["Radial neuropathy","Saturday night palsy"]],
["G56.8","Other mononeuropathies of upper limb","G56",["Upper limb mononeuropathy"]],
["G56.9","Mononeuropathy of upper limb, unspecified","G56",["Upper limb mononeuropathy NOS"]],
["G57.0","Lesion of sciatic nerve","G57",["Sciatica","Sciatic neuropathy"]],
["G57.1","Meralgia paraesthetica","G57",["Lateral femoral cutaneous neuropathy"]],
["G57.2","Lesion of lateral popliteal nerve","G57",["Common peroneal neuropathy"]],
["G57.3","Lesion of medial popliteal nerve","G57",["Tibial neuropathy"]],
["G57.4","Lesion of tibial nerve","G57",["Tarsal tunnel syndrome"]],
["G57.5","Lesion of lateral plantar nerve","G57",["Baxter neuropathy"]],
["G57.6","Lesion of plantar nerve","G57",["Morton neuroma"]],
["G57.8","Other mononeuropathies of lower limb","G57",["Lower limb mononeuropathy"]],
["G57.9","Mononeuropathy of lower limb, unspecified","G57",["Lower limb mononeuropathy NOS"]],
["G60.0","Hereditary motor and sensory neuropathy","G60",["Charcot-Marie-Tooth disease","CMT"]],
["G60.1","Refsum disease","G60",["Refsum disease"]],
["G60.2","Neuropathy in association with hereditary ataxia","G60",["Friedreich ataxia neuropathy"]],
["G60.3","Idiopathic progressive neuropathy","G60",["Chronic inflammatory demyelinating polyneuropathy"]],
["G60.8","Other hereditary and idiopathic neuropathies","G60",["Hereditary neuropathy NOS"]],
["G60.9","Hereditary and idiopathic neuropathy, unspecified","G60",["Hereditary neuropathy NOS"]],
["G61.0","Guillain-Barre syndrome","G61",["GBS","Guillain-Barre syndrome"]],
["G61.1","Miller Fisher syndrome","G61",["Miller Fisher syndrome"]],
["G61.8","Other inflammatory polyneuropathies","G61",["CIDP","Inflammatory polyneuropathy"]],
["G61.9","Inflammatory polyneuropathy, unspecified","G61",["Inflammatory polyneuropathy NOS"]],
["G62.0","Alcoholic polyneuropathy","G62",["Alcoholic neuropathy"]],
["G62.1","Polyneuropathy due to other toxic agents","G62",["Toxic neuropathy"]],
["G62.2","Polyneuropathy due to malignancy","G62",["Paraneoplastic neuropathy"]],
["G62.8","Other specified polyneuropathies","G62",["Polyneuropathy NOS"]],
["G62.9","Polyneuropathy, unspecified","G62",["Neuropathy NOS","Peripheral neuropathy"]],
["G70.0","Myasthenia gravis","G70",["Myasthenia gravis","MG"]],
["G70.1","Lambert-Eaton myasthenic syndrome","G70",["LEMS"]],
["G70.2","Congenital and developmental myasthenia","G70",["Congenital myasthenia"]],
["G70.8","Other myoneural disorders","G70",["Myoneural disorder"]],
["G70.9","Myoneural disorder, unspecified","G70",["Neuromuscular disorder NOS"]],
["G71.0","Muscular dystrophy","G71",["Duchenne muscular dystrophy","Becker muscular dystrophy"]],
["G71.1","Neuromuscular junction disorders","G71",["Neuromuscular junction disorder"]],
["G71.2","Congenital myopathies","G71",["Congenital myopathy"]],
["G71.3","Mitochondrial myopathy","G71",["Mitochondrial myopathy"]],
["G71.8","Other primary disorders of muscles","G71",["Myopathy NOS"]],
["G71.9","Primary disorder of muscle, unspecified","G71",["Myopathy NOS"]],
["G72.0","Drug-induced myopathy","G72",["Drug-induced myopathy","Statin myopathy"]],
["G72.1","Alcoholic myopathy","G72",["Alcoholic myopathy"]],
["G72.2","Myopathy due to other toxic agents","G72",["Toxic myopathy"]],
["G72.3","Periodic paralysis","G72",["Hypokalemic periodic paralysis","Hyperkalemic periodic paralysis"]],
["G72.4","Inflammatory myopathy, unspecified","G72",["Polymyositis","Dermatomyositis"]],
["G72.8","Other specified myopathies","G72",["Myopathy NOS"]],
["G72.9","Myopathy, unspecified","G72",["Myopathy NOS"]],
["G80.0","Spastic diplegic cerebral palsy","G80",["Spastic diplegia","Spastic CP"]],
["G80.1","Spastic quadriplegic cerebral palsy","G80",["Spastic quadriplegia"]],
["G80.2","Spastic hemiplegic cerebral palsy","G80",["Spastic hemiplegia"]],
["G80.3","Dyskinetic cerebral palsy","G80",["Dyskinetic CP","Athetoid CP"]],
["G80.4","Ataxic cerebral palsy","G80",["Ataxic CP"]],
["G80.8","Other cerebral palsy","G80",["Cerebral palsy NOS"]],
["G80.9","Cerebral palsy, unspecified","G80",["Cerebral palsy NOS"]],
["G81.0","Flaccid hemiplegia","G81",["Flaccid hemiplegia"]],
["G81.1","Spastic hemiplegia","G81",["Spastic hemiplegia"]],
["G81.9","Hemiplegia, unspecified","G81",["Hemiplegia NOS","Paralysis of limb"]],
["G82.0","Paraplegia (complete)","G82",["Paraplegia complete","Paralysis of lower extremities"]],
["G82.1","Paraplegia, incomplete","G82",["Paraplegia incomplete"]],
["G82.2","Quadriplegia (complete)","G82",["Quadriplegia complete","Paralysis of all four extremities"]],
["G82.3","Quadriplegia, incomplete","G82",["Quadriplegia incomplete"]],
["G82.4","Paraplegia, unspecified","G82",["Paraplegia NOS"]],
["G82.5","Quadriplegia, unspecified","G82",["Quadriplegia NOS"]],
["G82.A","Paraplegia NOS","G82",["Paraplegia NOS"]],
["G82.B","Paraplegia, unspecified","G82",["Paraplegia NOS"]],
["G83.0","Diplegia of upper limbs","G83",["Upper limb diplegia"]],
["G83.1","Monoplegia of lower limb","G83",["Monoplegia lower extremity"]],
["G83.2","Monoplegia of upper limb","G83",["Monoplegia upper extremity"]],
["G83.3","Monoplegia, unspecified","G83",["Monoplegia NOS"]],
["G83.4","Cauda equina syndrome","G83",["Cauda equina syndrome"]],
["G83.8","Other paralytic syndromes","G83",["Paralytic syndrome NOS"]],
["G83.9","Paralytic syndrome, unspecified","G83",["Paralysis NOS"]],
["G89.0","Central post-stroke pain","G89",["Post-stroke pain"]],
["G89.1","Acute pain due to trauma","G89",["Post-traumatic pain"]],
["G89.2","Chronic pain","G89",["Chronic pain syndrome","CPS"]],
["G89.3","Postprocedural pain","G89",["Post-surgical pain"]],
["G89.4","Chronic pain syndrome","G89",["Chronic pain syndrome NOS"]],
["G89.8","Other pain syndromes","G89",["Pain syndrome NOS"]],
["G89.9","Pain syndrome, unspecified","G89",["Pain NOS"]],
["G90.0","Idiopathic peripheral autonomic neuropathy","G90",["Autonomic neuropathy"]],
["G90.1","Familial dysautonomia [Riley-Day]","G90",["Familial dysautonomia","Riley-Day syndrome"]],
["G90.2","Horner syndrome","G90",["Horner syndrome"]],
["G90.3","Systemic autonomic neuropathy","G90",["Autonomic neuropathy NOS"]],
["G90.4","Autonomic neuropathy due to diabetes","G90",["Diabetic autonomic neuropathy"]],
["G90.8","Other disorders of autonomic nervous system","G90",["Autonomic disorder NOS"]],
["G90.9","Disorder of autonomic nervous system, unspecified","G90",["Autonomic disorder NOS"]],
["G91.0","Communicating hydrocephalus","G91",["Communicating hydrocephalus"]],
["G91.1","Obstructive hydrocephalus","G91",["Obstructive hydrocephalus","Non-communicating hydrocephalus"]],
["G91.2","Normal-pressure hydrocephalus","G91",["NPH","Normal pressure hydrocephalus"]],
["G91.8","Other hydrocephalus","G91",["Hydrocephalus NOS"]],
["G91.9","Hydrocephalus, unspecified","G91",["Hydrocephalus NOS"]],
["G93.0","Cerebral cyst","G93",["Cerebral cyst"]],
["G93.1","Anoxic brain damage, not elsewhere classified","G93",["Anoxic encephalopathy","Hypoxic brain injury"]],
["G93.2","Benign intracranial hypertension","G93",["IIH","Idiopathic intracranial hypertension","Pseudotumor cerebri"]],
["G93.3","Postviral fatigue syndrome","G93",["Chronic fatigue syndrome","CFS"]],
["G93.4","Encephalopathy, unspecified","G93",["Encephalopathy NOS"]],
["G93.5","Compression of brain","G93",["Brain compression"]],
["G93.6","Cerebral edema","G93",["Brain swelling"]],
["G93.7","Reye syndrome","G93",["Reye syndrome"]],
["G93.8","Other specified disorders of brain","G93",["Brain disorder NOS"]],
["G93.9","Disorder of brain, unspecified","G93",["Brain disorder NOS"]],
["G95.0","Syringomyelia and syringobulbia","G95",["Syringomyelia"]],
["G95.1","Vascular disorders of spinal cord","G95",["Spinal cord infarction"]],
["G95.8","Other specified diseases of spinal cord","G95",["Spinal cord disorder NOS"]],
["G95.9","Disease of spinal cord, unspecified","G95",["Spinal cord disorder NOS"]],
["G96.0","Cerebrospinal fluid leak","G96",["CSF leak"]],
["G96.1","Disorders of meninges, not elsewhere classified","G96",["Meninx disorder NOS"]],
["G96.8","Other specified disorders of central nervous system","G96",["CNS disorder NOS"]],
["G96.9","Disorder of central nervous system, unspecified","G96",["CNS disorder NOS"]],
["G97.0","Cerebrospinal fluid leak after lumbar puncture","G97",["Post-LP headache","CSF leak post-LP"]],
["G97.1","Other reaction to lumbar and spinal puncture","G97",["Post-LP reaction"]],
["G97.2","Intracranial hypotension following lumbar puncture","G97",["Post-LP intracranial hypotension"]],
["G97.4","Post-lumbar puncture headache","G97",["Post-LP headache"]],
["G97.8","Other postprocedural disorders of nervous system","G97",["Post-surgical nervous system disorder"]],
["G97.9","Postprocedural disorder of nervous system, unspecified","G97",["Post-procedural nervous system disorder NOS"]],
["G98.0","Other disorders of autonomic nervous system","G98",["Autonomic disorder NOS"]],
["G98.8","Other disorders of nervous system","G98",["Nervous system disorder NOS"]],
["G98.9","Disorder of nervous system, unspecified","G98",["Nervous system disorder NOS"]]
];

allCodes = allCodes.concat(ch5).concat(ch6);

var codeLines = [];
for (var i = 0; i < allCodes.length; i++) {
  var c = allCodes[i];
  var cu = c[3] || [];
  var s = '  codes["' + c[0] + '"] = { code: "' + c[0] + '", description: "' + c[1].replace(/"/g, '\\"') + '", category: "' + c[2] + '", excludes1: [], excludes2: [], includes: [], commonUse: [' + cu.map(function(x){return '"'+x.replace(/"/g,'\\"')+'"';}).join(',') + '], documentation: [] };';
  codeLines.push(s);
}

fs.writeFileSync(path.join(__dirname, 'part_ch5_6.txt'), codeLines.join('\n'), 'utf8');
console.log('Wrote ' + allCodes.length + ' Chapter V+VI entries');
