// Complete generator for icd10-data.js
var fs = require('fs');
var path = require('path');

var out = [];
function w(s) { out.push(s); }

w("'use strict';");
w("var ICD10_DB = (function() {");
w("");

// ===== CHAPTERS =====
w("  var chapters = [");
[
  ["I","Certain infectious and parasitic diseases","A00-B99"],
  ["II","Neoplasms","C00-D49"],
  ["III","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D50-D89"],
  ["IV","Endocrine, nutritional and metabolic diseases","E00-E89"],
  ["V","Mental, Behavioral and Neurodevelopmental disorders","F01-F99"],
  ["VI","Diseases of the nervous system","G00-G99"],
  ["VII","Diseases of the eye and adnexa","H00-H59"],
  ["VIII","Diseases of the ear and mastoid process","H60-H95"],
  ["IX","Diseases of the circulatory system","I00-I99"],
  ["X","Diseases of the respiratory system","J00-J99"],
  ["XI","Diseases of the digestive system","K00-K93"],
  ["XII","Diseases of the skin and subcutaneous tissue","L00-L99"],
  ["XIII","Diseases of the musculoskeletal system and connective tissue","M00-M99"],
  ["XIV","Diseases of the genitourinary system","N00-N99"],
  ["XV","Pregnancy, childbirth and the puerperium","O00-O9A"],
  ["XVI","Certain conditions originating in the perinatal period","P00-P96"],
  ["XVII","Congenital malformations, deformations and chromosomal abnormalities","Q00-Q99"],
  ["XVIII","Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified","R00-R99"],
  ["XIX","Injury, poisoning and certain other consequences of external causes","S00-T88"],
  ["XX","External causes of morbidity","V00-Y99"],
  ["XXI","Factors influencing health status and contact with health services","Z00-Z99"]
].forEach(function(c) {
  w('    { code: "' + c[0] + '", name: "' + c[1] + '", range: "' + c[2] + '" },');
});
w("  ];");
w("");

// ===== CODES - Using compact array format =====
// Format: [code, description, category, excludes1, excludes2, includes, commonUse, documentation]
// We'll generate thousands of codes covering all chapters

w("  var codes = {};");

// Helper to emit a code entry
function emitCode(c, d, cat, ex1, ex2, inc, use, doc) {
  var e1 = JSON.stringify(ex1 || []);
  var e2 = JSON.stringify(ex2 || []);
  var ic = JSON.stringify(inc || []);
  var u = JSON.stringify(use || []);
  var dc = JSON.stringify(doc || []);
  w('  codes["' + c + '"] = { code: "' + c + '", description: "' + d.replace(/"/g, '\\"') + '", category: "' + cat + '", excludes1: ' + e1 + ', excludes2: ' + e2 + ', includes: ' + ic + ', commonUse: ' + u + ', documentation: ' + dc + ' };');
}

// ===== CHAPTER I: INFECTIOUS DISEASES =====
var ch1 = [
  ["A00.0","Cholera due to Vibrio cholerae 01, biovar cholerae","A00",[],[],[],["Traveler diarrhea from cholera"],["Stool culture"]],
  ["A00.1","Cholera due to Vibrio cholerae 01, biovar eltor","A00",[],[],[],["Cholera eltor strain"],["Stool culture"]],
  ["A00.9","Cholera, unspecified","A00",[],[],[],["Cholera NOS"],["Clinical diagnosis"]],
  ["A01.0","Typhoid fever","A01",[],[],[],["Typhoid fever"],["Blood culture, stool culture"]],
  ["A01.1","Paratyphoid fever A","A01",[],[],[],["Paratyphoid A"],["Blood culture"]],
  ["A01.2","Paratyphoid fever B","A01",[],[],[],["Paratyphoid B"],["Blood culture"]],
  ["A01.3","Paratyphoid fever C","A01",[],[],[],["Paratyphoid C"],["Blood culture"]],
  ["A01.4","Paratyphoid fever, unspecified","A01",[],[],[],["Paratyphoid NOS"],["Blood culture"]],
  ["A02.0","Salmonella gastroenteritis","A02",[],[],[],["Salmonella food poisoning"],["Stool culture"]],
  ["A02.1","Salmonella septicemia","A02",[],[],[],["Salmonella bloodstream infection"],["Blood culture"]],
  ["A02.2","Localized salmonella infections","A02",[],[],[],["Salmonella osteomyelitis","Salmonella meningitis"],["Culture of infected site"]],
  ["A02.9","Salmonella infection, unspecified","A02",[],[],[],["Salmonellosis NOS"],["Stool culture"]],
  ["A04.0","Escherichia coli infections","A04",[],[],[],["E. coli infection"],["Stool culture"]],
  ["A04.1","Escherichia coli gastroenteritis","A04",[],[],[],["E. coli diarrhea"],["Stool culture"]],
  ["A04.2","Enteropathogenic Escherichia coli infections","A04",[],[],[],["Enteropathogenic E. coli"],["Stool culture"]],
  ["A04.3","Enterotoxigenic Escherichia coli infections","A04",[],[],[],["Traveler diarrhea from ETEC"],["Stool culture"]],
  ["A04.4","Enteroinvasive Escherichia coli infections","A04",[],[],[],["Enteroinvasive E. coli"],["Stool culture"]],
  ["A04.5","Campylobacter enteritis","A04",[],[],[],["Campylobacter gastroenteritis"],["Stool culture"]],
  ["A04.6","Enteritis due to other specified bacteria","A04",[],[],[],["Bacterial enteritis"],["Stool culture"]],
  ["A04.7","Enterocolitis due to Clostridium difficile","A04",["B95-B96 if applicable"],[""],["Clostridium difficile infection","C. diff colitis"],["Stool C. diff toxin","GDH assay"]],
  ["A04.8","Other specified bacterial intestinal infections","A04",[],[],[],["Other bacterial enteritis"],["Stool culture"]],
  ["A04.9","Bacterial intestinal infection, unspecified","A04",[],[],[],["Bacterial gastroenteritis NOS"],["Stool culture"]],
  ["A05.0","Foodborne staphylococcal intoxication","A05",[],[],[],["Staph food poisoning"],["Stool enterotoxin assay"]],
  ["A05.1","Clostridium perfringens food intoxication","A05",[],[],[],["C. perfringens food poisoning"],["Stool assay"]],
  ["A05.2","Foodborne Clostridium botulinum intoxication","A05",[],[],[],["Botulism from food"],["Toxin assay, culture"]],
  ["A05.3","Vibrio parahaemolyticus food poisoning","A05",[],[],[],["V. parahaemolyticus food poisoning"],["Stool culture"]],
  ["A05.4","Bacillus cereus food poisoning","A05",[],[],[],["B. cereus food poisoning"],["Stool assay"]],
  ["A05.9","Bacterial food poisoning, unspecified","A05",[],[],[],["Bacterial food poisoning NOS"],["Stool culture"]],
  ["A06.0","Acute amebic dysentery","A06",[],[],[],["Amebic dysentery"],["Stool O&P exam"]],
  ["A06.1","Chronic amebic dysentery","A06",[],[],[],["Chronic amebic dysentery"],["Stool O&P exam"]],
  ["A06.2","Amebic nondysenteric colitis","A06",[],[],[],["Amebic colitis"],["Stool O&P exam"]],
  ["A06.3","Amebic cyst carrier","A06",[],[],[],["Amebic carrier"],["Stool O&P exam"]],
  ["A06.7","Cutaneous amebiasis","A06",[],[],[],["Skin amebiasis"],["Skin biopsy, culture"]],
  ["A06.8","Amebic infection of other sites","A06",[],[],[],["Amebic liver abscess"],["Serology, imaging"]],
  ["A06.9","Amebosis, unspecified","A06",[],[],[],["Amebiasis NOS"],["Stool O&P exam"]],
  ["A07.0","Balantidiasis","A07",[],[],[],["Balantidium coli infection"],["Stool O&P exam"]],
  ["A07.1","Giardiasis [lambliasis]","A07",[],[],[],["Giardia infection","Beaver fever"],["Stool O&P exam","Giardia antigen test"]],
  ["A07.2","Cryptosporidiosis","A07",[],[],[],["Cryptosporidium infection"],["Stool O&P exam","Acid-fast stain"]],
  ["A07.3","Isosporiasis","A07",[],[],[],["Isospora belli infection"],["Stool O&P exam"]],
  ["A07.8","Other specified protozoal intestinal diseases","A07",[],[],[],["Other protozoal enteritis"],["Stool O&P exam"]],
  ["A07.9","Protozoal intestinal disease, unspecified","A07",[],[],[],["Protozoal enteritis NOS"],["Stool O&P exam"]],
  ["A09","Infectious gastroenteritis and colitis, unspecified","A09",["A00-B34 if applicable"],[""],[],["Gastroenteritis","Stomach flu","Stomach bug","Food poisoning"],["Clinical diagnosis","Stool studies if warranted"]],
  ["A15.0","Tuberculosis of respiratory system","A15",[],[],[],["Pulmonary TB","Lung TB"],["Chest X-ray","Sputum AFB smear and culture"]],
  ["A15.4","Tuberculosis of intrathoracic lymph nodes","A15",[],[],[],["TB lymphadenitis"],["Chest X-ray","Biopsy"]],
  ["A15.5","Tuberculosis of larynx, trachea and bronchus","A15",[],[],[],["TB laryngitis"],["Laryngoscopy","Sputum AFB"]],
  ["A15.6","Tuberculous pleurisy","A15",[],[],[],["TB pleurisy"],["Pleural fluid analysis","Chest X-ray"]],
  ["A15.7","Primary respiratory tuberculosis","A15",[],[],[],["Primary pulmonary TB"],["Chest X-ray","Sputum AFB"]],
  ["A15.8","Other respiratory tuberculosis","A15",[],[],[],["Other pulmonary TB"],["Chest X-ray","Sputum AFB"]],
  ["A15.9","Respiratory tuberculosis unspecified","A15",[],[],[],["Pulmonary TB NOS"],["Chest X-ray","Sputum AFB"]],
  ["A17.0","Tuberculous meningitis","A17",[],[],[],["TB meningitis"],["LP with CSF analysis","Brain imaging"]],
  ["A17.1","Tuberculoma of meninges","A17",[],[],[],["TB meningeal tuberculoma"],["Brain imaging","LP"]],
  ["A17.8","Other tuberculosis of nervous system","A17",[],[],[],["TB encephalitis"],["Brain imaging","LP"]],
  ["A18.0","Tuberculosis of bones and joints","A18",[],[],[],["Pott disease","TB arthritis"],["X-ray","Joint fluid culture","Biopsy"]],
  ["A18.1","Tuberculosis of genitourinary system","A18",[],[],[],["TB nephritis","TB orchitis"],["Urine AFB culture","Imaging"]],
  ["A18.2","Tuberculous peripheral lymphadenopathy","A18",[],[],[],["TB lymphadenitis"],["Lymph node biopsy","AFB stain"]],
  ["A18.3","Tuberculosis of intestines, peritoneum and mesenteric glands","A18",[],[],[],["TB peritonitis","TB enteritis"],["Laparoscopy","Biopsy"]],
  ["A18.4","Tuberculosis of skin and subcutaneous tissue","A18",[],[],[],["Lupus vulgaris","Scrofuloderma"],["Skin biopsy"]],
  ["A18.5","Tuberculosis of eye","A18",[],[],[],["TB uveitis","TB conjunctivitis"],["Ophthalmologic exam"]],
  ["A18.6","Tuberculosis of ear","A18",[],[],[],["TB otitis media"],["Ear examination"]],
  ["A18.7","Tuberculosis of adrenal glands","A18",[],[],[],["TB Addison disease"],["Serology","Imaging"]],
  ["A18.8","Tuberculosis of other specified organs","A18",[],[],[],["TB of other organs"],["Site-specific studies"]],
  ["A18.9","Tuberculosis, unspecified","A18",[],[],[],["TB NOS"],["TB testing","Imaging"]],
  ["A19.0","Acute miliary tuberculosis","A19",[],[],[],["Miliary TB"],["Chest X-ray","Sputum AFB","Blood cultures"]],
  ["A19.1","Acute disseminated tuberculosis","A19",[],[],[],["Disseminated TB"],["Blood cultures","Imaging"]],
  ["A19.2","Tuberculosis of other multiple specified sites","A19",[],[],[],["Multisite TB"],["Site-specific studies"]],
  ["A19.8","Other miliary tuberculosis","A19",[],[],[],["Other miliary TB"],["Imaging","AFB cultures"]],
  ["A19.9","Miliary tuberculosis, unspecified","A19",[],[],[],["Miliary TB NOS"],["Imaging","AFB cultures"]],
  ["A20.0","Bubonic plague","A20",[],[],[],["Bubonic plague"],["Yersinia culture","Flea bite history"]],
  ["A20.1","Celulocutaneous plague","A20",[],[],[],["Plague cellulitis"],["Yersinia culture"]],
  ["A20.2","Pneumonic plague","A20",[],[],[],["Plague pneumonia"],["Sputum culture","Chest X-ray"]],
  ["A20.3","Plague meningitis","A20",[],[],[],["Plague meningitis"],["LP","Yersinia culture"]],
  ["A20.7","Septicemic plague","A20",[],[],[],["Plague septicemia"],["Blood culture"]],
  ["A20.8","Other forms of plague","A20",[],[],[],["Other plague presentations"],["Yersinia culture"]],
  ["A20.9","Plague, unspecified","A20",[],[],[],["Plague NOS"],["Yersinia culture"]],
  ["A21.0","Glanders","A21",[],[],[],["Glanders"],["Burkholderia mallei culture"]],
  ["A21.1","Cutaneous glanders","A21",[],[],[],["Cutaneous glanders"],["Culture"]],
  ["A21.2","Pulmonary glanders","A21",[],[],[],["Pulmonary glanders"],["Culture","Chest X-ray"]],
  ["A21.3","Glanders of other sites","A21",[],[],[],["Other glanders"],["Culture"]],
  ["A21.7","Glanders, unspecified","A21",[],[],[],["Glanders NOS"],["Culture"]],
  ["A21.8","Other forms of glanders","A21",[],[],[],["Other glanders forms"],["Culture"]],
  ["A21.9","Glanders, unspecified","A21",[],[],[],["Glanders NOS"],["Culture"]],
  ["A22.0","Cutaneous anthrax","A22",[],[],[],["Anthrax skin lesion","Wool-sorter disease"],["Bacillus culture"]],
  ["A22.1","Pulmonary anthrax","A22",[],[],[],["Inhalation anthrax","Woolsorter disease"],["Chest X-ray","Bacillus culture"]],
  ["A22.2","Gastrointestinal anthrax","A22",[],[],[],["Anthrax GI infection"],["Stool culture","Bacillus culture"]],
  ["A22.7","Anthrax septicemia","A22",[],[],[],["Anthrax sepsis"],["Blood culture"]],
  ["A22.8","Other forms of anthrax","A22",[],[],[],["Other anthrax"],["Culture"]],
  ["A22.9","Anthrax, unspecified","A22",[],[],[],["Anthrax NOS"],["Culture"]],
  ["A23.0","Brucellosis due to Brucella melitensis","A23",[],[],[],["Brucellosis melitensis"],["Brucella serology","Blood culture"]],
  ["A23.1","Brucellosis due to Brucella abortus","A23",[],[],[],["Brucellosis abortus"],["Brucella serology","Blood culture"]],
  ["A23.2","Brucellosis due to Brucella suis","A23",[],[],[],["Brucellosis suis"],["Brucella serology","Blood culture"]],
  ["A23.3","Brucellosis due to Brucella canis","A23",[],[],[],["Brucellosis canis"],["Brucella serology","Blood culture"]],
  ["A23.8","Other brucellosis","A23",[],[],[],["Other brucellosis"],["Brucella serology","Blood culture"]],
  ["A23.9","Brucellosis, unspecified","A23",[],[],[],["Brucellosis NOS"],["Brucella serology","Blood culture"]],
  ["A24.0","Glanders and melioidosis","A24",[],[],[],["Melioidosis"],["Burkholderia culture"]],
  ["A24.1","Acute and fulminating melioidosis","A24",[],[],[],["Acute melioidosis"],["Culture","Blood culture"]],
  ["A24.2","Subacute and chronic melioidosis","A24",[],[],[],["Chronic melioidosis"],["Culture"]],
  ["A24.3","Other melioidosis","A24",[],[],[],["Other melioidosis"],["Culture"]],
  ["A24.4","Melioidosis, unspecified","A24",[],[],[],["Melioidosis NOS"],["Culture"]],
  ["A25.0","Rat-bite fever due to Spirillum minus","A25",[],[],[],["Sodoku"],["Blood smear","Culture"]],
  ["A25.1","Rat-bite fever due to Streptobacillus moniliformis","A25",[],[],[],["Rat-bite fever"],["Blood culture","Serology"]],
  ["A25.7","Other rat-bite fever","A25",[],[],[],["Other rat-bite fever"],["Culture"]],
  ["A25.9","Rat-bite fever, unspecified","A25",[],[],[],["Rat-bite fever NOS"],["Culture"]],
  ["A26.0","Erysipeloid cutaneous","A26",[],[],[],["Erysipeloid"],["Culture from skin lesion"]],
  ["A26.1","Erysipelothrix septicemia","A26",[],[],[],["Erysipelothrix sepsis"],["Blood culture"]],
  ["A26.2","Erysipelothrix endocarditis","A26",[],[],[],["Erysipelothrix endocarditis"],["Blood culture","Echocardiography"]],
  ["A26.3","Erysipelothrix infections of other sites","A26",[],[],[],["Other Erysipelothrix infections"],["Culture"]],
  ["A26.7","Erysipelothrix septicemia","A26",[],[],[],["Erysipelothrix sepsis"],["Blood culture"]],
  ["A26.8","Erysipelothrix infections of other sites","A26",[],[],[],["Other Erysipelothrix"],["Culture"]],
  ["A26.9","Erysipelothrix infection, unspecified","A26",[],[],[],["Erysipelothrix NOS"],["Culture"]],
  ["A27.0","Leptospirosis icterohemorrhagica","A27",[],[],[],["Weil disease"],["Leptospira serology","Blood culture"]],
  ["A27.1","Leptospirosis canicola","A27",[],[],[],["Canicola fever"],["Leptospira serology"]],
  ["A27.2","Leptospirosis autumnalis","A27",[],[],[],["Autumnal fever"],["Leptospira serology"]],
  ["A27.3","Leptospirosis grippotyphosa","A27",[],[],[],["Grippotyphosa"],["Leptospira serology"]],
  ["A27.4","Leptospirosis, unspecified","A27",[],[],[],["Leptospirosis NOS"],["Leptospira serology"]],
  ["A27.8","Other leptospirosis","A27",[],[],[],["Other leptospirosis"],["Leptospira serology"]],
  ["A27.9","Leptospirosis, unspecified","A27",[],[],[],["Leptospirosis NOS"],["Leptospira serology"]],
  ["A28.0","Pasteurellosis","A28",[],[],[],["Pasteurella infection"],["Culture"]],
  ["A28.1","Cat-scratch disease","A28",[],[],[],["Cat scratch fever","Bartonella infection"],["Bartonella serology","Lymph node biopsy"]],
  ["A28.2","Lymphocytic choriomeningitis","A28",[],[],[],["LCMV infection"],["Serology","CSF analysis"]],
  ["A28.8","Other specified zoonotic bacterial diseases, not elsewhere classified","A28",[],[],[],["Other zoonotic bacterial infections"],["Culture","Serology"]],
  ["A28.9","Zoonotic bacterial disease, unspecified","A28",[],[],[],["Zoonotic infection NOS"],["Culture","Serology"]],
  ["A30.0","Indeterminate leprosy","A30",[],[],[],["Indeterminate leprosy"],["Skin slit smear","Biopsy"]],
  ["A30.1","Tuberculoid leprosy","A30",[],[],[],["Tuberculoid leprosy"],["Skin slit smear","Biopsy"]],
  ["A30.2","Borderline tuberculoid leprosy","A30",[],[],[],["Borderline tuberculoid"],["Skin slit smear","Biopsy"]],
  ["A30.3","Borderline leprosy","A30",[],[],[],["Borderline leprosy"],["Skin slit smear","Biopsy"]],
  ["A30.4","Borderline lepromatous leprosy","A30",[],[],[],["Borderline lepromatous"],["Skin slit smear","Biopsy"]],
  ["A30.5","Lepromatous leprosy","A30",[],[],[],["Lepromatous leprosy"],["Skin slit smear","Biopsy"]],
  ["A30.8","Other forms of leprosy","A30",[],[],[],["Other leprosy"],["Skin slit smear","Biopsy"]],
  ["A30.9","Leprosy, unspecified","A30",[],[],[],["Leprosy NOS"],["Skin slit smear","Biopsy"]],
  ["A31.0","Mycobacterium avium-intracellulare infection","A31",[],[],[],["NTM pulmonary infection"],["Sputum culture","Chest CT"]],
  ["A31.1","Cutaneous mycobacterium avium-intracellulare infection","A31",[],[],[],["Cutaneous NTM"],["Culture","Biopsy"]],
  ["A31.2","Disseminated mycobacterium avium-intracellulare infection","A31",[],[],[],["Disseminated MAC"],["Blood culture","Bone marrow biopsy"]],
  ["A31.3","Mycobacterium kansasii infection","A31",[],[],[],["M. kansasii pulmonary"],["Sputum culture"]],
  ["A31.8","Other mycobacterial infections","A31",[],[],[],["Other NTM infections"],["Culture"]],
  ["A31.9","Mycobacterial infection, unspecified","A31",[],[],[],["NTM NOS"],["Culture"]],
  ["A32.0","Cutaneous listeriosis","A32",[],[],[],["Listeria skin infection"],["Culture"]],
  ["A32.1","Listeria meningitis","A32",[],[],[],["Listeria meningitis"],["LP","CSF culture"]],
  ["A32.7","Listerial septicemia","A32",[],[],[],["Listeria sepsis"],["Blood culture"]],
  ["A32.8","Other listeriosis","A32",[],[],[],["Other listeriosis"],["Culture"]],
  ["A32.9","Listeriosis, unspecified","A32",[],[],[],["Listeriosis NOS"],["Culture"]],
  ["A33","Tetanus neonatorum","A33",[],[],[],["Neonatal tetanus"],["Clinical diagnosis"]],
  ["A34","Obstetrical tetanus","A34",[],[],[],["Tetanus in pregnancy"],["Clinical diagnosis"]],
  ["A35","Other tetanus","A35",[],[],[],["Tetanus"],["Clinical diagnosis","Wound culture"]],
  ["A36.0","Diphtheria of pharynx","A36",[],[],[],["Pharyngeal diphtheria"],["Throat culture","Toxin testing"]],
  ["A36.1","Diphtheria of larynx","A36",[],[],[],["Laryngeal diphtheria"],["Throat culture"]],
  ["A36.2","Diphtheria of nasopharynx","A36",[],[],[],["Nasopharyngeal diphtheria"],["Throat culture"]],
  ["A36.3","Diphtheria of skin","A36",[],[],[],["Cutaneous diphtheria"],["Wound culture"]],
  ["A36.8","Other diphtheria","A36",[],[],[],["Other diphtheria"],["Culture"]],
  ["A36.9","Diphtheria, unspecified","A36",[],[],[],["Diphtheria NOS"],["Throat culture"]],
  ["A37.0","Whooping cough due to Bordetella pertussis","A37",[],[],[],["Pertussis","Whooping cough"],["Nasopharyngeal swab PCR","Serology"]],
  ["A37.1","Whooping cough due to Bordetella parapertussis","A37",[],[],[],["Parapertussis"],["Nasopharyngeal swab PCR"]],
  ["A37.8","Whooping cough due to other Bordetella species","A37",[],[],[],["Other pertussis"],["Nasopharyngeal swab PCR"]],
  ["A37.9","Whooping cough, unspecified","A37",[],[],[],["Pertussis NOS"],["Nasopharyngeal swab PCR"]],
  ["A38","Scarlet fever","A38",[],[],[],["Scarlet fever","Scarlatina"],["Throat culture","ASO titer"]],
  ["A39.0","Meningococcal meningitis","A39",[],[],[],["Meningococcal meningitis"],["LP","CSF culture","Blood culture"]],
  ["A39.1","Waterhouse-Friderichsen syndrome","A39",[],[],[],["Meningococcemia adrenal hemorrhage"],["Blood culture","ACTH level"]],
  ["A39.2","Meningococcal meningitis with meningoencephalitis","A39",[],[],[],["Meningococcal meningoencephalitis"],["LP","CSF culture"]],
  ["A39.3","Meningococcal meningitis with other localizations","A39",[],[],[],["Meningococcal infection with localizations"],["Culture","Serology"]],
  ["A39.4","Meningococcal meningitis, unspecified","A39",[],[],[],["Meningococcal meningitis NOS"],["LP","CSF culture"]],
  ["A39.5","Meningococcal meningitis without mention of meningitis","A39",[],[],[],["Meningococcemia"],["Blood culture"]],
  ["A39.8","Other meningococcal infections","A39",[],[],[],["Other meningococcal"],["Culture"]],
  ["A39.9","Meningococcal infection, unspecified","A39",[],[],[],["Meningococcal NOS"],["Blood culture"]],
  ["A40.0","Streptococcal septicemia due to streptococcus, group A","A40",[],[],[],["Group A strep sepsis"],["Blood culture"]],
  ["A40.1","Streptococcal septicemia due to streptococcus, group B","A40",[],[],[],["Group B strep sepsis","GBS sepsis"],["Blood culture"]],
  ["A40.2","Streptococcal septicemia due to streptococcus, group D and enterococcus","A40",[],[],[],["Enterococcal sepsis"],["Blood culture"]],
  ["A40.3","Streptococcal septicemia due to Streptococcus pneumoniae","A40",[],[],[],["Pneumococcal sepsis"],["Blood culture"]],
  ["A40.8","Other streptococcal septicemia","A40",[],[],[],["Other strep sepsis"],["Blood culture"]],
  ["A40.9","Streptococcal septicemia, unspecified","A40",[],[],[],["Strep sepsis NOS"],["Blood culture"]],
  ["A41.0","Staphylococcal septicemia due to Staphylococcus aureus","A41",[],[],[],["Staph aureus sepsis","MRSA sepsis"],["Blood culture"]],
  ["A41.1","Staphylococcal septicemia due to other specified staphylococcus","A41",[],[],[],["Other staph sepsis"],["Blood culture"]],
  ["A41.2","Staphylococcal septicemia, unspecified","A41",[],[],[],["Staph sepsis NOS"],["Blood culture"]],
  ["A41.3","Staphylococcal septicemia due to group D streptococcus","A41",[],[],[],["Strep D sepsis"],["Blood culture"]],
  ["A41.4","Staphylococcal septicemia due to anaerobes","A41",[],[],[],["Anaerobic staph sepsis"],["Blood culture"]],
  ["A41.5","Staphylococcal septicemia due to Gram-negative organisms","A41",[],[],[],["Gram-negative staph sepsis"],["Blood culture"]],
  ["A41.8","Other staphylococcal septicemia","A41",[],[],[],["Other staph sepsis"],["Blood culture"]],
  ["A41.9","Staphylococcal septicemia, unspecified","A41",[],[],[],["Staph sepsis NOS"],["Blood culture"]],
  ["A48.0","Gas gangrene","A48",[],[],[],["Gas gangrene","Clostridial myonecrosis"],["Wound culture","X-ray for gas"]],
  ["A48.1","Legionnaires disease","A48",[],[],[],["Legionella pneumonia"],["Urine Legionella antigen","Sputum culture","Chest X-ray"]],
  ["A48.2","Nonpneumonic Legionnaires disease [Pontiac fever]","A48",[],[],[],["Pontiac fever"],["Serology"]],
  ["A48.3","Toxic shock syndrome","A48",[],[],[],["TSS"],["Blood culture","Toxin assay"]],
  ["A48.4","Brazilian purpuric fever","A48",[],[],[],["Brazilian purpuric fever"],["Blood culture"]],
  ["A48.5","Other specified Gram-negative bacterial diseases","A48",[],[],[],["Other Gram-negative infections"],["Culture"]],
  ["A49.0","Streptococcal infection, unspecified site","A49",[],[],[],["Strep infection NOS"],["Culture"]],
  ["A49.1","Staphylococcal infection, unspecified site","A49",[],[],[],["Staph infection NOS"],["Culture"]],
  ["A49.2","Hemophilus influenzae infection, unspecified site","A49",[],[],[],["H. influenzae NOS"],["Culture"]],
  ["A49.3","Mycoplasma infection, unspecified site","A49",[],[],[],["Mycoplasma NOS"],["Serology","PCR"]],
  ["A49.8","Other bacterial infections of unspecified site","A49",[],[],[],["Other bacterial NOS"],["Culture"]],
  ["A49.9","Bacterial infection, unspecified","A49",[],[],[],["Bacterial infection NOS"],["Culture"]],
  ["A50.0","Early congenital syphilis, symptomatic","A50",[],[],[],["Congenital syphilis early"],["VDRL","Darkfield exam"]],
  ["A50.1","Early congenital syphilis, latent","A50",[],[],[],["Early latent congenital syphilis"],["VDRL","Serology"]],
  ["A50.2","Early congenital syphilis, unspecified","A50",[],[],[],["Early congenital syphilis NOS"],["Serology"]],
  ["A50.3","Late congenital syphilitic oculopathy","A50",[],[],[],["Congenital syphilitic eye disease"],["Ophthalmologic exam","Serology"]],
  ["A50.4","Late congenital neurosyphilis","A50",[],[],[],["Congenital neurosyphilis"],["LP","Serology"]],
  ["A50.5","Late congenital syphilis, other late symptomatic","A50",[],[],[],["Late congenital syphilis"],["Serology"]],
  ["A50.6","Late congenital syphilis, latent","A50",[],[],[],["Late latent congenital"],["Serology"]],
  ["A50.7","Late congenital syphilis, unspecified","A50",[],[],[],["Late congenital NOS"],["Serology"]],
  ["A50.9","Congenital syphilis, unspecified","A50",[],[],[],["Congenital syphilis NOS"],["Serology"]],
  ["A51.0","Primary genital syphilis","A51",[],[],[],["Primary syphilis chancre"],["Darkfield exam","VDRL","RPR"]],
  ["A51.1","Primary anal syphilis","A51",[],[],[],["Anal chancre"],["Darkfield exam","VDRL"]],
  ["A51.2","Primary syphilis of other sites","A51",[],[],[],["Other primary syphilis"],["Darkfield exam","VDRL"]],
  ["A51.3","Secondary syphilis of skin and mucous membranes","A51",[],[],[],["Secondary syphilis rash"],["VDRL","RPR","Darkfield exam"]],
  ["A51.4","Secondary syphilis of other sites","A51",[],[],[],["Secondary syphilis systemic"],["VDRL","RPR"]],
  ["A51.5","Early latent syphilis","A51",[],[],[],["Early latent syphilis"],["VDRL","RPR","FTA-ABS"]],
  ["A51.9","Early syphilis, unspecified","A51",[],[],[],["Early syphilis NOS"],["VDRL","RPR"]],
  ["A52.0","Cardiovascular syphilis","A52",[],[],[],["Syphilitic aortitis","Syphilitic aortic aneurysm"],["Serology","Echocardiography","CT"]],
  ["A52.1","Neurosyphilis, symptomatic","A52",[],[],[],["Neurosyphilis"],["LP","CSF VDRL","Serology"]],
  ["A52.2","Asymptomatic neurosyphilis","A52",[],[],[],["Asymptomatic neurosyphilis"],["LP","CSF VDRL"]],
  ["A52.3","Neurosyphilis, unspecified","A52",[],[],[],["Neurosyphilis NOS"],["LP","CSF VDRL"]],
  ["A52.7","Other late symptomatic syphilis","A52",[],[],[],["Late syphilis other"],["Serology","Site-specific studies"]],
  ["A52.8","Late syphilis, unspecified","A52",[],[],[],["Late syphilis NOS"],["Serology"]],
  ["A52.9","Syphilis, unspecified","A52",[],[],[],["Syphilis NOS"],["VDRL","RPR","FTA-ABS"]],
  ["A53.0","Latent syphilis, unspecified as early or late","A53",[],[],[],["Latent syphilis NOS"],["VDRL","RPR"]],
  ["A53.9","Syphilis, unspecified","A53",[],[],[],["Syphilis NOS"],["VDRL","RPR","FTA-ABS"]],
  ["A54.0","Gonococcal infection of lower genitourinary tract without abscess","A54",[],[],[],["Gonorrhea"],["Urethral/cervical culture","NAAT"]],
  ["A54.1","Gonococcal infection of lower genitourinary tract with periurethral and accessory gland abscess","A54",[],[],[],["Gonorrhea with abscess"],["Culture"]],
  ["A54.2","Gonococcal infection of upper genitourinary tract","A54",[],[],[],["Gonococcal PID","Gonococcal epididymitis"],["Cervical/urethral culture","NAAT"]],
  ["A54.3","Gonococcal infection of eye","A54",[],[],[],["Gonococcal conjunctivitis"],["Eye culture"]],
  ["A54.4","Gonococcal infection of musculoskeletal system","A54",[],[],[],["Gonococcal arthritis"],["Synovial fluid culture","NAAT"]],
  ["A54.5","Gonococcal pharyngitis","A54",[],[],[],["Gonococcal sore throat"],["Throat culture"]],
  ["A54.6","Gonococcal infection of anus and rectum","A54",[],[],[],["Gonococcal proctitis"],["Rectal culture"]],
  ["A54.8","Other gonococcal infections","A54",[],[],[],["Other gonococcal"],["Culture"]],
  ["A54.9","Gonococcal infection, unspecified","A54",[],[],[],["Gonorrhea NOS"],["Culture","NAAT"]],
  ["A55","Lymphogranuloma venereum due to Chlamydia trachomatis","A55",[],[],[],["LGV"],["Chlamydia serology","Swab culture"]],
  ["A56.0","Chlamydial infection of lower genitourinary tract","A56",[],[],[],["Chlamydia trachomatis infection"],["Urethral/cervical NAAT"]],
  ["A56.1","Chlamydial infection of upper genitourinary tract","A56",[],[],[],["Chlamydial PID"],["Cervical NAAT"]],
  ["A56.2","Chlamydial infection of anus and rectum","A56",[],[],[],["Chlamydial proctitis"],["Rectal NAAT"]],
  ["A56.3","Chlamydial infection of pharynx","A56",[],[],[],["Chlamydial pharyngitis"],["Throat swab NAAT"]],
  ["A56.4","Chlamydial infection of conjunctiva","A56",[],[],[],["Chlamydial conjunctivitis"],["Eye swab"]],
  ["A56.8","Chlamydial infection of other sites","A56",[],[],[],["Other chlamydial infections"],["NAAT"]],
  ["A56.9","Chlamydial infection, unspecified","A56",[],[],[],["Chlamydia NOS"],["NAAT"]],
  ["A57","Chancroid","A57",[],[],[],["Chancroid","Ducreyi ulcer"],["Culture","PCR"]],
  ["A58","Granuloma inguinale","A58",[],[],[],["Donovanosis"],["Biopsy","Donovan bodies on smear"]],
  ["A59.0","Urogenital trichomoniasis","A59",[],[],[],["Trichomoniasis"],["Wet mount","NAAT"]],
  ["A59.1","Trichomoniasis of other sites","A59",[],[],[],["Other trichomoniasis"],["Wet mount"]],
  ["A59.8","Trichomoniasis of other sites","A59",[],[],[],["Other trichomoniasis"],["Culture"]],
  ["A59.9","Trichomoniasis, unspecified","A59",[],[],[],["Trichomoniasis NOS"],["Wet mount"]],
  ["A60.0","Herpesviral infection of genitalia and urogenital tract","A60",[],[],[],["Genital herpes"],["Viral culture","PCR","DFA"]],
  ["A60.1","Herpesviral infection of perianal skin and rectum","A60",[],[],[],["Perianal herpes"],["Viral culture","PCR"]],
  ["A60.9","Herpesviral infection of unspecified site","A60",[],[],[],["Herpes simplex NOS"],["Viral culture","PCR"]],
  ["A63.0","Anogenital (venereal) warts","A63",[],[],[],["Genital warts","HPV warts"],["Visual examination","Biopsy"]],
  ["A63.8","Other specified sexually transmitted diseases","A63",[],[],[],["Other STDs"],["Culture","Serology"]],
  ["A64","Unspecified sexually transmitted disease","A64",[],[],[],["STD NOS"],["Culture","Serology"]],
  ["A65","Nonvenereal syphilis","A65",[],[],[],["Bejel","Endemic syphilis"],["Serology","Darkfield exam"]],
  ["A66.0","Initial lesions of yaws","A66",[],[],[],["Yaws initial lesion"],["Serology","Darkfield exam"]],
  ["A66.1","Multiple papillomata and wet crab yaws","A66",[],[],[],["Yaws papillomata"],["Serology"]],
  ["A66.2","Other early skin lesions of yaws","A66",[],[],[],["Yaws early skin"],["Serology"]],
  ["A66.3","Hyperkeratosis of yaws","A66",[],[],[],["Ghoul hand","Ghoul foot"],["Serology"]],
  ["A66.4","Gummatous ulceration of yaws","A66",[],[],[],["Yaws gumma"],["Serology"]],
  ["A66.5","Gangosa","A66",[],[],[],["Gangosa"],["Serology"]],
  ["A66.6","Bone and joint lesions of yaws","A66",[],[],[],["Yaws bone lesions"],["X-ray","Serology"]],
  ["A66.7","Other manifestations of yaws","A66",[],[],[],["Other yaws"],["Serology"]],
  ["A66.8","Latent yaws","A66",[],[],[],["Latent yaws"],["Serology"]],
  ["A66.9","Yaws, unspecified","A66",[],[],[],["Yaws NOS"],["Serology"]],
  ["A67.0","Primary lesions of pinta","A67",[],[],[],["Pinta primary lesion"],["Serology"]],
  ["A67.1","Intermediate lesions of pinta","A67",[],[],[],["Pinta intermediate"],["Serology"]],
  ["A67.2","Late lesions of pinta","A67",[],[],[],["Pinta late"],["Serology"]],
  ["A67.3","Mixed lesions of pinta","A67",[],[],[],["Pinta mixed"],["Serology"]],
  ["A67.9","Pinta, unspecified","A67",[],[],[],["Pinta NOS"],["Serology"]],
  ["A68.0","Relapsing fever due to Borrelia recurrentis","A68",[],[],[],["Epidemic relapsing fever"],["Blood smear"]],
  ["A68.1","Other relapsing fevers","A68",[],[],[],["Endemic relapsing fever"],["Blood smear"]],
  ["A68.8","Relapsing fever, unspecified","A68",[],[],[],["Relapsing fever NOS"],["Blood smear"]],
  ["A68.9","Relapsing fever, unspecified","A68",[],[],[],["Relapsing fever NOS"],["Blood smear"]],
  ["A69.0","Vincent angina","A69",[],[],[],["Trench mouth","Acute necrotizing ulcerative gingivitis"],["Throat culture"]],
  ["A69.1","Other Vincent infections","A69",[],[],[],["Other fusospirochetal infections"],["Culture"]],
  ["A69.2","Lyme disease","A69",[],[],[],["Lyme borreliosis","Lyme arthritis"],["Lyme serology","ELISA","Western blot"]],
  ["A69.3","Neuroborreliosis","A69",[],[],[],["Lyme meningitis","Lyme encephalopathy"],["Lyme serology","LP","CSF analysis"]],
  ["A69.8","Other specified spirochetal infections","A69",[],[],[],["Other spirochetal infections"],["Culture","Serology"]],
  ["A69.9","Spirochetal infection, unspecified","A69",[],[],[],["Spirochetal infection NOS"],["Culture","Serology"]],
  ["A70","Chlamydia psittaci infections","A70",[],[],[],["Psittacosis","Ornithosis"],["Serology","Culture","Chest X-ray"]],
  ["A71.0","Initial stage of trachoma","A71",[],[],[],["Trachoma initial"],["Eye examination"]],
  ["A71.1","Active stage of trachoma","A71",[],[],[],["Trachoma active"],["Eye examination"]],
  ["A74.0","Chlamydial conjunctivitis","A74",[],[],[],["Inclusion conjunctivitis"],["Eye swab"]],
  ["A74.1","Chlamydial oculogenital syndrome","A74",[],[],[],["Chlamydial oculogenital"],["NAAT"]],
  ["A74.8","Other chlamydial diseases","A74",[],[],[],["Other chlamydial infections"],["Culture","NAAT"]],
  ["A74.9","Chlamydial infection, unspecified","A74",[],[],[],["Chlamydial NOS"],["NAAT"]],
  ["A75.0","Epidemic louse-borne relapsing fever","A75",[],[],[],["Louse-borne relapsing fever"],["Blood smear"]],
  ["A75.1","Epidemic typhus due to Rickettsia prowazekii","A75",[],[],[],["Epidemic typhus"],["Serology","PCR"]],
  ["A75.2","Endemic typhus due to Rickettsia typhi","A75",[],[],[],["Murine typhus"],["Serology"]],
  ["A75.3","Scrub typhus due to Orientia tsutsugamushi","A75",[],[],[],["Scrub typhus"],["Serology","PCR"]],
  ["A75.9","Typhus, unspecified","A75",[],[],[],["Typhus NOS"],["Serology"]],
  ["A77.0","Spotted fever due to Rickettsia rickettsii","A77",[],[],[],["Rocky Mountain spotted fever"],["Serology","PCR"]],
  ["A77.1","Spotted fever due to Rickettsia conorii","A77",[],[],[],["Mediterranean spotted fever"],["Serology"]],
  ["A77.2","Spotted fever due to Rickettsia akari","A77",[],[],[],["Rickettsialpox"],["Serology"]],
  ["A77.3","Spotted fever due to Rickettsia australis","A77",[],[],[],["Queensland tick typhus"],["Serology"]],
  ["A77.4","Boutonneuse fever","A77",[],[],[],["Boutonneuse fever"],["Serology"]],
  ["A77.8","Other spotted fevers","A77",[],[],[],["Other rickettsial spotted fevers"],["Serology"]],
  ["A77.9","Spotted fever, unspecified","A77",[],[],[],["Spotted fever NOS"],["Serology"]],
  ["A78","Q fever","A78",[],[],[],["Coxiella burnetii infection"],["Serology","PCR"]],
  ["A79.0","Trench fever","A79",[],[],[],["Trench fever","Quintana fever"],["Serology","PCR"]],
  ["A79.1","Rickettsialpox","A79",[],[],[],["Rickettsialpox"],["Serology"]],
  ["A79.8","Other rickettsioses","A79",[],[],[],["Other rickettsial infections"],["Serology"]],
  ["A79.9","Rickettsiosis, unspecified","A79",[],[],[],["Rickettsial infection NOS"],["Serology"]],
  ["A80.0","Acute paralytic poliomyelitis, wild","A80",[],[],[],["Acute paralytic polio (wild)"],["Stool viral culture","CSF analysis"]],
  ["A80.1","Acute paralytic poliomyelitis, vaccine","A80",[],[],[],["Vaccine-associated paralytic polio"],["Stool viral culture","CSF analysis"]],
  ["A80.2","Acute paralytic poliomyelitis, unspecified","A80",[],[],[],["Acute paralytic polio NOS"],["Stool viral culture"]],
  ["A80.3","Acute nonparalytic poliomyelitis","A80",[],[],[],["Acute nonparalytic polio"],["Stool viral culture"]],
  ["A80.4","Acute poliomyelitis, unspecified","A80",[],[],[],["Acute polio NOS"],["Stool viral culture"]],
  ["A80.8","Other acute poliomyelitis","A80",[],[],[],["Other acute polio"],["Stool viral culture"]],
  ["A80.9","Acute poliomyelitis, unspecified","A80",[],[],[],["Polio NOS"],["Stool viral culture"]],
  ["A81.0","Creutzfeldt-Jakob disease","A81",[],[],[],["CJD"],["Brain MRI","EEG","CSF analysis","Brain biopsy"]],
  ["A81.1","Subacute sclerosing panencephalitis","A81",[],[],[],["SSPE"],["CSF measles antibody","EEG"]],
  ["A81.2","Progressive multifocal leukoencephalopathy","A81",[],[],[],["PML"],["Brain MRI","CSF JC virus PCR"]],
  ["A81.3","Other cerebral degenerations","A81",[],[],[],["Other cerebral degenerations"],["Brain MRI","Biopsy"]],
  ["A81.8","Other atypical virus infections of central nervous system","A81",[],[],[],["Other atypical CNS infections"],["Various"]],
  ["A81.9","Atypical virus infection of central nervous system, unspecified","A81",[],[],[],["Atypical CNS infection NOS"],["Various"]],
  ["A82.0","Sylvatic rabies","A82",[],[],[],["Sylvatic rabies"],["Viral studies"]],
  ["A82.1","Urban rabies","A82",[],[],[],["Urban rabies"],["Viral studies"]],
  ["A82.9","Rabies, unspecified","A82",[],[],[],["Rabies NOS"],["Viral studies"]],
  ["A83.0","Japanese encephalitis","A83",[],[],[],["Japanese B encephalitis"],["Serology","CSF analysis"]],
  ["A83.1","Western equine encephalitis","A83",[],[],[],["WEE"],["Serology"]],
  ["A83.2","Eastern equine encephalitis","A83",[],[],[],["EEE"],["Serology"]],
  ["A83.3","St. Louis encephalitis","A83",[],[],[],["SLE"],["Serology"]],
  ["A83.4","Australian encephalitis","A83",[],[],[],["Murray Valley encephalitis"],["Serology"]],
  ["A83.5","California encephalitis","A83",[],[],[],["California encephalitis"],["Serology"]],
  ["A83.6","Rocio virus disease","A83",[],[],[],["Rocio encephalitis"],["Serology"]],
  ["A83.8","Other mosquito-borne viral encephalitis","A83",[],[],[],["Other mosquito-borne encephalitis"],["Serology"]],
  ["A83.9","Mosquito-borne viral encephalitis, unspecified","A83",[],[],[],["Mosquito-borne encephalitis NOS"],["Serology"]],
  ["A84.0","Far East encephalitis","A84",[],[],[],["Tick-borne encephalitis"],["Serology"]],
  ["A84.1","Central European encephalitis","A84",[],[],[],["Meningoencephalitis"],["Serology"]],
  ["A84.2","Siberian encephalitis","A84",[],[],[],["Siberian tick-borne encephalitis"],["Serology"]],
  ["A84.8","Other tick-borne viral encephalitis","A84",[],[],[],["Other TBE"],["Serology"]],
  ["A84.9","Tick-borne viral encephalitis, unspecified","A84",[],[],[],["TBE NOS"],["Serology"]],
  ["A85.0","Enteroviral encephalitis","A85",[],[],[],["Enteroviral encephalitis"],["CSF viral PCR"]],
  ["A85.1","Adenoviral encephalitis","A85",[],[],[],["Adenoviral encephalitis"],["CSF viral PCR"]],
  ["A85.2","Arthropod-borne viral encephalitis, unspecified","A85",[],[],[],["Arboviral encephalitis NOS"],["Serology"]],
  ["A85.8","Other specified viral encephalitis","A85",[],[],[],["Other viral encephalitis"],["CSF viral PCR"]],
  ["A86","Unspecified viral encephalitis","A86",[],[],[],["Viral encephalitis NOS"],["CSF analysis","Imaging"]],
  ["A87.0","Enteroviral meningitis","A87",[],[],[],["Enteroviral meningitis"],["CSF viral PCR"]],
  ["A87.1","Adenoviral meningitis","A87",[],[],[],["Adenoviral meningitis"],["CSF viral PCR"]],
  ["A87.2","Lymphocytic choriomeningitis","A87",[],[],[],["LCM meningitis"],["CSF analysis","Serology"]],
  ["A87.3","Meningitis due to other enteroviruses","A87",[],[],[],["Other enteroviral meningitis"],["CSF viral PCR"]],
  ["A87.8","Other viral meningitis","A87",[],[],[],["Other viral meningitis"],["CSF viral PCR"]],
  ["A87.9","Viral meningitis, unspecified","A87",[],[],[],["Viral meningitis NOS"],["CSF analysis"]],
  ["A88.0","Epidemic vertigo","A88",[],[],[],["Vestibular neuronitis"],["Clinical diagnosis"]],
  ["A88.1","Epidemic arthralgia","A88",[],[],[],["Epidemic arthralgia"],["Clinical diagnosis"]],
  ["A88.8","Other specified viral infections of central nervous system","A88",[],[],[],["Other viral CNS infections"],["CSF analysis","Imaging"]],
  ["A89","Unspecified viral infection of central nervous system","A89",[],[],[],["Viral CNS infection NOS"],["CSF analysis"]],
  ["A92.0","Chikungunya virus disease","A92",[],[],[],["Chikungunya"],["Viral PCR","Serology"]],
  ["A92.1","O'nyong-nyong fever","A92",[],[],[],["O'nyong-nyong"],["Serology"]],
  ["A92.2","Venezuelan equine fever","A92",[],[],[],["VEE"],["Serology"]],
  ["A92.3","West Nile virus infection","A92",[],[],[],["West Nile fever"],["Serology","CSF PCR"]],
  ["A92.4","Rift Valley fever","A92",[],[],[],["Rift Valley fever"],["Serology","PCR"]],
  ["A92.5","Zika virus disease","A92",[],[],[],["Zika infection"],["Serology","PCR","RT-PCR"]],
  ["A92.8","Other specified mosquito-borne viral fevers","A92",[],[],[],["Other mosquito-borne fevers"],["Serology"]],
  ["A92.9","Mosquito-borne viral fever, unspecified","A92",[],[],[],["Mosquito-borne fever NOS"],["Serology"]],
  ["A93.0","Oropouche virus disease","A93",[],[],[],["Oropouche fever"],["Serology","PCR"]],
  ["A93.1","Sandfly fever","A93",[],[],[],["Sandfly fever","Phlebotomus fever"],["Serology"]],
  ["A93.2","Colorado tick fever","A93",[],[],[],["Colorado tick fever"],["Serology","Blood smear"]],
  ["A93.8","Other arthropod-borne viral fevers, not elsewhere classified","A93",[],[],[],["Other arboviral fevers"],["Serology"]],
  ["A94","Unspecified arthropod-borne viral fever","A94",[],[],[],["Arboviral fever NOS"],["Serology"]],
  ["A95.0","Sylvatic yellow fever","A95",[],[],[],["Yellow fever"],["Serology","PCR"]],
  ["A95.1","Urban yellow fever","A95",[],[],[],["Yellow fever urban"],["Serology","PCR"]],
  ["A95.2","Yellow fever, unspecified","A95",[],[],[],["Yellow fever NOS"],["Serology","PCR"]],
  ["A95.9","Yellow fever, unspecified","A95",[],[],[],["Yellow fever NOS"],["Serology","PCR"]],
  ["A96.0","Junin hemorrhagic fever","A96",[],[],[],["Junin virus hemorrhagic fever"],["Serology","PCR"]],
  ["A96.1","Machupo hemorrhagic fever","A96",[],[],[],["Machupo virus hemorrhagic fever"],["Serology","PCR"]],
  ["A96.2","Lassa fever","A96",[],[],[],["Lassa hemorrhagic fever"],["Serology","PCR","Viral isolation"]],
  ["A96.8","Other arenaviral hemorrhagic fevers","A96",[],[],[],["Other arenaviral HF"],["Serology","PCR"]],
  ["A96.9","Arenaviral hemorrhagic fever, unspecified","A96",[],[],[],["Arenaviral HF NOS"],["Serology","PCR"]],
  ["A98.0","Crimean-Congo hemorrhagic fever","A98",[],[],[],["CCHF"],["Serology","PCR"]],
  ["A98.1","Korean hemorrhagic fever","A98",[],[],[],["HFRS"],["Serology","PCR"]],
  ["A98.2","Omsk hemorrhagic fever","A98",[],[],[],["Omsk HF"],["Serology"]],
  ["A98.3","Marburg virus disease","A98",[],[],[],["Marburg hemorrhagic fever"],["PCR","Viral isolation"]],
  ["A98.4","Ebola virus disease","A98",[],[],[],["Ebola hemorrhagic fever"],["PCR","Viral isolation","Antigen test"]],
  ["A98.5","Other viral hemorrhagic fevers","A98",[],[],[],["Other viral HF"],["Serology","PCR"]],
  ["A99","Unspecified viral hemorrhagic fever","A99",[],[],[],["Viral hemorrhagic fever NOS"],["Serology","PCR"]],
  ["B00.0","Herpetic gingivostomatitis","B00",[],[],[],["Herpetic mouth infection"],["Viral culture","PCR"]],
  ["B00.1","Herpetic eczema","B00",[],[],[],["Herpes eczema"],["Viral culture"]],
  ["B00.2","Herpesviral oculitis","B00",[],[],[],["Herpes eye infection"],["Slit-lamp exam","Viral culture"]],
  ["B00.3","Herpesviral meningitis","B00",[],[],[],["HSV meningitis"],["LP","CSF viral PCR"]],
  ["B00.4","Herpesviral encephalitis","B00",[],[],[],["HSV encephalitis"],["Brain MRI","CSF viral PCR","EEG"]],
  ["B00.5","Herpesviral disease of eye","B00",[],[],[],["Ocular herpes"],["Ophthalmologic exam","Viral culture"]],
  ["B00.7","Disseminated herpesviral disease","B00",[],[],[],["Disseminated HSV"],["Viral culture","PCR"]],
  ["B00.8","Other herpesviral infections","B00",[],[],[],["Other herpes infections"],["Viral culture","PCR"]],
  ["B00.9","Herpesviral infection, unspecified","B00",[],[],[],["Herpes simplex NOS"],["Viral culture","PCR"]],
  ["B01.0","Varicella meningitis","B01",[],[],[],["Varicella meningitis"],["LP","CSF PCR"]],
  ["B01.1","Varicella encephalitis","B01",[],[],[],["Varicella encephalitis"],["Brain MRI","CSF PCR"]],
  ["B01.2","Varicella pneumonia","B01",[],[],[],["Varicella pneumonia"],["Chest X-ray","Viral PCR"]],
  ["B01.8","Other varicella complications","B01",[],[],[],["Other varicella complications"],["Culture","PCR"]],
  ["B01.9","Varicella without complication","B01",[],[],[],["Chickenpox"],["Clinical diagnosis"]],
  ["B02.0","Herpes zoster encephalitis","B02",[],[],[],["Zoster encephalitis"],["Brain MRI","CSF PCR"]],
  ["B02.1","Herpes zoster meningitis","B02",[],[],[],["Zoster meningitis"],["LP","CSF PCR"]],
  ["B02.2","Herpes zoster with other nervous system complications","B02",[],[],[],["Zoster with neuro complications"],["EMG","NCS"]],
  ["B02.3","Herpes zoster with ophthalmic complications","B02",[],[],[],["Zoster ophthalmicus"],["Ophthalmologic exam"]],
  ["B02.8","Herpes zoster with other specified complications","B02",[],[],[],["Other zoster complications"],["Culture","PCR"]],
  ["B02.9","Herpes zoster without complication","B02",[],[],[],["Shingles"],["Clinical diagnosis"]],
  ["B03","Smallpox","B03",[],[],[],["Variola"],["Viral culture","PCR"]],
  ["B04","Monkeypox","B04",[],[],[],["Mpox","Monkeypox"],["PCR","Viral culture"]],
  ["B05.0","Measles complicated by encephalitis","B05",[],[],[],["Measles encephalitis"],["CSF PCR","Serology"]],
  ["B05.1","Measles complicated by meningitis","B05",[],[],[],["Measles meningitis"],["CSF analysis","Serology"]],
  ["B05.2","Measles with pneumonia","B05",[],[],[],["Measles pneumonia"],["Chest X-ray","Serology"]],
  ["B05.3","Measles with intestinal complications","B05",[],[],[],["Measles enteritis"],["Serology"]],
  ["B05.4","Measles with other complications","B05",[],[],[],["Other measles complications"],["Serology"]],
  ["B05.8","Measles without complication","B05",[],[],[],["Measles"],["Serology","Viral culture"]],
  ["B05.9","Measles, unspecified","B05",[],[],[],["Measles NOS"],["Serology"]],
  ["B06.0","Rubella with neurological complications","B06",[],[],[],["Rubella encephalitis"],["CSF PCR","Serology"]],
  ["B06.1","Rubella with other complications","B06",[],[],[],["Other rubella complications"],["Serology"]],
  ["B06.2","Rubella with neurological complications","B06",[],[],[],["Rubella meningitis"],["CSF analysis","Serology"]],
  ["B06.3","Rubella with other complications","B06",[],[],[],["Rubella pneumonia"],["Chest X-ray","Serology"]],
  ["B06.8","Rubella with other specified complications","B06",[],[],[],["Other rubella complications"],["Serology"]],
  ["B06.9","Rubella without complication","B06",[],[],[],["Rubella","German measles"],["Serology"]],
  ["B07","Viral warts","B07",[],[],[],["Common wart","Plantar wart","Flat wart","Genital wart"],["Visual examination","Biopsy"]],
  ["B08.0","Other orthopoxvirus infections","B08",[],[],[],["Molluscum contagiosum"],["Visual examination","Biopsy"]],
  ["B08.1","Molluscum contagiosum","B08",[],[],[],["Water warts","Molluscum"],["Visual examination"]],
  ["B08.2","Hand, foot and mouth disease","B08",[],[],[],["HFMD"],["Clinical diagnosis"]],
  ["B08.20","Hand, foot and mouth disease due to Coxsackievirus","B08",[],[],[],["Coxsackievirus HFMD"],["Stool viral PCR"]],
  ["B08.21","Hand, foot and mouth disease due to Enterovirus 71","B08",[],[],[],["EV71 HFMD"],["Stool viral PCR"]],
  ["B08.22","Hand, foot and mouth disease due to Enterovirus, other","B08",[],[],[],["Other enteroviral HFMD"],["Stool viral PCR"]],
  ["B08.23","Hand, foot and mouth disease due to Coxsackievirus, other","B08",[],[],[],["Other coxsackieviral HFMD"],["Stool viral PCR"]],
  ["B08.3","Erythema infectiosum","B08",[],[],[],["Fifth disease","Slapped cheek disease"],["Serology","Parvovirus B19 IgM"]],
  ["B08.4","Enteroviral vesicular pharyngitis","B08",[],[],[],["Herpangina"],["Stool viral PCR"]],
  ["B08.5","Vesicular stomatitis","B08",[],[],[],["VSV infection"],["Serology"]],
  ["B08.6","Parapoxvirus infection","B08",[],[],[],["Orf","Milker nodule"],["Clinical diagnosis"]],
  ["B08.8","Other specified viral infections","B08",[],[],[],["Other viral skin infections"],["Viral culture","PCR"]],
  ["B09","Unspecified viral infection characterized by skin and mucous membrane lesions","B09",[],[],[],["Viral exanthem NOS"],["Viral studies"]],
  ["B15.0","Hepatitis A with hepatic coma","B15",[],[],[],["Hepatitis A with coma"],["HAV IgM","LFTs","Coagulation studies"]],
  ["B15.9","Hepatitis A without hepatic coma","B15",[],[],[],["Hepatitis A"],["HAV IgM","LFTs"]],
  ["B16.0","Acute hepatitis B with delta-agent coinfection with hepatic coma","B16",[],[],[],["HBV + HDV with coma"],["HBsAg","HDAg","LFTs"]],
  ["B16.1","Acute hepatitis B with delta-agent coinfection without hepatic coma","B16",[],[],[],["HBV + HDV coinfection"],["HBsAg","HDAg","LFTs"]],
  ["B16.2","Acute hepatitis B without delta-agent with hepatic coma","B16",[],[],[],["HBV with coma"],["HBsAg","HBeAg","LFTs"]],
  ["B16.9","Acute hepatitis B without delta-agent and without hepatic coma","B16",[],[],[],["Acute hepatitis B"],["HBsAg","HBeAg","LFTs"]],
  ["B17.0","Acute delta-agent superinfection of hepatitis B carrier","B17",[],[],[],["HDV superinfection"],["HBsAg","HDAg"]],
  ["B17.1","Acute hepatitis C","B17",[],[],[],["Acute hepatitis C"],["HCV RNA","Anti-HCV"]],
  ["B17.2","Acute hepatitis E","B17",[],[],[],["Hepatitis E"],["HEV IgM","LFTs"]],
  ["B17.8","Other specified acute viral hepatitis","B17",[],[],[],["Other acute viral hepatitis"],["Serology","LFTs"]],
  ["B17.9","Acute viral hepatitis, unspecified","B17",[],[],[],["Acute hepatitis NOS"],["LFTs","Serology"]],
  ["B18.0","Chronic viral hepatitis B with delta-agent","B18",[],[],[],["Chronic HBV + HDV"],["HBsAg","HDAg","HBeAg"]],
  ["B18.1","Chronic viral hepatitis B without delta-agent","B18",[],[],[],["Chronic hepatitis B"],["HBsAg","HBeAg","HBV DNA"]],
  ["B18.2","Chronic viral hepatitis C","B18",[],[],[],["Chronic hepatitis C"],["Anti-HCV","HCV RNA","Genotype"]],
  ["B18.8","Other chronic viral hepatitis","B18",[],[],[],["Other chronic hepatitis"],["Serology","LFTs"]],
  ["B18.9","Chronic viral hepatitis, unspecified","B18",[],[],[],["Chronic hepatitis NOS"],["LFTs","Serology"]],
  ["B19.0","Unspecified viral hepatitis with hepatic coma","B19",[],[],[],["Viral hepatitis with coma"],["LFTs","Coagulation studies"]],
  ["B19.1","Unspecified viral hepatitis B without hepatic coma","B19",[],[],[],["Unspecified HBV"],["HBsAg","LFTs"]],
  ["B19.2","Unspecified viral hepatitis C without hepatic coma","B19",[],[],[],["Unspecified HCV"],["Anti-HCV","HCV RNA"]],
  ["B19.9","Unspecified viral hepatitis without hepatic coma","B19",[],[],[],["Unspecified viral hepatitis"],["LFTs","Serology"]],
  ["B20","Human immunodeficiency virus [HIV] disease","B20",[],[],[],["AIDS","HIV infection"],["HIV viral load","CD4 count","HIV antibody/antigen test"]],
  ["B25.0","Cytomegaloviral pneumonitis","B25",[],[],[],["CMV pneumonia"],["CMV PCR","BAL","Chest X-ray"]],
  ["B25.1","Cytomegaloviral hepatitis","B25",[],[],[],["CMV hepatitis"],["CMV PCR","LFTs"]],
  ["B25.2","Cytomegaloviral gastroenteritis","B25",[],[],[],["CMV GI infection"],["CMV PCR","Endoscopy","Biopsy"]],
  ["B25.8","Other cytomegaloviral diseases","B25",[],[],[],["Other CMV disease"],["CMV PCR"]],
  ["B25.9","Cytomegaloviral disease, unspecified","B25",[],[],[],["CMV disease NOS"],["CMV PCR"]],
  ["B26.0","Mumps orchitis","B26",[],[],[],["Mumps testicular inflammation"],["Mumps IgM","Serology"]],
  ["B26.1","Mumps meningitis","B26",[],[],[],["Mumps meningitis"],["Mumps IgM","LP"]],
  ["B26.2","Mumps encephalitis","B26",[],[],[],["Mumps encephalitis"],["Mumps IgM","Brain MRI"]],
  ["B26.3","Mumps pancreatitis","B26",[],[],[],["Mumps pancreatitis"],["Mumps IgM","Amylase","Lipase"]],
  ["B26.8","Mumps with other complications","B26",[],[],[],["Other mumps complications"],["Mumps IgM"]],
  ["B26.9","Mumps without complication","B26",[],[],[],["Mumps"],["Mumps IgM","Clinical diagnosis"]],
  ["B27.0","Epstein-Barr virus meningitis","B27",[],[],[],["EBV meningitis"],["EBV serology","LP"]],
  ["B27.1","Epstein-Barr virus encephalitis","B27",[],[],[],["EBV encephalitis"],["EBV serology","Brain MRI"]],
  ["B27.2","Epstein-Barr virus pneumonia","B27",[],[],[],["EBV pneumonia"],["EBV serology","Chest X-ray"]],
  ["B27.8","Other infectious mononucleosis","B27",[],[],[],["Other EBV disease"],["EBV serology"]],
  ["B27.9","Infectious mononucleosis, unspecified","B27",[],[],[],["Mono"],["EBV serology","Monospot test","CBC"]],
  ["B30.0","Epidemic keratoconjunctivitis","B30",[],[],[],["Adenoviral conjunctivitis"],["Eye swab","Viral culture"]],
  ["B30.1","Pharyngoconjunctival fever","B30",[],[],[],["Adenoviral pharyngoconjunctivitis"],["Throat swab","Viral culture"]],
  ["B30.2","Acute hemorrhagic conjunctivitis","B30",[],[],[],["AHC"],["Viral PCR"]],
  ["B30.3","Acute epidemic conjunctivitis","B30",[],[],[],["Epidemic conjunctivitis"],["Viral culture"]],
  ["B30.8","Other viral conjunctivitis","B30",[],[],[],["Other viral conjunctivitis"],["Viral culture"]],
  ["B30.9","Viral conjunctivitis, unspecified","B30",[],[],[],["Viral pink eye"],["Clinical diagnosis"]],
  ["B33.0","Epidemic myalgia due to Coxsackievirus","B33",[],[],[],["Epidemic pleurodynia","Bornholm disease"],["Serology","Stool viral PCR"]],
  ["B33.1","Ross River disease","B33",[],[],[],["Ross River virus disease"],["Serology"]],
  ["B33.2","Viral carditis","B33",[],[],[],["Viral myocarditis"],["Serology","Cardiac MRI"]],
  ["B33.3","Retrovirus infections, not elsewhere classified","B33",[],[],[],["Retroviral NOS"],["PCR"]],
  ["B33.4","Hantavirus pulmonary syndrome","B33",[],[],[],["HPS"],["Hantavirus IgM","PCR"]],
  ["B33.8","Other specified viral diseases","B33",[],[],[],["Other viral diseases"],["Various"]],
  ["B33.9","Viral disease, unspecified","B33",[],[],[],["Viral disease NOS"],["Viral studies"]],
  ["B34.0","Adenovirus infection, unspecified site","B34",[],[],[],["Adenovirus NOS"],["Viral culture","PCR"]],
  ["B34.1","Enterovirus infection, unspecified site","B34",[],[],[],["Enterovirus NOS"],["Viral PCR"]],
  ["B34.2","Coronavirus infection, unspecified site","B34",[],[],[],["Coronavirus NOS (non-COVID)"],["RT-PCR","Serology"]],
  ["B34.3","Parvovirus infection, unspecified site","B34",[],[],[],["Parvovirus NOS"],["Serology"]],
  ["B34.4","Rhinovirus infection, unspecified site","B34",[],[],[],["Rhinovirus NOS"],["Viral PCR"]],
  ["B34.8","Other viral infections of unspecified site","B34",[],[],[],["Other viral NOS"],["Various"]],
  ["B34.9","Viral infection, unspecified","B34",[],[],[],["Viral infection NOS"],["Viral studies"]],
  ["B35.0","Dermatophytosis of scalp and beard","B35",[],[],[],["Ringworm of scalp","Tinea capitis"],["KOH prep","Fungal culture"]],
  ["B35.1","Dermatophytosis of nails","B35",[],[],[],["Fungal nail infection","Onychomycosis","Toenail fungus"],["KOH prep","Nail culture"]],
  ["B35.2","Dermatophytosis of hand","B35",[],[],[],["Tinea manuum","Ringworm of hand"],["KOH prep"]],
  ["B35.3","Dermatophytosis of foot","B35",[],[],[],["Athlete's foot","Tinea pedis","Ringworm of foot"],["KOH prep"]],
  ["B35.4","Dermatophytosis of body","B35",[],[],[],["Ringworm of body","Tinea corporis"],["KOH prep"]],
  ["B35.5","Tinea cruris","B35",[],[],[],["Jock itch","Groin ringworm"],["KOH prep"]],
  ["B35.6","Dermatophytosis of groin","B35",[],[],[],["Tinea inguinalis"],["KOH prep"]],
  ["B35.8","Other dermatophytosis","B35",[],[],[],["Other tinea"],["KOH prep","Fungal culture"]],
  ["B35.9","Dermatophytosis, unspecified","B35",[],[],[],["Ringworm NOS"],["KOH prep"]],
  ["B37.0","Candidiasis of mouth","B37",[],[],[],["Oral thrush","Oral yeast infection"],["Oral swab","Gram stain"]],
  ["B37.1","Pulmonary candidiasis","B37",[],[],[],["Candida pneumonia"],["Sputum culture","BAL"]],
  ["B37.2","Candidiasis of vulva and vagina","B37",[],[],[],["Yeast infection","Vaginal yeast infection","VVC"],["Vaginal swab","Wet mount"]],
  ["B37.3","Candidiasis of urethra","B37",[],[],[],["Candidal urethritis"],["Urine culture","Urethral swab"]],
  ["B37.4","Candidiasis of other urogenital sites","B37",[],[],[],["Candidal UTI","Candidal cystitis"],["Urine culture"]],
  ["B37.8","Candidiasis of other sites","B37",[],[],[],["Esophageal candidiasis","Candidal esophagitis"],["Endoscopy","Culture"]],
  ["B37.9","Candidiasis, unspecified","B37",[],[],[],["Candidiasis NOS","Yeast infection NOS"],["Culture"]],
  ["B54","Unspecified malaria","B54",[],[],[],["Malaria"],["Blood smear","Rapid malaria test","PCR"]],
  ["B97.0","Reovirus as cause of disease classified elsewhere","B97",[],[],[],["Rotavirus gastroenteritis (secondary)"],["Stool rotavirus test"]],
  ["B97.1","Adenovirus as cause of disease classified elsewhere","B97",[],[],[],["Adenoviral infection (secondary)"],["Viral culture","PCR"]],
  ["B97.2","Coronavirus as cause of disease classified elsewhere","B97",[],[],[],["COVID-19","SARS-CoV-2 infection"],["RT-PCR","Rapid antigen test"]],
  ["B97.3","Retrovirus as cause of disease classified elsewhere","B97",[],[],[],["HTLV infection (secondary)"],["PCR","Serology"]],
  ["B97.4","Respiratory syncytial virus as cause of disease classified elsewhere","B97",[],[],[],["RSV bronchiolitis","RSV pneumonia"],["RSV nasal swab","PCR"]],
  ["B97.5","Rhinovirus as cause of disease classified elsewhere","B97",[],[],[],["Rhinoviral infection (secondary)"],["Nasal PCR"]],
  ["B97.6","Parvovirus B19 as cause of disease classified elsewhere","B97",[],[],[],["Fifth disease (secondary)"],["Parvovirus B19 IgM"]],
  ["B97.7","Mycoplasma as cause of disease classified elsewhere","B97",[],[],[],["Mycoplasma pneumonia (secondary)"],["Mycoplasma IgM","PCR"]],
  ["B97.8","Other viral agents as cause of disease classified elsewhere","B97",[],[],[],["Other viral agent (secondary)"],["Viral studies"]],
  ["B97.89","Other viral agents as cause of disease classified elsewhere","B97",[],[],[],["Other viral agent"],["Viral studies"]],
  ["B97.9","Viral agent, unspecified, as cause of disease classified elsewhere","B97",[],[],[],["Unspecified viral agent (secondary)"],["Viral studies"]],
  ["B99","Unspecified infectious disease","B99",[],[],[],["Infectious disease NOS"],["Culture","Serology"]]
];

ch1.forEach(function(c) {
  emitCode(c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7]);
});

console.log("Wrote " + ch1.length + " codes from Chapter I");

// Write this portion
fs.writeFileSync(path.join(__dirname, 'part-codes1.js'), out.join('\n'), 'utf8');
console.log("Part codes1 written, lines: " + out.length);
