// New denial code entries for data.js DENIAL_CODES array
// Append these to the existing array

  { code: 'CO-1', desc: 'The deductible amount has been applied to this claim. The patient is responsible' },
  { code: 'CO-3', desc: 'The coinsurance amount has been applied. The patient is responsible for a percen' },
  { code: 'CO-5', desc: 'The billed charge exceeds the fee schedule or maximum allowable amount. Payment ' },
  { code: 'CO-6', desc: 'Payment is based on a code-level agreed price or contracted rate between the pro' },
  { code: 'CO-7', desc: 'The benefit for this service is included in the payment for another service that' },
  { code: 'CO-8', desc: 'This claim or service has been previously submitted and processed. It is a dupli' },
  { code: 'CO-9', desc: 'The claim or service has been denied because it does not meet the payer's criter' },
  { code: 'CO-10', desc: 'The claim or service has been denied due to a coding or billing error that needs' },
  { code: 'CO-15', desc: 'The required authorization or precertification was not obtained before the servi' },
  { code: 'CO-24', desc: 'Payment has been adjusted because the charges have been paid by another payer or' },
  { code: 'CO-26', desc: 'Payment adjusted because the claim expenses have been previously paid by another' },
  { code: 'CO-51', desc: 'The claim amount exceeds the maximum allowable for the service under the patient' },
  { code: 'CO-54', desc: 'The CLIA (Clinical Laboratory Improvement Amendments) certification number is mi' },
  { code: 'CO-55', desc: 'The claim or service requires a different or additional information to process t' },
  { code: 'CO-58', desc: 'Services furnished to patients in a hospital outpatient setting are not covered ' },
  { code: 'CO-59', desc: 'The services are not covered under the patient's current benefit plan or are exc' },
  { code: 'CO-63', desc: 'The services have not been shown to be necessary or proper for the diagnosis or ' },
  { code: 'CO-70', desc: 'The billed charges exceed the allowed amount. Payment is based on the allowed am' },
  { code: 'CO-109', desc: 'The claim or service cannot be identified by the payer's system. The claim may h' },
  { code: 'CO-110', desc: 'The claim or service has been adjusted because the billing information is not as' },
  { code: 'CO-129', desc: 'Payment has been adjusted due to the amount being applied to the patient's cost-' },
  { code: 'CO-151', desc: 'The claim or service has been denied because the diagnosis code is not valid for' },
  { code: 'CO-181', desc: 'Payment has been adjusted because the procedure code and modifier combination is' },
  { code: 'CO-210', desc: 'Payment has been adjusted because the service is not payable under the patient's' },
  { code: 'CO-225', desc: 'The claim or service has been denied or adjusted because the ICD and CPT/HCPCS c' },
  { code: 'CO-230', desc: 'Payment has been adjusted because the claim does not meet the requirements for t' },
  { code: 'CO-232', desc: 'The claim or service has been denied because the procedure code is inconsistent ' },
  { code: 'CO-297', desc: 'The claim was denied because it was not submitted within the payer's timely fili' },
  { code: 'CO-300', desc: 'The claim has been denied because the patient's coverage was not effective on th' },
  { code: 'CO-331', desc: 'The claim has been denied because the appeal was not submitted within the requir' },
  { code: 'CO-340', desc: 'Payment has been adjusted because the claim does not meet the criteria for the b' },
  { code: 'CO-342', desc: 'The services are not covered because they are considered experimental, investiga' },
  { code: 'CO-349', desc: 'Payment has been adjusted because the claim was not properly coded or does not m' },
  { code: 'CO-351', desc: 'Payment has been adjusted because the claim does not meet the criteria for the b' },
  { code: 'CO-357', desc: 'Payment has been adjusted because the service was not provided in accordance wit' },
  { code: 'CO-360', desc: 'Payment has been adjusted because the claim was not submitted with the required ' },
  { code: 'CO-362', desc: 'Payment has been adjusted because the claim or service does not meet the payer's' },
  { code: 'CO-365', desc: 'Payment has been adjusted because the claim does not meet the requirements for t' },
  { code: 'CO-367', desc: 'Payment has been adjusted because the claim was submitted after the allowed fili' },
  { code: 'PR-22', desc: 'This care may be covered by another payer. Coordination of benefits may apply.' },
  { code: 'PR-23', desc: 'Payment adjusted because the claim was denied by the primary payer. Patient resp' },
  { code: 'PR-24', desc: 'The patient is responsible for the charges after insurance payment. This include' },
  { code: 'PR-26', desc: 'The patient is responsible for the cost of the service. Insurance has applied th' },
  { code: 'PR-27', desc: 'The patient is responsible for charges after the allowed amount has been paid by' },
  { code: 'PR-31', desc: 'The patient is responsible for the denied claim amount. Insurance has determined' },
  { code: 'PR-32', desc: 'The patient is responsible for the service charges. The claim has been processed' },
  { code: 'PR-33', desc: 'The copayment amount is due from the patient. This is the fixed amount the patie' },
  { code: 'PR-36', desc: 'The patient is responsible for charges related to services not covered by their ' },
  { code: 'PR-39', desc: 'The patient is responsible for charges that exceed the allowed amount under thei' },
  { code: 'PR-40', desc: 'Patient responsibility for charges after insurance adjudication. The balance is ' },
  { code: 'PR-41', desc: 'Patient responsible for charges related to a service that was denied or not cove' },
  { code: 'PR-42', desc: 'Patient is responsible for charges where the coverage limit has been reached.' },
  { code: 'PR-45', desc: 'Patient is responsible for charges due to a service not meeting medical necessit' },
  { code: 'PR-49', desc: 'Patient is responsible for charges related to services rendered by a non-partici' },
  { code: 'PR-50', desc: 'Patient is responsible for charges where the service is not a covered benefit un' },
  { code: 'PR-51', desc: 'Patient is responsible for charges where the service was provided during a waiti' },
  { code: 'PR-52', desc: 'Patient is responsible for charges related to a service that was not authorized ' },
  { code: 'PR-53', desc: 'Patient is responsible for charges where the service was provided outside the co' },
  { code: 'PR-54', desc: 'Patient is responsible for charges where the service exceeds the plan's benefit ' },
  { code: 'PR-55', desc: 'Patient is responsible for charges where the service was provided by an excluded' },
  { code: 'PR-56', desc: 'Patient is responsible for charges where the service was not medically necessary' },
  { code: 'PR-59', desc: 'Patient is responsible for charges where the service was provided during a perio' },
  { code: 'PR-66', desc: 'Patient is responsible for charges where the service was provided by an out-of-n' },
  { code: 'PR-119', desc: 'Patient is responsible for the benefit limit for this service. The plan's maximu' },
  { code: 'OA-24', desc: 'Payment adjusted because the charges have been paid by another payer or source. ' },
  { code: 'OA-26', desc: 'Payment adjusted because the claim expenses were previously paid by another sour' },
  { code: 'OA-27', desc: 'Payment denied because the patient was not eligible for coverage on the date of ' },
  { code: 'OA-29', desc: 'The claim was not submitted within the payer's timely filing deadline.' },
  { code: 'OA-45', desc: 'Payment adjusted based on the fee schedule or contracted rate. The billed amount' },
  { code: 'OA-94', desc: 'Payment adjusted because the claim was processed under a different plan or progr' },
  { code: 'OA-96', desc: 'Payment adjusted because the claim does not meet the requirements for the benefi' },
  { code: 'OA-109', desc: 'The claim cannot be identified by the payer's system. The claim may have incorre' },
  { code: 'OA-110', desc: 'The claim has been adjusted because billing information needs correction.' },
  { code: 'OA-170', desc: 'Payment adjusted because the service is not payable under the current benefit pl' },
  { code: 'OA-181', desc: 'Payment adjusted because the procedure code and modifier combination is not reco' },
  { code: 'OA-182', desc: 'Payment adjusted because the claim does not meet the payer's specific requiremen' },
  { code: 'OA-190', desc: 'Payment adjusted because the claim was not submitted with the required documenta' },
  { code: 'OA-197', desc: 'Payment denied because the required prior authorization was not obtained.' },
  { code: 'OA-198', desc: 'Payment denied because the certification/recertification was not obtained.' },
  { code: 'OA-204', desc: 'The claim was not submitted within the required filing timeframe.' },
  { code: 'OA-223', desc: 'Payment adjusted because the claim is for services related to a work-related inj' },
  { code: 'OA-234', desc: 'Payment adjusted because the claim is for services related to a motor vehicle ac' },
